### PR TITLE
New documentation tooling for Hugo work

### PR DESCRIPTION
**Pull request by moxiegirl**
Updating title and other things
Removing old mkdocs file
Updating with the new sed scripts
Moving from index.md swarm-overview.md

Signed-off-by: Mary Anthony <mary@docker.com>

ping @vieux @aluzzardi @abronan this the new docs tooling for 1.7.  Can I get an LGTM from one or more of you?

### CODE REVIEW

**Comment by vieux** [comment]
LGTM

**Comment by moxiegirl** [comment]
Thanks @vieux --- just as an FYI

### The "docs RC plan"

This is the first step to an "docs RC build" if you will.  

After I pull this PR and the other 6, I'm going to do a build to a staging bucket on S3.  That build will include the new theme which is dropping around noon Monday. I'll page through every page on the RC build:

- look for layout issues
- checking all the links
- making sure images appear

Each problem will be noted and then I'll do a set of follow on PRs to fix issues.  That's why I'm wanting to pull this set today, it allows for an RC cycle.  And then, also, if necessary one more before the release this week.

**Comment by abronan** [comment]
LGTM

ping @aluzzardi

**Comment by aluzzardi** [comment]
LGTM

**Comment by moxiegirl** [comment]
Thank you guys!

**Pull request merged**
