### PR TITLE
Leader Election: Use same path prefix as discovery.

### LINKED ISSUE #1037: key used by master election do not use the given path prefix
I want to start multiple swarm manager by using etcd.

eg.
```
swarm manager --replication --addr=127.0.0.1:2375 etcd://127.0.0.1:4001/myapp/swarm
```
the key used to elect master, is always `/docker/swarm/leader`, ignoring prefix `/myapp/swarm`

this is designed on purpose, or a negligence ?

### PR DESCRIPTION
**Pull request by aluzzardi**
Fixes #1037

Signed-off-by: Andrea Luzzardi <aluzzardi@gmail.com>

### CODE REVIEW

**Comment by vieux** [comment]
If I use `0.0.0.0:1234/swarm/myapp` the leader election prefix will be `/swarm/myapp/docker/swarm/leader` 

is that expected ?

**Comment by aluzzardi** [comment]
Yep - it will be `/swarm/myapp/docker/swarm/nodes` and `/swarm/myapp/docker/swarm/leader`

**Comment by aluzzardi** [comment]
We could change that by using `/docker/swarm` as default prefix and override it with the command line, although I'm not sure.

The reasoning is that you could have stuff such as `/swarm/myapp/docker/network/peers` or whatnot.

**Comment by vieux** [comment]
LGTM ping @abronan

**Comment by abronan** [comment]
@vieux See my comment on #1046. I'm LGTM and not against merging this PR first but ultimately it would be better if we could configure the prefix independently for both mechanisms.

**Pull request merged**
