### PR TITLE
fix list networks with filter {name: <overlay_network_name>}

### PR DESCRIPTION
**Pull request by BSWANG**
fix list networks with filter {name: {overlay_network_name}} fail
such as: 
<code>curl --globoff  http://host:port/v1.21/networks\?filters\="{\"name\":[\"multi-host-name\"]}"</code>

fix fail to inspect {node}/{overlay_network_name}
such as:
<code>docker inspect node1/multi-host-network</code>

### CODE REVIEW

**Comment by vieux** [comment]
@BSWANG can you please add a test ?

**Comment by BSWANG** [comment]
@vieux another bug (network filter) is rest API, I don't know how do test for rest API with bats.

**Comment by vieux** [comment]
@BSWANG after reading more carefully your comment, I think it's the expected behavior.

global scope networks aren't attached to a particular host, the are on the whole cluster, so to me it make no sens to support <node>/<network> with global scope networks 

@abronan ?

**Comment by BSWANG** [comment]
@vieux If it's a network on the whole cluster, the network's containers information should be combine of the nodes', but now is just containers of one node.

**Comment by vieux** [comment]
@BSWANG the fix for inspect is here: https://github.com/docker/swarm/pull/1547

**Pull request closed without merging**
