### PR TITLE
Implement engine refresh backoff strategy for failing nodes

### LINKED ISSUE #1766: Container running on unheathy node... for days...
Hi,
I was just going through the swarm logs and noticed this message about a node disconnecting:
 ```
time="2016-02-03T10:51:44Z" level=error msg="Slave 172.31.36.33 disconnected" 
time="2016-02-03T10:51:44Z" level=error msg="Slave 172.31.36.33 disconnected" 
time="2016-02-03T10:51:44Z" level=error msg="Slave 172.31.36.33 disconnected" 
time="2016-02-03T10:51:44Z" level=error msg="Slave 172.31.36.33 disconnected" 
time="2016-02-03T10:51:44Z" level=error msg="Flagging engine as unhealthy. Connect failed 3 times" id="OWEV:2C5D:OIAZ:JNDP:VSTK:JS5Q:2CH5:5NG7:2A34:U52V:LVEI:LV7D" name=ip-172-31-36-33.aws.cmcrc.com 
time="2016-02-03T10:51:55Z" level=error msg="HTTP error: Container 8aa0afc034a18b6cfa49eae0629d2f37846afdff9954ed5b62356590dc7b4f23 running on unhealthy node ip-172-31-36-33.aws.cmcrc.com" status=500 
time="2016-02-03T10:51:55Z" level=error msg="HTTP error: Container 0cf8f7b5a38090428f8ae0768e4bb3e46fa5726298f66b85bdcc8844752e0e08 running on unhealthy node ip-172-31-36-33.aws.cmcrc.com" status=500 
time="2016-02-03T10:51:55Z" level=error msg="HTTP error: Container feb481e9bb38d56cddff7dcfd46f5e73bb76c9218149a55131ca84ba40a7d641 running on unhealthy node ip-172-31-36-33.aws.cmcrc.com" status=500 
time="2016-02-03T10:51:55Z" level=error msg="HTTP error: Container 45d70576d424d202c7ed879f7b125e59d0bea40adae472372b630a3fc1275723 running on unhealthy node ip-172-31-36-33.aws.cmcrc.com" status=500 
time="2016-02-03T10:52:24Z" level=error msg="Update engine specs failed: Get http://172.31.36.33:2375/v1.15/info: dial tcp 172.31.36.33:2375: i/o timeout. Are you trying to connect to a TLS-enabled daemon without TLS?" id="OWEV:2C5D:OIAZ:JNDP:VSTK:JS5Q:2CH5:5NG7:2A34:U52V:LVEI:LV7D" name=ip-172-31-36-33.aws.cmcrc.com 
time="2016-02-03T10:52:26Z" level=error msg="HTTP error: Container 8aa0afc034a18b6cfa49eae0629d2f37846afdff9954ed5b62356590dc7b4f23 running on unhealthy node ip-172-31-36-33.aws.cmcrc.com" status=500 
time="2016-02-03T10:52:26Z" level=error msg="HTTP error: Container 0cf8f7b5a38090428f8ae0768e4bb3e46fa5726298f66b85bdcc8844752e0e08 running on unhealthy node ip-172-31-36-33.aws.cmcrc.com" status=500 
time="2016-02-03T10:52:26Z" level=error msg="HTTP error: Container feb481e9bb38d56cddff7dcfd46f5e73bb76c9218149a55131ca84ba40a7d641 running on unhealthy node ip-172-31-36-33.aws.cmcrc.com" status=500 
time="2016-02-03T10:52:26Z" level=error msg="HTTP error: Container 45d70576d424d202c7ed879f7b125e59d0bea40adae472372b630a3fc1275723 running on unhealthy node ip-172-31-36-33.aws.cmcrc.com" status=500 
time="2016-02-03T10:52:57Z" level=error msg="HTTP error: Container 8aa0afc034a18b6cfa49eae0629d2f37846afdff9954ed5b62356590dc7b4f23 running on unhealthy node ip-172-31-36-33.aws.cmcrc.com" status=500 
time="2016-02-03T10:52:57Z" level=error msg="HTTP error: Container 0cf8f7b5a38090428f8ae0768e4bb3e46fa5726298f66b85bdcc8844752e0e08 running on unhealthy node ip-172-31-36-33.aws.cmcrc.com" status=500 
time="2016-02-03T10:52:57Z" level=error msg="HTTP error: Container feb481e9bb38d56cddff7dcfd46f5e73bb76c9218149a55131ca84ba40a7d641 running on unhealthy node ip-172-31-36-33.aws.cmcrc.com" status=500 
time="2016-02-03T10:52:57Z" level=error msg="HTTP error: Container 45d70576d424d202c7ed879f7b125e59d0bea40adae472372b630a3fc1275723 running on unhealthy node ip-172-31-36-33.aws.cmcrc.com" status=500 
time="2016-02-03T10:53:21Z" level=error msg="Update engine specs failed: Get http://172.31.36.33:2375/v1.15/info: dial tcp 172.31.36.33:2375: i/o timeout. Are you trying to connect to a TLS-enabled daemon without TLS?" id="OWEV:2C5D:OIAZ:JNDP:VSTK:JS5Q:2CH5:5NG7:2A34:U52V:LVEI:LV7D" name=ip-172-31-36-33.aws.cmcrc.com 
```

The problem is that, 5 days later...

```
time="2016-02-07T23:46:40Z" level=error msg="HTTP error: Container 45d70576d424d202c7ed879f7b125e59d0bea40adae472372b630a3fc1275723 running on unhealthy node ip-172-31-36-33.aws.cmcrc.com" status=500 
time="2016-02-07T23:46:40Z" level=error msg="HTTP error: Container feb481e9bb38d56cddff7dcfd46f5e73bb76c9218149a55131ca84ba40a7d641 running on unhealthy node ip-172-31-36-33.aws.cmcrc.com" status=500 
time="2016-02-07T23:46:40Z" level=error msg="HTTP error: Container 0cf8f7b5a38090428f8ae0768e4bb3e46fa5726298f66b85bdcc8844752e0e08 running on unhealthy node ip-172-31-36-33.aws.cmcrc.com" status=500 
time="2016-02-07T23:46:40Z" level=error msg="HTTP error: Container 8aa0afc034a18b6cfa49eae0629d2f37846afdff9954ed5b62356590dc7b4f23 running on unhealthy node ip-172-31-36-33.aws.cmcrc.com" status=500 
```

And it goes on and on and on...

I guess there should be some kind of timeout where Swarm says... ok this node is gone for good. Any task there should be removed from my list.

Luck!
Guimo

### PR DESCRIPTION
**Pull request by dongluochen**
Fix #1766.
Signed-off-by: Dong Chen <dongluo.chen@docker.com>

### CODE REVIEW

**Comment by dongluochen** [comment]
The current change would break some existing changes where the manager is expected to refresh a failed node quickly. Need update. 

cc @vieux .

**Comment by dongluochen** [comment]
Change the implementation to use a backoff factor so the backoff speed is relative to user setting. Ready for review. 

cc @docker/swarm-maintainers.

**Comment by vieux** [comment]
LGTM

**Comment by chanwit** [comment]
LGTM

**Pull request merged**
