### PR TITLE
Add Allen Sun to MAINTAINERS file

### PR DESCRIPTION
**Pull request by dongluochen**
Allen has contributed large amount of effort to Swarm project. I'd like to invite Allen to join Swarm maintainers. 

/cc @docker/core-swarm-maintainers . 

Signed-off-by: Dong Chen <dongluo.chen@docker.com>

### CODE REVIEW

**Comment by abronan** [comment]
LGTM :tada:

**Comment by nishanttotla** [comment]
LGTM 🎉

**Comment by vieux** [comment]
LGTM

**Comment by jimmyxian** [comment]
LGTM,Congratulations

**Comment by allencloud** [comment]
Thank all of you.  :)

**Comment by abronan** [comment]
ping @docker/core-swarm-maintainers

**Comment by chanwit** [comment]
LGTM, congrats @allencloud !!

**Comment by MHBauer** [comment]
busy today, but totes. LGTM.

**Pull request merged**
