### PR TITLE
Fixes #1072 replacing boot2docker references

### LINKED ISSUE #1072: Replace references to boot2docker with docker-machine
`boot2docker` is replaced with `docker-machine` in 1.8 `boot2docker` is deprecated.

```
./swarm/docs/install-w-machine.md:	This example was run a Mac OSX system with `boot2docker` installed. So, the
./swarm/docs/install-w-machine.md:		`dev` environment in the list represents the `boot2docker` machine.
```

### PR DESCRIPTION
**Pull request by moxiegirl**
Added in Docker Toolbox/machine reference.
Closes #1072 

Signed-off-by: Mary Anthony <mary@docker.com>

### CODE REVIEW

**Comment by aluzzardi** [comment]
LGTM

**Comment by moxiegirl** [comment]
ping @vieux @abronan

**Comment by abronan** [comment]
LGTM

**Comment by moxiegirl** [comment]
\0/ Yay. Thanks guys.

**Pull request merged**
