### PR TITLE
integration: Add skeleton for missing integration tests.

### PR DESCRIPTION
**Pull request by aluzzardi**
Signed-off-by: Andrea Luzzardi <aluzzardi@gmail.com>

### CODE REVIEW

**Comment by aluzzardi** [comment]
See #492

**Comment by chanwit** [comment]
+1

**Comment by jimmyxian** [comment]
+1
I have done half of the apis integration test. If all test ok locally, i will subbmit it.
Also, i will implement the rest integration test one by one.

**Comment by vieux** [comment]
LGTM

**Pull request merged**
