### PR TITLE
Additional unit tests for generator.go

### PR DESCRIPTION
**Pull request by mgoelzer**
Added some unit tests.  Raises generator.go coverage to 100%

Signed-off-by: Mike Goelzer <mike@goelzer.com>

### CODE REVIEW

**Comment by mgoelzer** [comment]
This PR adds two unit tests and nothing else.  Yet it caused Coveralls to *decrease*.  Can anyone help me understand why that happened?

**Comment by aluzzardi** [comment]
Let's ignore the coverage errors since it's a bug with coveralls.

@chanwit: Care to take a look since you're the author of the generation code?

**Comment by chanwit** [comment]
@aluzzardi These tests go through the missing alternative path, so it looks good to me to have them here.

**Comment by aluzzardi** [comment]
Thanks @mgoelzer, much appreciated.

LGTM

Related to #502

**Pull request merged**
