### PR TITLE
add test for run --ip

### PR DESCRIPTION
**Pull request by vieux**

### CODE REVIEW

**Comment by vieux** [comment]
ping @dongluochen

**Comment by dongluochen** [comment]
Likely need to change space to tab in the test file.

**Comment by vieux** [comment]
@dongluochen my bad, PTAL

**Comment by vieux** [comment]
ping @abronan

**Comment by abronan** [comment]
LGTM

**Comment by vieux** [comment]
test failure unrelated

**Comment by dongluochen** [comment]
LGTM.

**Pull request merged**
