### PR TITLE
Updating the documentation

### PR DESCRIPTION
**Pull request by moxiegirl**
@vieux Fix of schedule docs.

Signed-off-by: Mary Anthony <mary@docker.com>

### CODE REVIEW

**Comment by vieux** [comment]
@moxiegirl shouldn't you remove `docs/rescheduling.md` ?

**Comment by moxiegirl** [comment]
@vieux I moved it into filters and it doesn't show underneath `docs/` in my branch.  GitHub "improved" their file listing interface.

**Comment by vieux** [comment]
It's still here, even in your branch: https://github.com/moxiegirl/swarm/blob/fix-reschedule-doc/docs/rescheduling.md

you need to `git rm docs/rescheduling.md`

**Comment by dongluochen** [comment]
LGTM

**Comment by vieux** [comment]
LGTM

**Comment by moxiegirl** [comment]
@vieux Thanks for the fix Vieux, I was on PTO Thursday/Fri.

**Pull request merged**
