### PR TITLE
validate duration flags: --delay, --timeout,--replication-ttl

### PR DESCRIPTION
**Pull request by allencloud**
validate duration flags:
1.--delay, must not be a negative number
2.--timeout, must be a positive number
3.--replication-ttl, must be a postive number

Add test details.
1. add test cases realated to --replication-ttl in replication.bats
2. add a test file cli_list.bats 
3. add a test file cli_join.bats

Signed-off-by: Sun Hongliang <allen.sun@daocloud.io>

### CODE REVIEW

**Comment by jimmyxian** [comment]
@allencloud Thanks :)
Can you also add some integration tests?

**Comment by allencloud** [comment]
@jimmyxian 
Yes, I  have added integration tests.

**Comment by vieux** [comment]
LGTM

**Comment by jimmyxian** [comment]
LGTM
Thanks @allencloud

**Pull request merged**
