### PR TITLE
Support 'docker update' command

### PR DESCRIPTION
**Pull request by dongluochen**
Signed-off-by: Dong Chen <dongluo.chen@docker.com>

### CODE REVIEW

**Comment by vieux** [comment]
LGTM !

**Comment by vieux** [comment]
@dongluochen I would do a `docker help | grep -q update` and skip the test if the update command in unknown.

**Comment by abronan** [comment]
@dongluochen I'm probably missing something obvious but I'm a bit concerned about the scheduler.

Can't we fall into a race where an `update` is issued for a container on a given node, but we try to start another container with what should be an invalid amount of RAM (which will overcommit) on the same node? `UsedCPUs` can be triggered at a moment where the container specs update is not yet processed thus the information might be stale at the scheduler level.

Supposedly because the lock on container `Refresh` is bounded to the `container` object while `UsedCPUs` is locked on the `engine` object.

For example on a node with **8GB** start a container with **4GB** reservation, update it to **6GB** reservation and make sure you can't start another container on the same node with **4GB** reservation. The second request should fail in this case.

Schedule and update containers very quickly and there is a chance I think to allow the second container to be scheduled and started even though it shouldn't. In this case using `update` could be "dangerous".

Maybe worth adding a test on `docker info` after container updates?

Unless this falls under the scope of another PR?

/cc @vieux

**Comment by dongluochen** [comment]
@abronan Thanks for the comment. I added docker info to reflect swarm's resource management. 

On the other hand, Engine is not rejecting requests over its resource limit. To make it work end to end, Engine may need to support that.

**Comment by dongluochen** [comment]
@vieux Thanks for the suggestion. I skip docker version without `update` support.

**Comment by vieux** [comment]
I agree with @dongluochen I think it should be fixed upstream in engine. It's good enough for now.

**Comment by abronan** [comment]
thanks @dongluochen. At least we should support `update` so LGTM, mentioned this issue just so we can keep this in mind.

ping @vieux

**Comment by abronan** [comment]
Woop done already haha :tada:

**Pull request merged**
