### PR TITLE
fix set reschedule policy docs

### PR DESCRIPTION
**Pull request by realityone**
Swarm can't detect `com.docker.swarm.reschedule-policy` label, and it should be `com.docker.swarm.reschedule-policies`.

Thanks.

Signed-off-by: realityone <realityone@me.com>

### CODE REVIEW

**Comment by vieux** [comment]
LGTM

**Comment by realityone** [comment]
Hi there, I have rebased codes from master.
Now all checks have passed yet.

**Comment by yank1** [comment]
LGTM

**Comment by dongluochen** [comment]
LGTM

**Pull request merged**
