### PR TITLE
move dependencies to vendor/

### LINKED ISSUE #2111: go get github.com/docker/swarm broken
It was working yesterday but today:

```
root@zhlpeer:/opt# export GOPATH=/opt/golang
root@zhlpeer:/opt# go get github.com/docker/swarm
# github.com/docker/swarm/api/nopclient
golang/src/github.com/docker/swarm/api/nopclient/nop.go:226: undefined: client.RequestPrivilegeFunc
golang/src/github.com/docker/swarm/api/nopclient/nop.go:231: undefined: client.RequestPrivilegeFunc
golang/src/github.com/docker/swarm/api/nopclient/nop.go:241: undefined: client.RequestPrivilegeFunc
```

### PR DESCRIPTION
**Pull request by vieux**
Closes #2111

### CODE REVIEW

**Comment by nishanttotla** [comment]
CI fails, it seems like linter is trying to check on dependencies too!

**Comment by vieux** [comment]
@nishanttotla PTAL

**Comment by nishanttotla** [comment]
Nice! This has my LGTM!

Btw, I'm assuming that `go get -u` takes care of building from `/vendor` automatically. If not, then this wouldn't fix #2111 right?

**Comment by vieux** [comment]
@nishanttotla I think `go get ` uses `/vendor`

**Comment by nishanttotla** [comment]
Ping @dongluochen

**Comment by dongluochen** [comment]
LGTM

**Comment by MHBauer** [comment]
ALRIGHT, w00h00!

**Pull request merged**
