### PR TITLE
Container name fix scheduler/filter/README.md

### PR DESCRIPTION
**Pull request by ahmetalpbalkan**
Signed-off-by: Ahmet Alp Balkan

### CODE REVIEW

**Comment by vieux** [comment]
@ahmetalpbalkan could you update `docs/scheduler/filter.md` as well please ?

**Comment by ahmetalpbalkan** [comment]
done

**Comment by vieux** [comment]
@ahmetalpbalkan thanks

**Comment by aluzzardi** [comment]
LGTM

**Comment by vieux** [comment]
ping @moxiegirl

**Comment by moxiegirl** [comment]
Thanks @ahmetalpbalkan LGTM !

@vieux Maybe I should just link the readme to the docs.

**Comment by vieux** [comment]
@moxiegirl what do you mean ?

**Comment by moxiegirl** [comment]
@ahmetalpbalkan The way the Swarm documentation was originally designed it consisted of a number of README's scattered throughout the repo dirs.  What I was suggesting is that rather than maintaining the information in two places, we link from the README to the docs.  I'd save the README for implementation details or guidance for people who want to contribute to or expand the feature.

**Comment by aluzzardi** [comment]
@moxiegirl Agreed - maybe we could remove the README altogether.

LGTM for this PR - @moxiegirl feel free to merge anytime. I think we should address the duplication in another PR (there might be other READMEs that need to be removed beside filter)

**Comment by moxiegirl** [comment]
@aluzzardi Thanks, that sounds reasonable to me.

**Pull request merged**
