### PR TITLE
pretty print mesos offers

### PR DESCRIPTION
**Pull request by vieux**
from

```
Containers: 0
Images: 12
Strategy: spread
Filters: affinity, health, constraint, port, dependency
Offers: 3
  Offer: 20150609-222929-1327399946-5050-14390-O5970
   └ cpus: &Resource{Name:*cpus,Type:*SCALAR,Scalar:&Value_Scalar{Value:*2,XXX_unrecognized:[],},Ranges:nil,Set:nil,Role:**,XXX_unrecognized:[],}
   └ mem: &Resource{Name:*mem,Type:*SCALAR,Scalar:&Value_Scalar{Value:*1006,XXX_unrecognized:[],},Ranges:nil,Set:nil,Role:**,XXX_unrecognized:[],}
   └ disk: &Resource{Name:*disk,Type:*SCALAR,Scalar:&Value_Scalar{Value:*35195,XXX_unrecognized:[],},Ranges:nil,Set:nil,Role:**,XXX_unrecognized:[],}
   └ ports: &Resource{Name:*ports,Type:*RANGES,Scalar:nil,Ranges:&Value_Ranges{Range:[&Value_Range{Begin:*31000,End:*32000,XXX_unrecognized:[],}],XXX_unrecognized:[],},Set:nil,Role:**,XXX_unrecognized:[],}
  Offer: 20150609-222929-1327399946-5050-14390-O5971
   └ cpus: &Resource{Name:*cpus,Type:*SCALAR,Scalar:&Value_Scalar{Value:*2,XXX_unrecognized:[],},Ranges:nil,Set:nil,Role:**,XXX_unrecognized:[],}
   └ mem: &Resource{Name:*mem,Type:*SCALAR,Scalar:&Value_Scalar{Value:*1006,XXX_unrecognized:[],},Ranges:nil,Set:nil,Role:**,XXX_unrecognized:[],}
   └ disk: &Resource{Name:*disk,Type:*SCALAR,Scalar:&Value_Scalar{Value:*35195,XXX_unrecognized:[],},Ranges:nil,Set:nil,Role:**,XXX_unrecognized:[],}
   └ ports: &Resource{Name:*ports,Type:*RANGES,Scalar:nil,Ranges:&Value_Ranges{Range:[&Value_Range{Begin:*31000,End:*32000,XXX_unrecognized:[],}],XXX_unrecognized:[],},Set:nil,Role:**,XXX_unrecognized:[],}
  Offer: 20150609-222929-1327399946-5050-14390-O5972
   └ cpus: &Resource{Name:*cpus,Type:*SCALAR,Scalar:&Value_Scalar{Value:*2,XXX_unrecognized:[],},Ranges:nil,Set:nil,Role:**,XXX_unrecognized:[],}
   └ mem: &Resource{Name:*mem,Type:*SCALAR,Scalar:&Value_Scalar{Value:*1006,XXX_unrecognized:[],},Ranges:nil,Set:nil,Role:**,XXX_unrecognized:[],}
   └ disk: &Resource{Name:*disk,Type:*SCALAR,Scalar:&Value_Scalar{Value:*35195,XXX_unrecognized:[],},Ranges:nil,Set:nil,Role:**,XXX_unrecognized:[],}
   └ ports: &Resource{Name:*ports,Type:*RANGES,Scalar:nil,Ranges:&Value_Ranges{Range:[&Value_Range{Begin:*31000,End:*32000,XXX_unrecognized:[],}],XXX_unrecognized:[],},Set:nil,Role:**,XXX_unrecognized:[],}
```

to

```
Containers: 0
Images: 12
Strategy: spread
Filters: affinity, health, constraint, port, dependency
Offers: 3
  Offer: 20150609-222929-1327399946-5050-14390-O6286
   └ cpus: 2
   └ mem: 1006 MiB
   └ disk: 34.37 GiB
   └ ports: 31000-32000
  Offer: 20150609-222929-1327399946-5050-14390-O6287
   └ cpus: 2
   └ mem: 1006 MiB
   └ disk: 34.37 GiB
   └ ports: 31000-32000
  Offer: 20150609-222929-1327399946-5050-14390-O6288
   └ cpus: 2
   └ mem: 1006 MiB
   └ disk: 34.37 GiB
   └ ports: 31000-32000
```

### CODE REVIEW

**Comment by vieux** [comment]
ping @tnachen @jimenez

**Comment by abronan** [comment]
LGTM :+1:

**Comment by jimenez** [comment]
LGTM

**Comment by tnachen** [comment]
Too amazing, LGTM

**Pull request merged**
