### PR TITLE
update compose, remove useless bash and improve tests

### PR DESCRIPTION
**Pull request by vieux**
Signed-off-by: Victor Vieux <vieux@docker.com>

### CODE REVIEW

**Comment by dongluochen** [comment]
Let's retry test on master. 

```
not ok 154 docker volume rm
# (from function `docker' in file api/../helpers.bash, line 42,
#  from function `docker_swarm' in file api/../helpers.bash, line 53,
#  in test file api/volume.bats, line 88)
#   `docker_swarm rm test_container' failed
...
# time="2016-04-14T21:33:57Z" level=debug msg="HTTP request received" method=DELETE uri="/v1.24/volumes/node-1/5472c846c475a45cb2091fa6023f143635f64619dc0e387b6ab968b6ebb33d6c" 
# time="2016-04-14T21:33:57Z" level=error msg="HTTP error: node-1: Error response from daemon: Unable to remove volume, volume still in use: remove 5472c846c475a45cb2091fa6023f143635f64619dc0e387b6ab968b6ebb33d6c: volume is in use - [25657b9a93051e1314f9ff7285f55e77d04a3841075825700eb3f72b7d75d951]" status=500 
# time="2016-04-14T21:33:57Z" level=debug msg="HTTP request received" method=DELETE uri="/v1.24/containers/test_container" 
# time="2016-04-14T21:33:57Z" level=error msg="HTTP error: 409 Conflict: You cannot remove a running container 25657b9a93051e1314f9ff7285f55e77d04a3841075825700eb3f72b7d75d951. Stop the container before attempting removal or use -f\n" status=500 
```

**Comment by vieux** [comment]
@dongluochen isn't is related to https://github.com/docker/swarm/pull/2116 ?

**Comment by dongluochen** [comment]
@vieux It looks like so.

**Comment by vieux** [comment]
@dongluochen @nishanttotla PTAL

**Comment by dongluochen** [comment]
LGTM

**Comment by MHBauer** [comment]
Did `top` change the default format recently?

**Comment by vieux** [comment]
@MHBauer it's using the host's top, the test now works with more base images

**Comment by abronan** [comment]
LGTM

**Pull request merged**
