### PR TITLE
Fix double RLock in Mesos cluster (apply PR #2210 to Mesos cluster)

### PR DESCRIPTION
**Pull request by ezrasilvera**
Apply the same fix as in #2210   to the MEsos cluster.
We are seeing the same hang ..

### CODE REVIEW

**Comment by allencloud** [comment]
LGTM

**Comment by allencloud** [comment]
Could you squash two commits into a single one please? @ezrasilvera

**Comment by ezrasilvera** [comment]
Done (format + squash )

**Comment by vieux** [comment]
LGTM

**Pull request merged**
