### PR TITLE
DO NOT MERGE - REVIEW ONLY require username and password for swarm create

### PR DESCRIPTION
**Pull request by vieux**
Close #695

The server side part, isn't live yet please review the code.

Added a `-u,--username` and `-p.--password` to `swarm create`
Alternatively you can do a swarm create and it will ask for the username and password (without echo, like docker login)

You can combine with: 
```
$ swarm create -u vieux
Password:

53128764320641268482352786912
```

### CODE REVIEW

**Comment by vieux** [comment]
ping @abronan @aluzzardi @jlhawn

**Comment by vieux** [comment]
I know the tests are broken, I did it on purpose so we don't merge.

**Comment by aluzzardi** [comment]
As discussed IRL, how about having `destroy` as well, requiring the same auth (both client and server side)

**Comment by aluzzardi** [comment]
Also, this set aside, how about moving from discovery-staging to discovery?

**Comment by vieux** [comment]
I agree on the destroy but let's change the url in another PR

**Comment by aluzzardi** [comment]
How about this workflow:

```
$ swarm create
Warning: Anonymous cluster created. Anonymous clusters can be destroyed by anyone with knowledge of the token. Please provide a `--username` in order to create an authenticated cluster.
53128764320641268482352786912
```

```
$ swarm create -u vieux
Password:
53128764320641268482352786912
```

/cc @bfirsh @shykes

**Comment by vieux** [comment]
ping @bfirsh @shykes

**Comment by moxiegirl** [comment]
@vieux Do we need to update the user-facing documentation for this? I saw you hit the token README

**Comment by moxiegirl** [comment]
@vieux We need to add to `docs/discover.md` , `install-manual.md`, `install-w-machine.md` that tells users that they will need to do this. I'm assuming that it is the `docker login` credentials.  That can happen after your merge if you are moving fast.

**Comment by Yam408** [comment]
H

**Pull request closed without merging**
