### PR TITLE
add Server Version to docker info

### PR DESCRIPTION
**Pull request by vieux**
Signed-off-by: Victor Vieux <vieux@docker.com>

### CODE REVIEW

**Comment by vieux** [comment]
ping @schmunk42

**Comment by schmunk42** [comment]
Nice :+1: I'd also like to see the version of the swarm image, if possible.

Sure, I can filter it with something like: `docker ps -a --filter name=swarm` on the swarm - but having it in `docker info` would also not be wrong.

**Comment by vieux** [comment]
@schmunk42 today you can use `docker version` :)

**Comment by schmunk42** [comment]
Thanks :D never noticed that.

**Comment by nishanttotla** [comment]
LGTM

**Pull request merged**
