### PR TITLE
Implement docker attach-ws api

### PR DESCRIPTION
**Pull request by jimmyxian**
Signed-off-by: Xian Chaobo <xianchaobo@huawei.com>

### CODE REVIEW

**Comment by vieux** [comment]
@how did you test this ?

**Comment by aluzzardi** [comment]
Thanks @jimmyxian !

Could you provide an integration test for this?

Details are here: https://github.com/docker/swarm/tree/master/test/integration

**Comment by aluzzardi** [comment]
Woops - just realized this is almost impossible to write, never mind.

**Comment by abronan** [comment]
We could maybe put a websocket CLI tool inside a container for the integration test?

**Comment by abronan** [comment]
Tested and works great. We will wait for the integration tests as this part is a bit tricky..

LGTM

**Comment by abronan** [comment]
Thanks @jimmyxian!

**Comment by jimmyxian** [comment]
I tested locally. It's OK. I will provide an integration test.

**Comment by aluzzardi** [comment]
@jimmyxian Thanks! Try to, but if the integration test is too much work don't bother.

**Comment by jimmyxian** [comment]
@aluzzardi OK, i will try it...  :)

**Pull request merged**
