### PR TITLE
Prevent adding ServerName to TLSConfig (Issue #2027)

### PR DESCRIPTION
**Pull request by echupriyanov**
Quick fix for #2027 

Signed-off-by: Eugene Chupriyanov <tchu@tchu.ru>

### CODE REVIEW

**Comment by vieux** [comment]
@echupriyanov we vendor the engine-api code.

Can you please open your PR upstream in https://github.com/docker/engine-api

**Comment by echupriyanov** [comment]
Will do. Frankly, I opened it here mostly to illustrate the cause of the problem. Maybe there is a better place to handle it? Another way is to clear `TLSConfig.ServerName` after each `engine.Connect()` call. That way we don;t depend on [engine-api](https://github.com/docker/engine-api)

**Comment by diogomonica** [comment]
This should be fine. IIRC, hostname will be taken from the server's address if none is given in the `tls.Config`.

The only place where I know playing with `ServerName` might be an issue is when creating a `tls.Client` directly, in which case not passing a `ServerName` might mean we're simply verifying the validity of the certificate chain.

**Comment by jpetazzo** [comment]
(Confirming that cherrypicking this solves #2027 for me)

**Comment by vieux** [comment]
@echupriyanov did you open the PR on engine-api ?

**Comment by echupriyanov** [comment]
Sorry, was busy at primary job. Will do now.

**Comment by echupriyanov** [comment]
Added PR (https://github.com/docker/engine-api/pull/173)

**Comment by echupriyanov** [comment]
Looks like my PR in docker/engine-api is not accepted. Another option I see is to modify `validatePendingEngine()` call to create a copy of `c.TLSConfig` and pass it to `engine.Connect()`.
I will try it tomorrow.

**Comment by echupriyanov** [comment]
@vieux I’m not sure my PR https://github.com/docker/engine-api/pull/173 will be accepted.
So here is another way to resolve certificate/ServerName problem.

**Comment by echupriyanov** [comment]
This PR is obsoleted by https://github.com/docker/engine-api/pull/179

**Comment by dongluochen** [comment]
Thank @echupriyanov for reporting the problem and helping with the fix.

**Pull request closed without merging**
