### PR TITLE
update all godeps

### PR DESCRIPTION
**Pull request by vieux**
replace https://github.com/docker/swarm/pull/1575

It's 2016, what do you say we update all godeps :)

ping @docker/swarm-maintainers

### CODE REVIEW

**Comment by dongluochen** [comment]
LGTM. Thanks @vieux!

**Comment by vieux** [comment]
ping @abronan @MHBauer @jimmyxian @chanwit

**Comment by abronan** [comment]
LGTM

**Comment by chanwit** [comment]
LGTM

**Comment by jimmyxian** [comment]
LGTM

**Comment by dongluochen** [comment]
:fireworks:

**Pull request merged**
