### PR TITLE
	fix soft / resource computation

### LINKED ISSUE #1698: Node resources are not considered in soft filter
Hi,

I have a concern about how soft filter works, let me explain it with an example:
There is only one node in swarm cluster: `node1` which has 4GB memory and a label `env=prod`, now user creates a container which requests 3GB memory and with a soft filter `constraint:env==~dev`, so the container can be created successfully in `node1` since the filter is soft and `node1` has enough memory for the container. So far so good.

But if there are two nodes in the cluster: `node1` (same with the above `node1`) and `node2` which has 2GB memory and a label `env=dev`, and user still creates a container which requests 3GB memory and with a soft filter `constraint:env==~dev`, but this time, the container will fail to be created due to no available nodes (`node2` does not have enough resources for the container). But I think it seems this does not make sense, the same container can be created when no nodes have the required label, but can NOT be created when there is a node has the required label.

IMHO, the container should be created in both of these two cases (in `node1`).

### PR DESCRIPTION
**Pull request by vieux**
The issue was clearly explained in #1698, thanks @zhq527725

Fix #1698

### CODE REVIEW

**Comment by vieux** [comment]
ping @abronan @dongluochen

**Comment by abronan** [comment]
@vieux The test failed on travis :cry:

**Comment by vieux** [comment]
@abronan whoops my bad

**Comment by abronan** [comment]
LGTM (failure related to #1709, so should be good to merge)

**Comment by vieux** [comment]
ping @dongluochen

**Comment by vieux** [comment]
ping @nishanttotla

**Comment by dongluochen** [comment]
@vieux LGTM for 1.1.0. I think there are some duplicate computation with current approach. I'd suggest we revisit it in the later releases.

**Comment by vieux** [comment]
@dongluochen agreed

**Pull request merged**
