### PR TITLE
add buildtime, kernelversion and experimental to API version

### PR DESCRIPTION
**Pull request by vieux**
follow up of #1626

It makes me very happy as we introduce the `engine-api` dependency,
we can slowly start using it instead of `samalba/dockerclient` (at least for all the types)

/cc @calavera @icecrime 

(I used it because, as usual, `samalba/dockerclient `has it's types outdated (no Experimental, BuildTime or KernelVersion in the Version struct))

### CODE REVIEW

**Comment by vieux** [comment]
ping @abronan @dongluochen, not mandatory for 1.10, but would be nice

**Comment by abronan** [comment]
LGTM :tada: :balloon:

**Comment by dongluochen** [comment]
LGTM. Thanks @vieux.

**Comment by icecrime** [comment]
:tada:

**Pull request merged**
