### PR TITLE
Fix reserved cpus computation

### PR DESCRIPTION
**Pull request by km4rcus**
This should fix the reserved cpus computation https://github.com/docker/swarm/issues/475#issuecomment-95858898

Signed-off-by: Marco Mancini <marcomancini72@gmail.com>

### CODE REVIEW

**Comment by vieux** [comment]
@km4rcus can you add a test ? Thank you.

**Comment by km4rcus** [comment]
@vieux I added test function and changed also the cpuShare computation when a container is created, otherwise usedCpu is wrong if NCPU is not a power of 2. Should I add to  test function several values for NCPU?

**Comment by vieux** [comment]
@km4rcus yes please if you can.

**Comment by km4rcus** [comment]
@vieux Added two arrays for testing different values for cpus.

**Comment by vieux** [comment]
@aluzzardi @abronan not sure what to do about this one, I would prefer to wait after the RC to merge it.

**Comment by aluzzardi** [comment]
@km4rcus So, actually, `-c 1` on a 1 CPU machine should give you 1024 shares by design.

The logic behind is explained in https://github.com/docker/swarm/issues/475#issuecomment-88258864

**Comment by vieux** [comment]
replaced by #904

**Pull request closed without merging**
