### PR TITLE
Pass the X-Registry-Auth info in createContainer for the internal pull

### PR DESCRIPTION
**Pull request by ezrasilvera**
Swarm performs internally a pull request if a createContainer failed. For that pull operation Swarm doesn't have the registry auth parameters so it can't support private registries.
While it's true that "docker run" doesn't pass such information it is still valuable capability as the user can either use the REST API directly and pass X-Registry-Auth during create-container or even use a config file with X-Registry-Auth info forcing "docker run" to pass this header
This change can be much simpler without changing any of the function signatures if the ContainerConfig in samalba.dockerclient would include also the registry auth info
This was briefly discussed in #1269 and I believe  that also #1197 

Signed-off-by: Ezra Silvera <ezra@il.ibm.com>

### CODE REVIEW

**Comment by aluzzardi** [comment]
Hey @ezrasilvera - thanks for the contribution.

The slight problem is that it requires the client to do custom things.

We have something in mind: change the Docker API so that `create` can actually pull the image if not there.

This means:
- `docker run` against swarm will actually give you the pull progress. Right now it just hangs since swarm is doing the pull for you in the background.
- `docker run` against swarm will actually pass the authentication details. Private registries will work with that

Thoughts? /cc @docker/swarm-maintainers 

We may still merge this PR while we work to do the previous

**Comment by ezrasilvera** [comment]
@aluzzardi thanks for the feedback. I fully agree that having the pull progress is an excellent idea. 
However I don't think the client need to do anything to support the change I proposed - if you just point the docker run (with the --config) to a config file with the X-Registry-Auth this will work out of the box (and is working already for us :-)  The "docker pull " is basically doing the same but pulling the information from the file generated by the login , so basically I don't see any additional requirement that we introduce to docker run . 
As this is a simple and quick solution I suggest we merge this while we wait for the more complete solution that you suggested. This will also allow more time to develop that other solution by giving the users a way to work with private registries (and this is mandatory for some of our customers)

**Comment by aluzzardi** [comment]
@ezrasilvera Could you provide an example of how to use it?

I wasn't aware there was a way to inject a X-Registry-Auth in a run :)

**Comment by ezrasilvera** [comment]
yep just put in your config.json something like:
{
  "HttpHeaders": {
    "X-Registry-Auth": <base64 string of your X-Registry-Auth info>
  }
}
and run will inject this header ...

**Comment by jimmyxian** [comment]
@ezrasilvera 
`docker run` do not have `--config` option. :)

**Comment by ezrasilvera** [comment]
@jimmyxian correct. My bad. Indeed for docker run we need to change the client to load the file. (I forgot I did it for our tests sorry for that ..   )
But again on the API (containers/create) there is no problem in doing that. So at least you can do something if this is a mandatory requirement for you (as it's the case for us)
I guess the main Q is  How simple is this fix (merge complexity + potential risk)   Vs., how soon are we going to have an alternative solution

**Comment by ezrasilvera** [comment]
@jimmyxian Actually, you can use the un-modfified client using "docker create" and the "docker start" . create does load the config AND send the info on the X-Registry-Auth.

**Comment by ezrasilvera** [comment]
@jimmyxian But you can still do "docker create" which does send the headers (and read the config) and then docker start, right ?    So one can use the unmodified client and be able to send the registry auth info...

**Comment by vieux** [comment]
@ezrasilvera I don't think `docker create` sends the header.

**Comment by ezrasilvera** [comment]
@vieux This is strange - As far as I can see (I just tested again just to be sure) both create and run do pass the headers from the config and I can also see the header in Swarm (the exact one I defined in my config).
I also looked in the docker code itself and it seems that the headers are sent for these commands ..
Which docker version are you using? This is supported in 1.8.1 and above.

**Comment by ezrasilvera** [comment]
@aluzzardi @vieux I tested the code with the latest Docker 1.9.0 and latest Swarm (I rebased the PR) and everything is working. In Docker 1.9 (as in 1.8) all relevant commands support the --config parameter allowing you to pass the X-Registry-Auth.

**Comment by garagatyi** [comment]
@aluzzardi Yes, this would be nice! 
It also solves problem when container should be created on one node only and it is waste of resources to pull it on all nodes.

**Comment by thaJeztah** [comment]
@ezrasilvera looks like you pulled in some none-related commits into your PR, also it's missing a sign-off

**Comment by thaJeztah** [comment]
@jimmyxian @vieux this PR can probably be closed, per https://github.com/docker/swarm/issues/1269#issuecomment-167292641 - and this should already be covered by https://github.com/docker/swarm/pull/1384 (didn't want to close this PR, because I'm not a maintainer here, but feel free to close it yourself, @ezrasilvera, if you think it should be closed)

**Pull request closed without merging**
