### PR TITLE
make the command clearly

### PR DESCRIPTION
**Pull request by xcl3721**
Signed-off-by:Changlong.Xu <xcl_rockman@qq.com>

make the command clearly 

Example haven't show that

you must connect to swarm manager!

please added it

and before pull request will be deleted

### CODE REVIEW

**Comment by jimmyxian** [comment]
@xcl3721 Thanks
Could you please sign your commits ? :)

**Comment by vieux** [comment]
LGTM ping @moxiegirl

**Comment by moxiegirl** [comment]
@xcl3721 Thank you for the contribution.  The actual documentation lives in `docs/schedule/strategy.md` we need to make the change there.  I can handle it in a carry if you prefer.

@vieux  I'm kind of inclined to remove this README.  Is there any reason we want to keep it around?

**Comment by xcl3721** [comment]
no pb.i'm bad in english thank u very much

**Comment by moxiegirl** [comment]
Thank you @xcl3721 discovering the problem. 

@vieux If you are cool with my comment to remove the README and update the doc, I'll carry.

**Comment by vieux** [comment]
I find it useful when you browse github as a contributor.

We have the same for filter.

Are you ok with replacing the readme with a link to our doc ? but at least keep a file called readme.md (maybe the github UI will follow the link)

**Comment by xcl3721** [comment]
ok，i will change filter file on doc

**Comment by amitshukla** [comment]
@xcl3721 any update?

**Comment by vieux** [comment]
@moxiegirl what do you think of this one ?

**Comment by moxiegirl** [comment]
@vieux I'm a bit leary of doing it this way but @xcl3721 has a point in that the commands assume you have a terminal on the manager --- so he was confused.

I'm LGTM but we need to revisit later date and clean up.

**Pull request merged**
