### PR TITLE
[eventsHandler] Use Lock/Unlock to sync a write access

### PR DESCRIPTION
**Pull request by noxiouz**
Handle method modifies internal maps, so we have to use Lock/Unlock

### CODE REVIEW

**Comment by aluzzardi** [comment]
Not sure this is the right way to go: I'm worried it would cause lots of lock contention since the handler is writing to the network and it might take a while.

Any better idea?

/cc @vieux @abronan

**Comment by noxiouz** [comment]
the modification section was moved out of the reading section

**Comment by vieux** [comment]
LGTM

**Comment by noxiouz** [comment]
Sorry, I accidentally removed the branch. It's restored now

**Comment by aluzzardi** [comment]
LGTM

@vieux ?

**Comment by vieux** [comment]
LGTM

**Pull request merged**
