### PR TITLE
Updated Swarm with Machine documentation

### PR DESCRIPTION
**Pull request by jonasrosland**
Removed a lot of information that's not useful for beginners getting started with Docker Swarm.
Rewrote large portions to make use of the `swarm` commands instead of manual configuration.

Signed-off-by: jonasrosland <jonas.rosland@gmail.com>

### CODE REVIEW

**Comment by vieux** [comment]
ping @moxiegirl

**Comment by moxiegirl** [comment]
@jonasrosland Thank you for making this contribution.  Our experience was that users new to Swarm were confused by coming to a "Swarm" page and learning a number of Machine commands. This, in part, why we rewrote this page. We wanted  to de-emphasize the role of `docker-machine`.

The existing content is working as we intended. We'd want to reject this PR and but not the content.  I have two suggestions:

* Make a PR with this content into Docker Machine documentation
* Create a blog post with your content and we will reference it from this page: https://docs.docker.com/swarm/provision-with-machine/

What do you think?

**Comment by jonasrosland** [comment]
Hi @moxiegirl, the reasoning I had was that I learnt these easier to remember commands when getting started with Swarm a while back, and was surprised to see the advanced commands that aren't really needed (IMHO) when looking at the new version of the docs.

Since we already have the `swarm` commands implemented in Docker Machine my thought was that should be promoted instead of demoted in favor of manual commands, to make it easier to find information in the commands themselves (such as `docker-machine create` which displays all the Swarm commands).

Looking at the linked docs it covers pretty much what I've added here, maybe the two docs "Evaluate Swarm in a sandbox" and "Provision with Machine" could be merged somehow? It looks like they are targeting similar setups, so perhaps that would be an option?

**Comment by jonasrosland** [comment]
Hi again @moxiegirl, I think I was a bit confused about the docs, since this file is explicitly named `install-w-machine.md`, and the other is `provision-with-machine.md`. Perhaps a renaming to say `swarm-sandbox.md` or something would remove the confusion (at least for me)? I'll look into the `provision-with-machine.md` docs and see if I can add any value there. I still think it's a bit confusing having both of these though.

**Comment by nishanttotla** [comment]
^ #1771 might be slightly related

**Comment by moxiegirl** [comment]
@nishanttotla @jonasrosland I see the point.  I can certainly rename this file. If you are good with that. I'll close this issue, rename the file, and redirect.  WDYT?

**Comment by jonasrosland** [comment]
@moxiegirl I think renaming the document would be a good idea. The question in #1771 still remains though, why are there two similar documents with essentially the same outcome? The Twitter request links to the blog post I wrote that contains the commands that I've added into the document here.

**Comment by moxiegirl** [comment]
@jonasrosland  `provision-with-machine.md` explains that it is possible but doesn't show how to do it step-by-step.  `install-w-machine` which we will rename to remove the `machine` assumes a local install in a Toolbox environment but uses the regular `swarm` image to provision.

**Comment by jonasrosland** [comment]
Sounds good @moxiegirl. I'll see if I can add something to the other docs then, you can close this now :)

**Comment by moxiegirl** [comment]
Thanks @jonasrosland!

**Pull request closed without merging**
