### PR TITLE
Add the support for specifying Leader Election TTL

### LINKED ISSUE #1227: Leader failover too slow, taking 40 seconds
Hi there,
   I've started two swarm managers with advertise set to their own hostnames. With consul, I could implement the leader failover successfully, but found the whole process always took 40 seconds before the new leader information was written to the KV store in consul. I guess this is becuase the default TTL for consul session is 15 seconds. Consul takes a conservative method to multiple it with a factor of two plus 10 seconds as the check interval. 
   Do you guys know how to descrease the failover interval? Sounds like no existing config parameters help. Thanks.

### PR DESCRIPTION
**Pull request by abronan**
Fixes #1227 #930 

Signed-off-by: Alexandre Beslic <abronan@docker.com>

### CODE REVIEW

**Comment by abronan** [comment]
@vieux hmm still the same failure on `images`:

```
not ok 53 docker images
# (in test file api/images.bats, line 44)
#   `[ "${#lines[@]}" -ge 4 ]' failed
```

**Comment by abronan** [comment]
@jimmyxian Sounds like there is a race with the engine `connect/disconnect` on the `etcd` integration tests, at a first glance it seems that previous tests are not cleaning their entry properly with the `TTL` expiration and we don't get the event as we are supposed.

Might be worth adding some more checks to make sure the store is empty before trying this test? WDYT?

**Comment by abronan** [comment]
@vieux @chanwit @jimmyxian Ready for review ;)

**Comment by jimmyxian** [comment]
@abronan I will check it. :)
LGTM

**Comment by chanwit** [comment]
Awesome @abronan!!

LGTM

**Comment by vieux** [comment]
LGTM

**Pull request merged**
