### PR TITLE
Add cpus mem

### PR DESCRIPTION
**Pull request by vieux**
```
$ docker info
Containers: 0
Nodes: 3
 fedora-1:X.X.X.X:4242
  └ CPUs: 1
  └ Total Memory: 1.957 GiB
 ubuntu-2: X.X.X.X:4242
  └ CPUs: 1
  └ Total Memory: 1.954 GiB
 ubuntu-1: X.X.X.X:4242
  └ CPUs: 1
  └ Total Memory: 1.954 GiB
```

### CODE REVIEW

**Comment by jhamrick** [comment]
I see this is marked as in progress -- does that mean you also plan on adding information about how many resources are being used? As far as I can tell, there currently doesn't seem to be a good way to get that information. But, it would be super useful to have for debugging purposes if a container can't be scheduled but you expect it to be able to. 

cc @minrk

**Comment by vieux** [comment]
@jhamrick good idea.

**Comment by vieux** [comment]
@jhamrick something like this:

```
Containers: 1
Nodes: 3
 ubuntu-2: X.X.X.X:4242
  └ Total CPUs: 1
  └ Reserved CPUs: 0
  └ Total Memory: 1.954 GiB
  └ Reserved Memory: 1 GiB
 fedora-1: X.X.X.X:4242
  └ Total CPUs: 1
  └ Reserved CPUs: 0
  └ Total Memory: 1.957 GiB
  └ Reserved Memory: 0 B
 ubuntu-1: X.X.X.X:4242
  └ Total CPUs: 1
  └ Reserved CPUs: 0
  └ Total Memory: 1.954 GiB
  └ Reserved Memory: 0 B
```

**Comment by vieux** [comment]
@aluzzardi what do you think about the UI ?

**Comment by vieux** [comment]
Maybe better:

```
Containers: 1
Nodes: 3
 ubuntu-1: X.X.X.X:4242
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 1.954 GiB
 fedora-1: X.X.X.X:4242
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 1.957 GiB
 ubuntu-2: X.X.X.X:4242
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 1 GiB / 1.954 GiB
```

**Comment by jhamrick** [comment]
@vieux Yeah, that second example you gave is exactly what I was thinking. Also maybe you could include how many containers are running on each node, in addition to the total number of containers?

**Comment by vieux** [comment]
@jhamrick @aluzzardi please take another look:

```
Containers: 10
Nodes: 3
 ubuntu-2: XXXX:4242 - Containers: 7
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 1.954 GiB
 ubuntu-1: XXXX:4242 - Containers: 1
  └ Reserved CPUs: 1 / 1
  └ Reserved Memory: 0 B / 1.954 GiB
 fedora-1: XXXX:4242 - Containers: 2
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 1 GiB / 1.957 GiB
```

**Comment by aluzzardi** [comment]
I'm worried that it won't be easily parsable by external calls to the API - do we care about doing that?

**Comment by vieux** [comment]
I feel like it was useful information, @jhamrick ?

I agree it looks heavy, but `docker info | grep <name> | cut -d : -f 2,3` still works :D

**Comment by jhamrick** [comment]
Looks great to me! :+1:

**Comment by bacongobbler** [comment]
this looks very useful! :+1:

**Comment by aluzzardi** [comment]
LGTM

**Pull request merged**
