### PR TITLE
fix -c calculation

### PR DESCRIPTION
**Pull request by vieux**
Signed-off-by: Victor Vieux <victorvieux@gmail.com>

### CODE REVIEW

**Comment by vieux** [comment]
THIS is far from ideal, but it's required for the RC2

**Comment by vieux** [comment]
This is a follow up of #886

**Comment by vieux** [comment]
ping @aluzzardi @abronan

**Comment by abronan** [comment]
LGTM

**Comment by aluzzardi** [comment]
LGTM

**Pull request merged**
