### PR TITLE
add amitshukla, moxiegirl and nishanttotla to the MAINTAINERS file

### PR DESCRIPTION
**Pull request by vieux**
Add @amitshukla as `curator` as he's currently helping us triaging issues
Add @moxiegirl as `docs maintainer` she should have been there already!
Add @nishanttotla as `maintainer`

ping @docker/swarm-maintainers 
ping @thaJeztah 

:tada: :balloon:

### CODE REVIEW

**Comment by dongluochen** [comment]
LGTM. :tada: :tada:

**Comment by nishanttotla** [comment]
Yay thanks @vieux 😄😄😄
LGTM.

**Comment by jimmyxian** [comment]
LGTM :tada: :tada:

**Comment by abronan** [comment]
LGTM

**Comment by chanwit** [comment]
LGTM

Congrats !!

**Comment by MHBauer** [comment]
Yay! LGTM

**Comment by thaJeztah** [comment]
LGTM :+1:

**Comment by amitshukla** [comment]
LGTM

**Comment by moxiegirl** [comment]
LGTM

**Comment by vieux** [comment]
Awesome, welcome!

**Pull request merged**
