### PR TITLE
API Cleanup

### PR DESCRIPTION
**Pull request by aluzzardi**
Some refactoring around the API to split up `api.go` (one of the biggest files of swarm) into sub components.

### CODE REVIEW

**Comment by aluzzardi** [comment]
@vieux @abronan: Thoughts? This is a proposal, feel free to reject if the split doesn't make sense.

**Comment by vieux** [comment]
LGTM

**Comment by abronan** [comment]
LGTM

**Comment by aluzzardi** [comment]
Rebased

**Pull request merged**
