### PR TITLE
Tasks to continue running after swarm crash

### PR DESCRIPTION
**Pull request by Spritekin**
By default, when a framework fails, Mesos will terminate any tasks started by a framework

The failovertimeout parameter allows the tasks to continue running for this number of seconds after the swarm manager dies. If not specified mesos will kill the tasks immediately (default behaviour). Mesos documentation recommends setting this value to 1 week time.

The frameworkid allows to specify a unique id. If Swarm manages to reconnect with the same task ID it had before the crash then mesos will reassigned the tasks to it. The ID must follow the mesos format for IDs (i.e. b2853a78-7cba-455a-99c7-d73bb5cbda95-0024). Refer to mesos for ID formats.

Signed-off-by: Guillermo Rodriguez <grodriguez@cmcrc.com>

### CODE REVIEW

**Comment by Spritekin** [comment]
Note, this is the separation of the changes proposed in the PR #2067

This PR only updates the mesos timeout and frameworkid for task resilience.

The changes to modify the Dockerfile only are now in PR #2344

**Comment by ezrasilvera** [comment]
@Spritekin Looks good. I also think the curl stuff should have a separate PR.  I suggest you close #2067

**Comment by ezrasilvera** [comment]
@Spritekin not sure the help message for the timeout is clear enough, how about: 
keep the tasks lunched by this framework, running for this number of seconds in case this Swarm manager crashes ....

what did you mean by "recover by restarting with the same framwrodk id " ?  I'm not sure we should refer to the HA/recovery flow in the help of this parameter.

**Comment by Spritekin** [comment]
@ezrasilvera 
Closed PR 2067.

Will try to rephrase. The problem is both parameters are very related. The main concept is:

Mesos identifies a framework by its ID. All tasks started by the framework are assigned to that ID. If the framework crashes the tasks keep assigned to that ID for the failover_timeout seconds (default 0 means they are stopped immediately). If you restart a framework with the same framework id before the framework_timeout elapses, then the tasks are reassigned.

Now, about HA, it doesn't work with mesos because of contradicting behaviours. 
a. when you start swarm mesos will assign it a unique ID. So if you start three swarm in HA mode, each will have its own ID. Then, when you start tasks, they will start with the leader ID. But if the leader crashes then mesos can't reassign them to the new elected leader because they have different IDs.

b. So then I tried to start three swarm with the same ID, the first one took leadership, then the other two were waiting. But when mesos sent offers, instead of being sent to the leader they are sent to the last framework connected with that ID (which happens not to be the leader) so the leader never receives offers so it is unable to launch tasks. The solution in this case would be to allow a secondary swarm to reroute offers to the leader.

In any case, my HA is to quickly detect problems in swarm using a Marathon health checks and restart quickly. That's where the curl requirements get in but then that's another story.

**Comment by Spritekin** [comment]
@ezrasilvera 
Ok, I have adjusted the help text. Please tell me if its a bit clearer.

**Comment by ezrasilvera** [comment]
@Spritekin I agree that the to get HA like capabilities (i.e., detect failure and restart a new Swarm master) you need both PRs . This doesn't mean, however, that one can't use each of this separately for whatever reason he wants to :-)  
For example, I can see why people would like to explicitly set the farmeworkID even without th erestart scenario.

**Comment by ezrasilvera** [comment]
that's why I thought that in the help we shouldn't refer to a specific use-case of the parameter but simply to what the parameter does

**Comment by Spritekin** [comment]
@ezrasilvera 
Removed specific use case text from the help strings.

**Comment by Spritekin** [comment]
@ezrasilvera 
Why are the checks failing? Doesn't seem caused by this change.

**Comment by ezrasilvera** [comment]
@Spritekin I think it's not related to your changes. You can see that other builds failed as well. I just push again from time to time to initiate the build (you can use --no-edit and --amend so no real commit is needed)

**Comment by Spritekin** [comment]
@ezrasilvera @jimenez 
What now! I don't see a problem in the documentation and it says its failing!

I like this project but I don't have time for being stopped by nonexistent errors. Please ask someone to fix the build system.

Luck!

**Comment by Spritekin** [comment]
And now I can't try to commit again because it says:
fatal: You are in the middle of a cherry-pick -- cannot amend.

Aaaaaarggggg....

**Comment by Spritekin** [comment]
Closing. Pulled an invalid ticket

**Pull request closed without merging**
