### PR TITLE
remove \b (\u0008) prefix from /info api calls

### PR DESCRIPTION
**Pull request by u2mejc**
This is related to issue https://github.com/docker/swarm/issues/1237

### CODE REVIEW

**Comment by vieux** [comment]
duplicate of https://github.com/docker/swarm/pull/1147

**Comment by u2mejc** [comment]
@vieux It seems like we're mixing data with presentation here?

This does appear to breaking the ability to programmatically parse the output (as noted in #1214). It seems like this should be modified in the cli where output presentation is formatted, would you be able point me in the right direction, I'll be happy to take a crack at fixing it.

**Comment by vieux** [comment]
@u2mejc I agree it's not good as it is right now, changing the docker cli would be better so we could remove the \b in swarm.

**Comment by nishanttotla** [comment]
Closing this PR since it needs more changes. Follow the discussion on #1625 instead.

**Comment by vieux** [comment]
This is fixed in https://github.com/docker/swarm/pull/1721 :tada:

**Comment by u2mejc** [comment]
@nishanttotla and @vieux, thank you! I'm looking forward to testing master as time allows!

**Pull request closed without merging**
