### PR TITLE
scheduler just return best node for container

### PR DESCRIPTION
**Pull request by adohe**
@dongluochen ptal.

### CODE REVIEW

**Comment by AdoHe** [comment]
Failed because of:
```
+ docker rm -vf swarm-prs-master2600
Failed to remove container (swarm-prs-master2600): Error response from daemon: No such container: swarm-prs-master2600
```

**Comment by vieux** [comment]
@AdoHe cannot compile

**Comment by AdoHe** [comment]
@vieux ptal.

**Comment by AdoHe** [comment]
@dongluochen @vieux could we get this merged into master branch? I have some other update which is based on this one, but I don't want make them into one PR. So it would be better for this PR to get merged at first.

**Comment by allencloud** [comment]
@AdoHe 
Can you rebase the code here and solve the confilct ?

**Comment by AdoHe** [comment]
@allencloud I just get time to update this, conflict resolved, ptal.

**Comment by nishanttotla** [comment]
Closing due to lack of activity. Please rebase and reopen if you wish to continue working on it.

**Pull request closed without merging**
