### PR TITLE
Add a random delay to avoid synchronized registration at swarm join. Simple fix for #1353

### PR DESCRIPTION
**Pull request by dongluochen**
Signed-off-by: Dong Chen <dongluo.chen@docker.com>

### CODE REVIEW

**Comment by MHBauer** [comment]
I feel like this change merits a warning somewhere saying that registration might not occur until after `heartbeat` amount of time. This could be surprising if the heartbeat is minutes or longer. (I do admit to not knowing what any typical heartbeat is in actual deployments.)

**Comment by dongluochen** [comment]
@MHBauer I was thinking about it in the first commit.

**Comment by vieux** [comment]
LGTM

ping @aluzzardi 

@dongluochen can you please rebase ?

**Comment by aluzzardi** [comment]
I agree with @MHBauer - this can be surprising, especially with longer HBs.

Thoughts?

**Comment by cpuguy83** [comment]
Wouldn't it be better to handle this in the manager so that it's not overwhelmed when the thundering herd comes in?

**Comment by cpuguy83** [comment]
Either way there is still a delay in registration, but at least then it's only happening during high volume instead of all the time.

**Comment by dongluochen** [comment]
@cpuguy83 `swarm join` is not controlled by swarm manager. For example, a script starting 1k nodes, or a synchronized recovery from failure would cause spikes to registry (hub or KV store).  

@aluzzardi Maybe we can take the minimum of 10s and heartbeat to avoid a long wait. The random delay would be between 0 and min(10s, heartbeat).

**Comment by cpuguy83** [comment]
@dongluochen Oh, I see.

**Comment by aluzzardi** [comment]
What if we have a different set of flags to control that, which default to `0s` (no wait)?

**Comment by dongluochen** [comment]
@aluzzardi Right that would give user control. I'll update the PR.

**Comment by vieux** [comment]
@aluzzardi pling

**Comment by aluzzardi** [comment]
Since this is a flag of `join`, maybe just `--delay`?

As in, `join --joindelay` seems like too many joins

**Comment by vieux** [comment]
LGTM

**Comment by abronan** [comment]
@dongluochen Can you update the PR to add a warning or a docs section to explain why we would need `--delay` as suggested by @MHBauer? Otherwise LGTM.

**Comment by abronan** [comment]
Tracked by #1353

**Comment by dongluochen** [comment]
Thanks @abronan. I updated docs/discovery.md.

**Comment by abronan** [comment]
LGTM

**Comment by dongluochen** [comment]
ping @docker/swarm-maintainers.

**Pull request merged**
