### PR TITLE
cleanup godeps

### PR DESCRIPTION
**Pull request by vieux**
Signed-off-by: Victor Vieux <vieux@docker.com>

### CODE REVIEW

**Comment by ahmetalpbalkan** [comment]
@vieux Hi Victor, samalba/dockerclient has one more new commit `0cba4a96`, do you mind including that as well?

**Comment by vieux** [comment]
sure

**Comment by vieux** [comment]
many issues will be fixed by https://github.com/docker/docker/pull/18839

**Comment by dongluochen** [comment]
LGTM. Thanks @vieux.

**Comment by abronan** [comment]
LGTM

**Pull request merged**
