### PR TITLE
rollback to Go 1.5.4

### PR DESCRIPTION
**Pull request by vieux**
See docker/docker#20865

### CODE REVIEW

**Comment by abronan** [comment]
LGTM

**Comment by nishanttotla** [comment]
LGTM

**Comment by nishanttotla** [comment]
@vieux test fails on master, not sure if related. First time I'm seeing this fail.
```
not ok 110 docker ps --before
# (in test file api/ps.bats, line 81)
#   `[ "${#lines[@]}" -eq  1 ]' failed
```

**Comment by vieux** [comment]
@nishanttotla not the 1st time for me, let's retry

**Pull request merged**
