### PR TITLE
Creating http client in swarm

### PR DESCRIPTION
**Pull request by nishanttotla**
This is experimental, let's see if we can make it work. Had to temporarily change vendor, but will figure out an alternative if this is successful.

Addresses #1879.

Signed-off-by: Nishant Totla <nishanttotla@gmail.com>

### CODE REVIEW

**Comment by nishanttotla** [comment]
Ping @dongluochen @vieux how do you feel about this? (test failure is unrelated -- leader election)

**Comment by nishanttotla** [comment]
Ping @dongluochen @vieux @abronan any objections to merging this?

It does modify `vendor` and that's temporary because `samalba/dockerclient` is going away, so we shouldn't really add swarm specific stuff to it and vendor.

**Comment by dongluochen** [comment]
LGTM

**Comment by vieux** [comment]
LGTM

**Pull request merged**
