### PR TITLE
Fixed image affinity examples in docs

### PR DESCRIPTION
**Pull request by mbentley**
Signed-off-by: Matt Bentley <mbentley@mbentley.net>

### CODE REVIEW

**Comment by mbentley** [comment]
fixes https://github.com/docker/swarm/issues/910

**Comment by abronan** [comment]
Thanks @mbentley! LGTM

/cc @thaJeztah @moxiegirl @SvenDowideit

**Comment by thaJeztah** [comment]
thanks! nice find :)
LGTM

**Comment by vieux** [comment]
LGTM

**Pull request merged**
