### PR TITLE
integration: Fix API races related to delay in refresh.

### PR DESCRIPTION
**Pull request by aluzzardi**
Signed-off-by: Andrea Luzzardi <aluzzardi@gmail.com>

### CODE REVIEW

**Comment by aluzzardi** [comment]
Well, well, well. This is **slow** :) Or maybe blocking. I don't know.

Don't merge yet

**Comment by aluzzardi** [comment]
Works now. Although our tests take slightly longer :(

**Comment by aluzzardi** [comment]
@vieux @abronan Could you take a look at this? It fixes most integration failures

**Comment by abronan** [comment]
LGTM

/cc @vieux

**Comment by vieux** [comment]
LGTM

**Pull request merged**
