### PR TITLE
docs: Typo in scheduler/filter.md

### PR DESCRIPTION
**Pull request by MiLk**
Small typo I found while reading the documentation.

### CODE REVIEW

**Comment by abronan** [comment]
Thank you @MiLk

/cc @thaJeztah Just to bring this to docs maintainer attention, seems like there is an issue with docs CI env.

`FATAL: 2016/01/08 mkdir /docs/public/opensource/kitematic/images/: no such file or directory`

Is it necessary to fail the docs tests if related to another project? I'm unfamiliar with the docs CI so just wondering :smile:

**Comment by thaJeztah** [comment]
@abronan yeah, there's something funky causing Hugo to sometimes fail, see https://github.com/spf13/hugo/issues/1754

Reason if checks the other docs, is that the test needs all docs, to (e.g.) checks for duplicate menu-id's  (which can result in docs not being visible, or Hugo not generating the docs).

If you have an account for Jenkins, you can manually restart the test (I don't have an account currently, but I think Jess can provide one).

In this case, I think it's okay to ignore the failing docs-build, because no links were added, or pages renamed/menu-items added so LGTM

feel free to merge if you're okay with that! :+1:

**Comment by abronan** [comment]
@thaJeztah thanks for the clarification!

**Comment by MHBauer** [comment]
Good catch. Thanks @MiLk!

**Pull request merged**
