### PR TITLE
Fix issue where conn is stuck waiting for stdin

### LINKED ISSUE #1284: attach seems to hang
The following hangs when my DOCKER_HOST points to a Swarm master, but works just fine when DOCKER_HOST points to a Docker Engine.
```bash
docker run --rm -it busybox
/ # exit
```

I tested this by installing docker and docker-machine from Homebrew on OSX, and using docker-machine to build a 1-VM Swarm cluster, where my manual test fails, as well as a standalone engine VM, where my test passes.

Swarm `docker version`

```
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.5.1
 Git commit:   0a8c2e3
 Built:        Sun Sep 13 01:00:38 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      swarm/0.4.0
 API version:  1.16
 Go version:   go1.4.2
 Git commit:   d647d82
 Built:
 OS/Arch:      linux/amd64
```

Swarm `docker info`

```
Containers: 2
Images: 4
Role: primary
Strategy: spread
Filters: affinity, health, constraint, port, dependency
Nodes: 1
 swarm-master: 192.168.99.103:2376
  └ Containers: 2
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 1.022 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=4.0.9-boot2docker, operatingsystem=Boot2Docker 1.8.2 (TCL 6.4); master : aba6192 - Thu Sep 10 20:58:17 UTC 2015, provider=virtualbox, storagedriver=aufs
CPUs: 1
Total Memory: 1.022 GiB
Name: 006fc711cf9f
```

Docker engine `docker version`.

```
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.5.1
 Git commit:   0a8c2e3
 Built:        Sun Sep 13 01:00:38 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:10:10 UTC 2015
 OS/Arch:      linux/amd64
```

Docker engine `docker info`

```
Containers: 0
Images: 50
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 50
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.0.9-boot2docker
Operating System: Boot2Docker 1.8.2 (TCL 6.4); master : aba6192 - Thu Sep 10 20:58:17 UTC 2015
CPUs: 1
Total Memory: 996.2 MiB
Name: dev
ID: FEMP:H5QZ:MHUU:UF6Q:TYIF:7WUW:XOUN:MQVS:HQ7E:TTLV:VLP7:LL6D
Debug mode (server): true
File Descriptors: 11
Goroutines: 18
System Time: 2015-10-13T03:40:58.261859256Z
EventsListeners: 0
Init SHA1:
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox
```

### LINKED ISSUE #1297: `run -i` requires hitting input to exit
When doing `docker run -i` against swarm, when the container exits, it is required to hit enter 2 times to get back to a prompt.
This is true with a  shell in the container `docker run -it busybox` (then type exit), or even just `docker run -i busybox false`.
It always requires hitting enter 2 times to fully exit.

### info
```
Containers: 5
Images: 5
Engine Version:
Role: primary
Strategy: spread
Filters: affinity, health, constraint, port, dependency
Nodes: 3
 swarm-demo-1: 192.168.99.148:2376
  └ Containers: 2
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 1.021 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=4.1.10-boot2docker, operatingsystem=Boot2Docker 1.9.0-rc1 (TCL 6.4); master : 4187d2c - Wed Oct 14 14:00:28 UTC 2015, provider=virtualbox, storagedriver=aufs
 swarm-demo-2: 192.168.99.147:2376
  └ Containers: 1
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 1.021 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=4.1.10-boot2docker, operatingsystem=Boot2Docker 1.9.0-rc1 (TCL 6.4); master : 4187d2c - Wed Oct 14 14:00:28 UTC 2015, provider=virtualbox, storagedriver=aufs
 swarm-demo-3: 192.168.99.149:2376
  └ Containers: 2
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 1.021 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=4.1.10-boot2docker, operatingsystem=Boot2Docker 1.9.0-rc1 (TCL 6.4); master : 4187d2c - Wed Oct 14 14:00:28 UTC 2015, provider=virtualbox, storagedriver=aufs
CPUs: 3
Total Memory: 3.064 GiB
Name: dd4b830fedda
```

### version
```
Client:
 Version:      1.9.0-rc1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   9291a0e
 Built:        Wed Oct 14 03:29:07 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      swarm/1.0.0
 API version:  1.16
 Go version:   go1.5.1
 Git commit:   fe88189
 Built:
 OS/Arch:      linux/amd64
```

### PR DESCRIPTION
**Pull request by cpuguy83**
This was hard to repro, but found out it seems to only happen with TLS
connections.
When `docker run -i` was set, the client gets stuck waiting for sdin on
exit, and requires hitting return twice.

This fix ensures that:
1. When stdin is done, wait for stdout always
2. When stdout is done, close the stream and wait for stdin to finish

On 2, stdin copy should return immediately now since the out stream is closed.
Note that we probably don't actually even need to wait here.

I'm not sure how we can do up a test for this since it only seems to be for tls connections

Fixes #1284
Fixes #1297

### CODE REVIEW

**Comment by chanwit** [comment]
LGTM

**Comment by chanwit** [comment]
ping @pwnall 
Could you please confirm this fix since a few of us can reproduce this.

**Comment by pwnall** [comment]
@chanwit Will try to have a verdict out in a couple of hours. I've been used pre-baked Docker images, it might take me a bit of time to get my own build set up.

@cpuguy83 @chanwit Thank you so much for putting this together!

**Comment by chanwit** [comment]
I'd love this to get merged into 1.0 as the bug bites me too.
Is that OK @docker/swarm-maintainers ?

**Comment by pwnall** [comment]
@cpuguy83 @chanwit Just finished verifying the fix. It works for me. Thank you very much!!

I would also be grateful to see this make it to a release!

As you might have imagined, my bug report is a reduction. I actually hit this bug using the `/attach` API in a piece of code I'm using. I put together a workaround (turns out `/logs` was enough for me), but I would prefer to use the `/attach` code and an official Swarm release.

**Comment by aluzzardi** [comment]
Awesome! Will get this merged for 1.0.

Thanks @pwnall for reproducing!

**Comment by aluzzardi** [comment]
Thanks @cpuguy83, that was hardcore to spot.

> 1. When stdin is done, wait for stdout always
> 2. When stdout is done, close the stream and wait for stdin to finish
>
> On 2, stdin copy should return immediately now since the out stream is closed.
Note that we probably don't actually even need to wait here.

Do you mind adding that or something similar as a comment in the code?

**Comment by cpuguy83** [comment]
@aluzzardi done

**Comment by vieux** [comment]
LGTM

**Comment by yoshiokatsuneo** [comment]
Related issue that this commit does not fix:
https://github.com/docker/swarm/issues/1430

**Pull request merged**
