### PR TITLE
fix network inspect via name for global scope

### LINKED ISSUE #1345: 1.0.0-rc2: docker network inspect returns error
Just trying out Swarm RC2 and hit this issue
```
$ docker info
Containers: 4
Images: 4
Role: primary
Strategy: spread
Filters: health, port, dependency, affinity, constraint
Nodes: 2
 swl-demo0: 192.168.99.112:2376
  └ Containers: 3
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 1.021 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=4.1.11-boot2docker, operatingsystem=Boot2Docker 1.9.0-rc2 (TCL 6.4); master : 8df9af7 - Fri Oct 23 17:18:18 UTC 2015, provider=virtualbox, storagedriver=aufs
 swl-demo1: 192.168.99.113:2376
  └ Containers: 1
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 1.021 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=4.1.11-boot2docker, operatingsystem=Boot2Docker 1.9.0-rc2 (TCL 6.4); master : 8df9af7 - Fri Oct 23 17:18:18 UTC 2015, provider=virtualbox, storagedriver=aufs
CPUs: 2
Total Memory: 2.043 GiB
Name: f2b826418c44

$ docker network ls
NETWORK ID          NAME                        DRIVER
6160c2497c3b        myapp                       overlay
0beacabcfead        swl-demo0/bridge            bridge
1e2a852eecba        swl-demo0/none              null
7fe6bd73e5b8        swl-demo0/docker_gwbridge   bridge
7cdc33d1f602        swl-demo1/bridge            bridge
cc937031f486        swl-demo1/none              null
1a4eb4171462        swl-demo1/host              host
c98656aacf24        swl-demo1/docker_gwbridge   bridge
57fccd19ca8a        swl-demo0/host              host

$ docker network inspect myapp
Error response from daemon: No such network: myappnull
```

### PR DESCRIPTION
**Pull request by vieux**
fix #1345

### CODE REVIEW

**Comment by vieux** [comment]
ping @aluzzardi @dave-tucker

**Comment by aluzzardi** [comment]
LGTM

**Comment by abronan** [comment]
LGTM

**Comment by jimmyxian** [comment]
LGTM

**Pull request merged**
