### PR TITLE
Clairify port usage in multi-manager-setup.md

### PR DESCRIPTION
**Pull request by dreilly1982**
Clarified port usages in the assumptions section of multi-manager-setup.md.  This is to address issue #996

### CODE REVIEW

**Comment by aanm** [comment]
@dreilly1982 I think there should also be a clarification on the agent's IP addresses. It's confusing for new guys to understand that there's:
 * A swarm agent running on a different IP than managers
 * A docker daemon running on the same IP of managers

**Comment by abronan** [comment]
@aanm Agreed.

@dreilly1982 Sorry for the delay on stumbling upon this, are you up to making this change? Otherwise LGTM and we can merge it as it is and make the clarification in another PR.

/ping @moxiegirl

**Comment by abronan** [comment]
This one PR is long standing... let's merge it as it is just a clarification. We can discuss on improving the whole Multi-Manager doc later on.

**Comment by moxiegirl** [comment]
@abronan apologies for letting this linger.

**Comment by abronan** [comment]
@moxiegirl no worries :smiley_cat:

**Pull request merged**
