### PR TITLE
integration tests: run with native/vfs by default.

### PR DESCRIPTION
**Pull request by aluzzardi**
Signed-off-by: Andrea Luzzardi <aluzzardi@gmail.com>

### CODE REVIEW

**Comment by aluzzardi** [comment]
Using `vfs` the tests don't slow down by much and the environment is more reproducible on every host.

```
STORAGE_DRIVER=aufs bats test/integration/constraints.bats  3.75s user 1.17s system 13% cpu 37.104 total
STORAGE_DRIVER=vfs bats test/integration/constraints.bats  4.05s user 1.39s system 13% cpu 40.089 total
```

**Comment by aluzzardi** [comment]
Also, it's not supported to run the aufs driver on top of the aufs driver:
https://github.com/docker/docker/blob/master/daemon/graphdriver/aufs/aufs.go#L48

Meaning that we cannot chain aufs docker-in-docker's.

@jfrazelle @vieux @abronan Any better option than `vfs` to run docker in docker?

**Comment by vieux** [comment]
image affinity seems to fail with this PR and on an unrelated note, docker cp is stuck on both master and this PR

**Comment by aluzzardi** [comment]
With #703 and #702 it actually works, I believe.

**Comment by abronan** [comment]
Tests blocking at `cp` for me, will test with the other PRs ;-)

**Comment by abronan** [comment]
Like @vieux, tests are failing on **affinity** after merging changes in #703

**Comment by aluzzardi** [comment]
Try:

```
DRIVER=vfs DOCKER_IMAGE=dockerswarm/dind DOCKER_VERSION=1.6.0 bats [...]
```

**Comment by abronan** [comment]
@aluzzardi Indeed, it passes now :+1:

**Comment by abronan** [comment]
@aluzzardi Wait still having random errors on affinity if I re-run the tests..

On `[[ "${output}" == *'"Name": "node-0"'* ]]`

**Comment by abronan** [comment]
I had the tests passing the first time and now it fails systematically on `image affinity`.

**Pull request merged**
