### PR TITLE
Migration from pkg/store to docker/libkv

### PR DESCRIPTION
**Pull request by abronan**
This PR removes `pkg/store` and uses `docker/libkv` instead.

Only the last commit is relevant to see the changes.

Depends on docker/libkv#4

### CODE REVIEW

**Comment by abronan** [comment]
*Godep* changed:

```
"GoVersion": "go1.3.3",
	"Packages": [		
		"./..."		
	],
```

to

```
"GoVersion": "go1.4.1",
```

after a `godep save`, I expected the bump in Go version as I'm using a different one but not sure how the lack of `Packages` section impact things for `godep`?

Also this would be nice to remove `pkg/store` from the commit history here in swarm as we successfully extracted the commit history in `docker/libkv`. Thoughts?

ping @aluzzardi

**Comment by chanwit** [comment]
@abronan just do `godep save ./...` instead of `godep save`

**Comment by abronan** [comment]
@chanwit Indeed, the usual :smile: thanks! Also switched back to `go1.3.3` for the `godep save`.

**Comment by abronan** [comment]
ping @vieux @aluzzardi

**Comment by vieux** [comment]
LGTM

**Comment by aluzzardi** [comment]
What's the status of this?

**Comment by abronan** [comment]
@aluzzardi ready to merge but rebased first to see if nothing breaks with latest changes (at least on the discovery/storage part)

**Comment by abronan** [comment]
ping @aluzzardi @vieux (tests are ok for the discovery/storage part)

**Comment by thaJeztah** [comment]
Nice! thanks @abronan!

**Pull request merged**
