### PR TITLE
remove empty vendor in stretchr testify

### LINKED ISSUE #2142: can not build binary of swarm after vendor dependencies
Hi All,

I found that docker swarm has already move Godeps into vendor.
However when I followed the instructions in CONTRIBUTING.md to build binary of swarm, error happened. And the output is like below:

```
root@ubuntu:~/gocode/src/github.com/docker/swarm# git checkout remotes/origin/master
Previous HEAD position was 4df5b52... show container status of each node in docker info
HEAD is now at 78bacff... Merge pull request #2131 from jimmycmh/master
root@ubuntu:~/gocode/src/github.com/docker/swarm# go install .
vendor/github.com/stretchr/testify/mock/mock.go:12:2: no buildable Go source files in /root/gocode/src/github.com/docker/swarm/vendor/github.com/stretchr/testify/vendor/github.com/stretchr/objx
```
Anybody can reproduce this?
Something wrong in the vendor folder?

```
/root/gocode/src/github.com/docker/swarm/vendor/github.com/stretchr/testify/vendor/github.com/stretchr/objx
```

there is a vendor in `/root/gocode/src/github.com/docker/swarm/vendor/github.com/stretchr/testify` and the objx has nothing in it.

### PR DESCRIPTION
**Pull request by allencloud**
remove empty vendor in stretchr testify

With the empty vendor in `/root/gocode/src/github.com/docker/swarm/vendor/github.com/stretchr/testify`, error will occur when building the binary of swarm.

Fixed #2142 

Signed-off-by: Sun Hongliang <allen.sun@daocloud.io>

### CODE REVIEW

**Comment by alexellis** [comment]
I am getting the same error.

**Comment by allencloud** [comment]
@alexellis 
You can do fix by following this pr.

**Comment by allencloud** [comment]
Has anybody tested this? Now I cannot build a Swarm binary via the source code.
I think this makes me a little bit suffering when hacking Swarm.
@nishanttotla @dongluochen @vieux

**Comment by nishanttotla** [comment]
@allencloud you mean you can't build from source on the branch in this PR? Or do you mean master?

**Comment by allencloud** [comment]
@nishanttotla 
No, I cannot build from source code. I describe the issue in #2142.
However, I tried `docker build ` from Dockerfile, and swarm image can be built seccessfully.

here is the error message from `go install .`:
```
root@10-11-1-156:~/gocode/src/github.com/docker/swarm# go install .
vendor/github.com/stretchr/testify/mock/mock.go:12:2: no buildable Go source files in /root/gocode/src/github.com/docker/swarm/vendor/github.com/stretchr/testify/vendor/github.com/stretchr/objx
```

**Comment by vieux** [comment]
LGTM

**Comment by abronan** [comment]
LGTM

**Pull request merged**
