### PR TITLE
increate timeout in 'leader election - rescheduling' test

### PR DESCRIPTION
**Pull request by vieux**
Signed-off-by: Victor Vieux <vieux@docker.com>

### CODE REVIEW

**Comment by vieux** [comment]
@dongluochen test on master unrelated (bug in runc) and test on 1.9 unrelated (will be fixed by https://github.com/docker/swarm/pull/2050)

**Comment by vieux** [comment]
ping @abronan

**Comment by dongluochen** [comment]
LGTM

**Comment by abronan** [comment]
LGTM

**Pull request merged**
