### PR TITLE
set MemorySwappiness default value

### PR DESCRIPTION
**Pull request by jimmyxian**
Fix this issue: https://github.com/docker/swarm/issues/1411
Signed-off-by: Xian Chaobo <xianchaobo@huawei.com>

### CODE REVIEW

**Comment by jimmyxian** [comment]
ping @fsfshijm @AzenYao 
Can you try this and see if it works. Thanks

**Comment by fsfshijm** [comment]
@jimmyxian, Seems it works well!
```
-sh-4.2$ ps -ef | grep swarm
jmshi     9427     1  0 03:36 ?        00:00:00 swarm join --addr=192.168.0.233:2375 etcd://192.168.0.141:4001
jmshi     9439     1  0 03:36 ?        00:00:00 swarm join --addr=192.168.0.17:2375 etcd://192.168.0.141:4001
jmshi     9450     1  0 03:36 ?        00:00:02 swarm manage -H 0.0.0.0:2380 etcd://192.168.0.141:4001
jmshi    10466  9473  0 04:23 pts/0    00:00:00 grep --color=auto swarm
-sh-4.2$ export | grep DOCKER_HOST
export DOCKER_HOST="tcp://0.0.0.0:2380"
-sh-4.2$ swarm -v
swarm version 1.0.0 (HEAD)
-sh-4.2$ docker-compose up -d
Creating web
Creating mongo
-sh-4.2$ docker ps
CONTAINER ID        IMAGE                         COMMAND                  CREATED             STATUS              PORTS                          NAMES
678b77255062        mongo                         "/entrypoint.sh mongo"   3 seconds ago       Up 3 seconds        27017/tcp                      EP003/mongo
88d14f3e4264        bfirsh/compose-mongodb-demo   "/bin/sh -c 'python a"   6 seconds ago       Up 3 seconds        192.168.0.233:1234->5000/tcp   PEKdev233.dev.fwmrm.net/web
-sh-4.2$
```

Thanks very much!

**Comment by jimmyxian** [comment]
ping @docker/swarm-maintainers

**Comment by abronan** [comment]
LGTM

**Comment by abronan** [comment]
ping @vieux

**Comment by vieux** [comment]
@jimmyxian shouldn't this be fixed in compose ?

**Comment by jimmyxian** [comment]
@vieux I think should fix in both compose \ docker \ swarm.
If send `create` json request without `MemorySwappiness` to docker / swarm, we should set this -1 in docker / swarm.
In compose, maybe also need to set this -1.

**Comment by johnjelinek** [comment]
when will this get merged?

**Comment by jimmyxian** [comment]
@johnjelinek Can you try this and see if it work. Thanks.

**Comment by johnjelinek** [comment]
@jimmyxian: I don't think I can test this until there's a container for it. I'm not set up to build golang apps yet in my cluster.

**Comment by johnjelinek** [comment]
I must've done something wrong. I did a `$GOPATH/bin/godep go install .` to build a new swarm bin (this is after I checked out this branch). Then I stopped all my `swarm-agent` containers and manually ran swarm in all my cluster servers. When I do `docker version`, it says swarm is pointing to this commit hash: https://github.com/jimmyxian/swarm/commit/087e245. I still get the same error message about swappiness. Any ideas how I can build just your branch right?

**Comment by johnjelinek** [comment]
@jimmyxian: I also tried merging your branch into master in my local repo of swarm:master. Same problem. What should I do to ensure that it's tracking an updated commit hash?

**Comment by abronan** [comment]
@johnjelinek Did you restart your Swarm Manager too with the new Image/binary including the commit? From your comment I read that you tried only with Swarm Agents. You mostly need to restart the Swarm Manager. So restarting it (hopefully) should do the trick :)

**Comment by johnjelinek** [comment]
Hrmm ... I'll give that a shot. I have the swarm manager running in HA mode with consul. Not sure if that makes a difference.



—

**Comment by johnjelinek** [comment]
@abronan: that was it :) all fixed now. :shipit:

**Comment by abronan** [comment]
@johnjelinek Woop! Thanks a lot for testing and confirming :)

Let's include the fix asap. PTAL @docker/swarm-maintainers

**Comment by jimmyxian** [comment]
@johnjelinek Thanks for testing. :)

**Comment by johnjelinek** [comment]
@jimmyxian / @abronan: do you have an ETA on when this might get merged/published? I feel nervous running all these processes outside of docker containers.

**Comment by aluzzardi** [comment]
LGTM

**Comment by aluzzardi** [comment]
@johnjelinek Hey, you can run the `master` swarm image by doing a docker run of `dockerswarm/swarm:master` instead of `swarm`.

This will be published in 1.0.1 sometime next week.

**Comment by johnjelinek** [comment]
@aluzzardi: sweet, thanks!

**Comment by thaJeztah** [comment]
If I understand correctly, this fixes https://github.com/docker/docker/issues/17879 ?

**Comment by johnjelinek** [comment]
Yes, that's correct.

**Pull request merged**
