### PR TITLE
cluster:use AuthConfig when Engine Pull Image

### PR DESCRIPTION
**Pull request by fugr**
origin code missing using authConfig for pull image,this maybe a mistake when docker need the authConfig.

### CODE REVIEW

**Comment by fugr** [comment]
have I followed the rules?

**Comment by fugr** [comment]
@GordonTheTurtle squash all commits into one commit,done!

**Comment by nishanttotla** [comment]
This might be related to #2217. I'm looking at what the API expects in this case.

Ping @vieux @dongluochen

**Comment by dongluochen** [comment]
LGTM.

**Comment by nishanttotla** [comment]
Let's hold this off until #2272 is done, since some API behavior has changed.

**Comment by nishanttotla** [comment]
Sorry @fugr, I'll have to close this since it is no longer an issue. Thank you very much for this PR, and we look forward to further contributions.

**Pull request closed without merging**
