### PR TITLE
Leader election

### PR DESCRIPTION
**Pull request by aluzzardi**
This is an experimental feature. It's clearly lacking tests (I'll add them next week) but wanted to get it merged anyway and add tests later. If you don't use `--leader-election`, swarm will behave exactly like before so it's pretty safe.

Here's how you can try it out

Start two managers:

```
$ swarm manage -H :4000 --leader-election --addr 127.0.0.1:4000 consul://localhost:8500/addr
INFO[0000] Cluster leadership acquired
INFO[0000] New leader elected: 127.0.0.1:4000
```

```
$ swarm manage -H :4001 --leader-election --addr 127.0.0.1:4001 consul://localhost:8500/addr
INFO[0000] Cluster leadership lost
INFO[0000] New leader elected: 127.0.0.1:4000
```

The first manager is elected leader and the second one is a follower. You can send commands to either server - the follower will proxy everything to the leader automatically.

Now if you stop the leader and wait a little bit, the follower will be promoted to leader:
```
INFO[0064] Cluster leadership acquired
INFO[0064] New leader elected: 127.0.0.1:4001
```

If you start the previous leader again, it will boot as a follower.

### CODE REVIEW

**Comment by aluzzardi** [comment]
ping @abronan @vieux

**Comment by aluzzardi** [comment]
Fixes #835

**Comment by jimmyxian** [comment]
:+1: I will try to use it.

**Comment by aluzzardi** [comment]
@jimmyxian Awesome! It's still very experimental.

**Comment by janeczku** [comment]
this is big. can't wait to try it out :+1:

**Comment by abronan** [comment]
My Vagrantfile was ready for this :+1: 

Setuping everything and I'll test it, but what's up with those tests failing with Zookeeper? I know it's certainly unrelated to this PR but.. *!rebuild*?

**Comment by abronan** [comment]
@aluzzardi Works great with Consul, Etcd and Zookeeper :+1: 

Played with this by killing the Leader, followers, doing some Node Removal at the same time.

Is there a way to improve the responsiveness over a Manager failure though? For example, I was expecting this but when I killed the Leader I immediately pointed the `DOCKER_HOST` to be another Manager and issued `docker run` commands to see what would happen and I got:

```
INFO[0000] Listening for HTTP                            addr=:4000 proto=tcp
INFO[0000] Cluster leadership lost
INFO[0000] New leader elected: 192.168.42.200:4000
INFO[0000] Registered Engine swarm-agent-1 at 192.168.42.101:2375
INFO[0000] Registered Engine swarm-agent-2 at 192.168.42.102:2375
INFO[0000] Registered Engine swarm-agent-0 at 192.168.42.100:2375
ERRO[0112] HTTP error: dial tcp 192.168.42.200:4000: connection refused  status=500
ERRO[0112] HTTP error: dial tcp 192.168.42.200:4000: connection refused  status=500
ERRO[0113] HTTP error: dial tcp 192.168.42.200:4000: connection refused  status=500
ERRO[0113] HTTP error: dial tcp 192.168.42.200:4000: connection refused  status=500
ERRO[0120] HTTP error: dial tcp 192.168.42.200:4000: connection refused  status=500
ERRO[0120] HTTP error: dial tcp 192.168.42.200:4000: connection refused  status=500
INFO[0138] New leader elected: 192.168.42.201:4000
```

Cannot we enforce a new turn of Leader election when we have a connection refused error? Like force delete the entry in that case and get around the TTL expiration? (I'm aware that this is not possible in every store backend because of the lock being hold but with Etcd we can allow this for example)

**Comment by abronan** [comment]
Other than that LGTM :+1:

**Comment by abronan** [comment]
ping @vieux

**Comment by aluzzardi** [comment]
@abronan Clearly this is lacking a few features:

- Configurable TTL (so you can decide how long until the leader is considered dead)
- Auto-resign: So that when a leader is cleanly killed (Ctrl-C), it resigns before exiting 
- Tests
- Docs

I'm planning to add these next week or so, after this gets merged.

Also, not happy with the code structure. The actual code that does leader election lives in "leadership" (merged last week). However there's a bunch of logic in this PR in cli/. I'd like to create a "manager" package and put all that stuff in there.

Probably the thing I'm most unsure about is naming:

- leader follower va master slave
- --leader-election: I'm not sold on the flag name
- --addr, again. Should it be --node-addr, --leader-addr, something else ?

**Comment by abronan** [comment]
@aluzzardi what about `--join` to mean that we are joining a multi-clustered Manager setup?

**Comment by vieux** [comment]
LGTM

**Comment by abronan** [comment]
@aluzzardi Nevermind `--join` would be appealing only if we weren't using `swarm join <...>` already.

Throwing a few ideas here:
- `--lead`
- `--advertise`

**Pull request merged**
