### PR TITLE
Update RELEASE-CHECKLIST.md

### PR DESCRIPTION
**Pull request by dongluochen**
Signed-off-by: Dong Chen <dongluo.chen@docker.com>

### CODE REVIEW

**Comment by nishanttotla** [comment]
LGTM

**Comment by vieux** [comment]
LGTM

**Comment by nishanttotla** [comment]
It's unrelated, but some tests are newly failing.
```
not ok 123 docker run with image digest
# (from function `docker' in file api/../helpers.bash, line 42,
#  from function `docker_swarm' in file api/../helpers.bash, line 53,
#  in test file api/run.bats, line 33)
#   `docker_swarm pull 
```
and
```
not ok 108 docker pull with image digest
# (from function `docker' in file api/../helpers.bash, line 42,
#  from function `docker_swarm' in file api/../helpers.bash, line 53,
#  in test file api/pull.bats, line 48)
#   `docker_swarm pull 
```

**Comment by dongluochen** [comment]
Pull failures are related to docker.io availability.
```
# node-0: Pulling jimmyxian/busybox@sha256:649374debd26307573564fcf9748d39db33ef61fbf88ee84c3af10fd7e08765d... : Get https://registry-1.docker.io/v2/jimmyxian/busybox/manifests/sha256:649374debd26307573564fcf9748d39db33ef61fbf88ee84c3af10fd7e08765d: Get https://auth.docker.io/token?scope=repository%3Ajimmyxian%2Fbusybox%3Apull&service=registry.docker.io: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
# 
```

**Comment by nishanttotla** [comment]
:+1:

**Pull request merged**
