### PR TITLE
Adding additional notes for installing Go via Homebrew on Mac OS X

### PR DESCRIPTION
**Pull request by gegere**
Signed-off-by: Jason Gegere <jason@hgmail.com>

### CODE REVIEW

**Comment by abronan** [comment]
Thanks! :+1: If you ever forget to sign again, you can just amend your commit using `git commit --amend -s --no-edit` and force push to your branch. This saves you the hassle of closing and re-opening the PR :)

**Comment by vieux** [comment]
The line right after you changes sets `GOPATH=~/gocode` it feels like the 2 docs are conflicting, no ?

**Comment by gegere** [comment]
@vieux I have restructured the content based on your response. Does this look better?

**Comment by abronan** [comment]
LGTM

ping @SvenDowideit

**Comment by SvenDowideit** [comment]
LGTM - the one line should really be wrapped at 80 chars, @gegere

**Comment by vieux** [comment]
@gegere can you please fix  the 80 chars ?

**Comment by gegere** [comment]
@vieux sorry for my delay. Hopefully this is good.

**Pull request merged**
