### PR TITLE
Fix images affinity for local registry and digest

### PR DESCRIPTION
**Pull request by yanchanghai**
To fix issue [1676](https://github.com/docker/swarm/issues/1676). 
Use function parseRepositoryTag to support.

### CODE REVIEW

**Comment by vieux** [comment]
@yanchanghai can you please add an integration test ?
also parseRepositoryAndTag is already in cluster/images.go it would be nice to have the function only in one place

**Comment by yanchanghai** [comment]
Sure. Will update.

**Comment by chanwit** [comment]
> Signed-off-by: 易嘉 <changhai.ych@alibaba-inc.com>
@yanchanghai Is it possible for you to also re-sign your name in plain ASCII?

**Comment by vieux** [comment]
Thanks @yanchanghai we want to include this in our next RC, so I went away and carried your PR to merge it faster.

See https://github.com/docker/swarm/pull/1715

**Comment by navinSing** [comment]
hi,

have we checked registry on swarm with compose..

**Pull request closed without merging**
