### PR TITLE
Updated Readme.md to include git client

### PR DESCRIPTION
**Pull request by Ranjandas**
`go get ` command requires git client to be present in the system to work, so added the instruction to get git installed with golang package.

### CODE REVIEW

**Comment by vieux** [comment]
@Ranjandas can you please sign your commit ?

Thanks.

**Comment by Ranjandas** [comment]
@vieux not sure how to do this. i signedoff in my local repo ,but pushing to remote doesn't seem to show the signed-of commit. :(

**Comment by chanwit** [comment]
@Ranjandas squash them and push with force would do. your merge commit (the second one) prevents this.

**Comment by vieux** [comment]
I merged manually https://github.com/docker/swarm/commit/abf5d40aebd35caa4fc746dbf720be4f3425f8e4

**Pull request closed without merging**
