### PR TITLE
remove engine details in POST /volumes/create API

### LINKED ISSUE #2260: [Incompatible API] Swarm adds engine details in `POST /volumes/create` API which is useless
Hi, All,

I found when I call `127.0.0.1:2375/volumes/create` against Swarm with request BODY
```
{"Name":"assdasa","Driver":"local"}
```

It returns the response like below:
```
{
  "Name": "assdasa",
  "Driver": "local",
  "Mountpoint": "/var/lib/docker/volumes/assdasa/_data",
  "Labels": null,
  "Engine": {
    "ID": "HRBI:EV6M:3NAC:CXZ3:BDS7:UOKL:PD6Y:ZCK4:V3PF:V7MR:CU2Y:3LGG",
    "IP": "192.168.0.4",
    "Addr": "192.168.0.4:2376",
    "Name": "ubuntu",
    "Cpus": 1,
    "Memory": 2098442240,
    "Labels": {
      "executiondriver": "",
      "kernelversion": "3.19.0-25-generic",
      "operatingsystem": "Ubuntu 14.04.3 LTS",
      "storagedriver": "aufs"
    },
    "Version": "1.11.1"
  }
}
```

I am afraid Swarm returned extra **ENGINE details** in the response which is not reasonable.
It is **not compatible** with docker engine's API.

And the reason is that in Swarm's Volume struct, it has two fields:
```
type Volume struct {
	types.Volume
	Engine *Engine
}
```

Swarm returns the above struct instead of only `types.Volume`.

### PR DESCRIPTION
**Pull request by allencloud**
This PR did:
remove engine details in POST /volumes/create API

Fixed #2260 

Signed-off-by: allencloud <allen.sun@daocloud.io>

### CODE REVIEW

**Comment by abronan** [comment]
LGTM

**Comment by allencloud** [comment]
ping @dongluochen @vieux @nishanttotla

**Comment by allencloud** [comment]
PTAL @vieux @dongluochen @nishanttotla 
I think it is a Bug currently Swarm has. We had better improve the API part.

**Comment by dongluochen** [comment]
LGTM

**Pull request merged**
