### PR TITLE
integration: wait for zookeeper to start

### PR DESCRIPTION
**Pull request by chanwit**
A small fix to the ZooKeeper integration test. It waits until the server started before proceed to the next steps.

Signed-off-by: Chanwit Kaewkasi <chanwit@gmail.com>

### CODE REVIEW

**Comment by chanwit** [comment]
cc @aluzzardi @snrism @vieux @abronan

**Comment by abronan** [comment]
Jenkins can finally go to the zoo :dancers: :tiger2: :bird: :horse: 

LGTM

**Comment by aluzzardi** [comment]
#742

**Comment by aluzzardi** [comment]
It failed again :/

**Comment by abronan** [comment]
:sob:

**Comment by snrism** [comment]
@chanwit one point that @aluzzardi mentioned in consul test holds good here as well.. i.e. to remove the starting `run` in `start_zk` and `stop_zk` and also remove the `[ "$status" -eq 0 ]`.

**Comment by aluzzardi** [comment]
Although this is helping.

Here's the logs with some interpretation.

* Joins were attempted
```
   Swarm join #0: 127.0.0.1:5050 zk://127.0.0.1:7530/test
   Swarm join #1: 127.0.0.1:5051 zk://127.0.0.1:7530/test
```

* Something is going on with Zk. Port `7530` tells us it's a zookeeper (range 7000).
```
   2015/05/09 02:14:58 read tcp 127.0.0.1:7530: i/o timeout
   time="2015-05-09T02:14:58Z" level=fatal msg="zk: connection closed" 
   2015/05/09 02:14:58 read tcp 127.0.0.1:7530: i/o timeout
   time="2015-05-09T02:14:58Z" level=fatal msg="zk: connection closed" 
```

* `check_discovery_nodes` failing means that the problem is entirely on the discovery side, as in, swarm manager was not yet involved
```
   Command "check_discovery_nodes zk://127.0.0.1:7530/test" failed 10 times. Output: 0 out of 2 hosts joined discovery
```

* And this is probably the most interesting part. `kill` failing. this is the kill in `swarm_join_cleanup`. This tells us that `swarm join` crashed (or exited).
```
   kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
   /go/src/github.com/docker/swarm/test/integration/./helpers.bash: line 150: kill: (16551) - No such process
   /go/src/github.com/docker/swarm/test/integration/./helpers.bash: line 150: kill: (16578) - No such process
```

**Comment by aluzzardi** [comment]
@chanwit I think I found the issue, it's in our side of the code, not on your tests. More details on Monday!

**Comment by snrism** [comment]
Interested to see the issue in the code side..also, if no one has started, I can pickup the `etcd` test case next.

**Comment by aluzzardi** [comment]
@snrism That would be awesome! With the revamped zk/etcd/consul code (#756), those tests are needed really bad.

Regarding the issue: whatever it's going on with `zk` or `consul` not being ready shouldn't be the test concern. `join` (and `manage`) should be resilient to errors when starting up and retry - you wouldn't want your join to fail and exit just because there was a temporary problem with your store.

Once we fix that, the tests could (and maybe should) start the join **before** starting `zk`/`consul` and it should still be successful.

**Comment by abronan** [comment]
@snrism @aluzzardi :+1: for integration tests for etcd, that'd be awesome.

**Comment by chanwit** [comment]
@aluzzardi got it.

**Comment by aluzzardi** [comment]
Merging this as it might help in the meantime.

@abronan agreed?

**Pull request merged**
