### PR TITLE
Fix connect event

### PR DESCRIPTION
**Pull request by jimmyxian**
Fix: https://github.com/docker/swarm/issues/1215

Signed-off-by: Xian Chaobo <xianchaobo@huawei.com>

### CODE REVIEW

**Comment by jimmyxian** [comment]
ping @abronan 
Do we need integration test for this PR. Integration test need to use KV discovery service.

**Comment by jimmyxian** [comment]
ping @aanm Try this, see if it works.

**Comment by aanm** [comment]
@jimmyxian Yep, this seems to solved the problem. I'm seeing `connect` messages after an agent is detected. Thanks!

**Comment by MHBauer** [comment]
Is it the Lock? Does RegisterEventHandler need to be under the lock?

**Comment by abronan** [comment]
Thanks @jimmyxian, I guess we can include a generic test under the `discovery` folder in integration maybe?

LGTM to me as is

ping @vieux

**Comment by abronan** [comment]
@MHBauer The event handler was not registered before doing the `Connect` in which we emit the `engine_connect` event, thus the event was ignored :)

**Comment by MHBauer** [comment]
Oh, duh, I see it now. Thanks @abronan

**Comment by jimmyxian** [comment]
@aanm Thanks.
@abronan Yeah, under the `discovery` folder seems good. I will do that.

**Comment by jimmyxian** [comment]
ping @abronan @vieux 
I have added an integration test for this PR. Review again. Thanks. :)

**Comment by abronan** [comment]
LGTM

**Comment by vieux** [comment]
LGTM

**Pull request merged**
