### PR TITLE
use golang:1.5.3-alpine in Dockerfile

### PR DESCRIPTION
**Pull request by vieux**
Signed-off-by: Victor Vieux <vieux@docker.com>

### CODE REVIEW

**Comment by vieux** [comment]
@tianon what do you think of this change ?

**Comment by tianon** [comment]
If it builds successfully and the resulting binary functions properly, I'm a fan. :smile:

Isn't there an integration test suite of some kind for `swarm` you can run the binary against to verify it?

**Comment by chanwit** [comment]
@vieux how should I verify this? 

It seems I have to build an image and provision on a cluster rather than doing a regression. Is that correct?

**Comment by chanwit** [comment]
It's broken with `build -m 1GB`. How much memory should I allocate to build it?

```
github.com/mesos/mesos-go/mesosproto
# github.com/mesos/mesos-go/mesosproto
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x843f10, 0x16)
        /usr/local/go/src/runtime/panic.go:527 +0x90
runtime.sysMap(0xc840b90000, 0x100000, 0xa7b00, 0xdab818)
        /usr/local/go/src/runtime/mem_linux.go:203 +0x9b
runtime.mHeap_SysAlloc(0xc95400, 0x100000, 0x0)
        /usr/local/go/src/runtime/malloc.go:426 +0x160
runtime.mHeap_Grow(0xc95400, 0x8, 0x0)
        /usr/local/go/src/runtime/mheap.go:628 +0x63
runtime.mHeap_AllocSpanLocked(0xc95400, 0x4, 0x7fc9a0d384b8)
        /usr/local/go/src/runtime/mheap.go:532 +0x5f1
runtime.mHeap_Alloc_m(0xc95400, 0x4, 0x7f0000000036, 0x7fc9a0d384b8)
        /usr/local/go/src/runtime/mheap.go:425 +0x1ac
runtime.mHeap_Alloc.func1()
        /usr/local/go/src/runtime/mheap.go:484 +0x41
runtime.systemstack(0xc820031e50)
        /usr/local/go/src/runtime/asm_amd64.s:278 +0xab
runtime.mHeap_Alloc(0xc95400, 0x4, 0x10000000036, 0x40d634)
        /usr/local/go/src/runtime/mheap.go:485 +0x63
runtime.mCentral_Grow(0xca07a8, 0x0)
        /usr/local/go/src/runtime/mcentral.go:190 +0x93
runtime.mCentral_CacheSpan(0xca07a8, 0x7fc9a0d384b8)
        /usr/local/go/src/runtime/mcentral.go:86 +0x4d4
runtime.mCache_Refill(0x7fc9a166c000, 0x36, 0x7fc9a0d384b8)
        /usr/local/go/src/runtime/mcache.go:118 +0xcf
runtime.mallocgc.func2()
        /usr/local/go/src/runtime/malloc.go:614 +0x2b
runtime.systemstack(0xc820018000)
        /usr/local/go/src/runtime/asm_amd64.s:262 +0x79
runtime.mstart()
        /usr/local/go/src/runtime/proc1.go:668

goroutine 1 [running]:
runtime.systemstack_switch()
        /usr/local/go/src/runtime/asm_amd64.s:216 fp=0xc83b4a1060 sp=0xc83b4a1058
runtime.mallocgc(0x2900, 0x7f7e80, 0x0, 0x469f34)
        /usr/local/go/src/runtime/malloc.go:615 +0x842 fp=0xc83b4a1130 sp=0xc83b4a1060
runtime.newarray(0x7f7e80, 0x73, 0xc840aed410)
        /usr/local/go/src/runtime/malloc.go:780 +0xc9 fp=0xc83b4a1170 sp=0xc83b4a1130
runtime.makeslice(0x7839a0, 0x73, 0x73, 0x0, 0x0, 0x0)
        /usr/local/go/src/runtime/slice.go:32 +0x165 fp=0xc83b4a11c0 sp=0xc83b4a1170
cmd/compile/internal/gc.Flowstart(0xc840b766c0, 0x0, 0x0)
        /usr/local/go/src/cmd/compile/internal/gc/popt.go:273 +0x2af fp=0xc83b4a12d0 sp=0xc83b4a11c0
cmd/compile/internal/amd64.peep(0xc840b766c0)
        /usr/local/go/src/cmd/compile/internal/amd64/peep.go:83 +0x2e fp=0xc83b4a1330 sp=0xc83b4a12d0
cmd/compile/internal/gc.regopt(0xc840b766c0)
        /usr/local/go/src/cmd/compile/internal/gc/reg.go:1412 +0x2da1 fp=0xc83b4a17e8 sp=0xc83b4a1330
cmd/compile/internal/gc.compile(0xc8237dfc20)
        /usr/local/go/src/cmd/compile/internal/gc/pgen.go:508 +0xe82 fp=0xc83b4a1a58 sp=0xc83b4a17e8
cmd/compile/internal/gc.funccompile(0xc8237dfc20)
        /usr/local/go/src/cmd/compile/internal/gc/dcl.go:1484 +0x1c9 fp=0xc83b4a1ad0 sp=0xc83b4a1a58
cmd/compile/internal/gc.Main()
        /usr/local/go/src/cmd/compile/internal/gc/lex.go:473 +0x1f08 fp=0xc83b4a1dd0 sp=0xc83b4a1ad0
cmd/compile/internal/amd64.Main()
        /usr/local/go/src/cmd/compile/internal/amd64/galign.go:127 +0x58d fp=0xc83b4a1e38 sp=0xc83b4a1dd0
main.main()
        /usr/local/go/src/cmd/compile/main.go:26 +0x189 fp=0xc83b4a1f10 sp=0xc83b4a1e38
runtime.main()
        /usr/local/go/src/runtime/proc.go:111 +0x2b0 fp=0xc83b4a1f60 sp=0xc83b4a1f10
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1721 +0x1 fp=0xc83b4a1f68 sp=0xc83b4a1f60
os/user
```

**Comment by chanwit** [comment]
Sorry my bad. I used a 512MB box to compile it and obviously OOM.
Still doing a test.

**Comment by chanwit** [comment]
Test the image built by `Dockerfile` in this PR and everything works fine.
There are performance degradation (#1750) but I think it's unrelated.

**Comment by chanwit** [comment]
LGTM

**Comment by vieux** [comment]
@tianon since you are crazy about bash, what if we use 

```
cat .git/`cat .git/HEAD | cut -d ' ' -f 2` | cut -c 1-7
```

instead of 

```
git rev-parse --short HEAD
```

The build will be much faster :)

**Comment by tianon** [comment]
Hahahaha, reading ".git" internal state by hand is taking your life into
your own hands, but if you're happy with it (and more importantly, with
debugging it if Git ever breaks your assumptions about the internal state
there), then sounds fine to me. :smile:

**Comment by nishanttotla** [comment]
The variety in git versions people use is huge, I'd be really afraid to run that command on .git state on any other machine :)

**Comment by vieux** [comment]
@tianon @nishanttotla when you think about it:

the flow is `docker build .` so
1) you did the git pull on your machine
2) COPY in the dockerfile it going to copy everything including .git folder in the container
3) we install git
4) we use git

anyway, git on your machine and git on the container could be different

**Comment by chanwit** [comment]
> cat .git/`cat .git/HEAD | cut -d ' ' -f 2` | cut -c 1-7

+1 for this as I can have a fake .git/HEAD to speed up my tests.

**Comment by vieux** [comment]
@docker/swarm-maintainers what do you think about this PR ?
It won't change a thing fo our official image, but it makes our dev image much smaller)

**Comment by nishanttotla** [comment]
@vieux I'm convinced about 
```
cat .git/`cat .git/HEAD | cut -d ' ' -f 2` | cut -c 1-7
```
Are you going to update the PR to include that?

**Comment by MHBauer** [comment]
How much does the git trick save? Can we pin the version of git installed with apk?

**Comment by vieux** [comment]
@nishanttotla not in this PR
@MHBauer it only saves time, not space since we are removing git in the same layer we added it

**Comment by abronan** [comment]
LGTM

**Comment by nishanttotla** [comment]
LGTM.

**Pull request merged**
