### PR TITLE
fix swarm api readme

### PR DESCRIPTION
**Pull request by jimmyxian**
Signed-off-by: Xian Chaobo <xianchaobo@huawei.com>

### CODE REVIEW

**Comment by vieux** [comment]
LGTM, ping @moxiegirl

**Comment by vieux** [comment]
ping @SvenDowideit

**Comment by moxiegirl** [comment]
LGTM

@vieux I have merge privs on docker/docker  so I would have merged this earlier...but I have none here.

**Comment by vieux** [comment]
LGTM

**Pull request merged**
