### PR TITLE
Close TCP connections at disconnect

### PR DESCRIPTION
**Pull request by dongluochen**
Also set GOMAXPROCS to runtime CPU count. 
Signed-off-by: Dong Chen <dongluo.chen@docker.com>

### CODE REVIEW

**Comment by dongluochen** [comment]
This is part of fix for #1838.

**Comment by nathanleclaire** [comment]
FYI, in Go >1.5 GOMAXPROCS is set to number of CPU cores by default: https://golang.org/doc/go1.5#runtime

**Comment by vieux** [comment]
LGTM

**Comment by nishanttotla** [comment]
LGTM

**Comment by nishanttotla** [comment]
Btw this test is failing across several PRs (including this one), not sure why:
```
not ok 155 mesos - docker build
# (from function `retry' in file mesos/api/../../helpers.bash, line 80,
#  from function `discovery_check_swarm_info' in file mesos/api/../../helpers.bash, line 95,
#  from function `swarm_manage' in file mesos/api/../../helpers.bash, line 110,
#  in test file mesos/api/build.bats, line 15)
#   `swarm_manage --cluster-driver mesos-experimental 127.0.0.1:$MESOS_MASTER_PORT' failed
# Unable to find image 'dockerswarm/mesos:0.26.0' locally
# 0.26.0: Pulling from dockerswarm/mesos
# efb8479c8773: Pulling fs layer
# ac4e6f37f1e0: Pulling fs layer
# 9bb3720f3761: Pulling fs layer
```

**Comment by dongluochen** [comment]
Cannot reproduce it locally. I'll monitor it.

**Pull request merged**
