### PR TITLE
delete the link and the sentence since the docs have been moved

### PR DESCRIPTION
**Pull request by YuPengZTE**
Signed-off-by: yupengzte <yu.peng36@zte.com.cn>

### CODE REVIEW

**Comment by nishanttotla** [comment]
@YuPengZTE thanks! Could you please also make sure that other instances of this are included in this PR as well?

**Comment by YuPengZTE** [comment]
@nishanttotla yes, that other instances of this are included in this PR.

This is the result of finding by notepad++:
Search "/docs/" (3 hits in 3 files)
  E:\mygo\src\github.com\docker\swarm\discovery\README.md (1 hit)
	Line 7: file](https://github.com/docker/swarm/blob/master/docs/discovery.md) in this
  E:\mygo\src\github.com\docker\swarm\scheduler\filter\README.md (1 hit)
	Line 7: directory](https://github.com/docker/swarm/blob/master/docs/scheduler/index.md)
  E:\mygo\src\github.com\docker\swarm\scheduler\strategy\README.md (1 hit)
	Line 7: directory](https://github.com/docker/swarm/blob/master/docs/scheduler/index.md)

**Comment by nishanttotla** [comment]
LGTM

@mstanleyjones should we include links to new docs for Swarm as well?

**Comment by mstanleyjones** [comment]
@nishanttotla I'm not sure what you mean. I think that's what this PR was doing?

**Comment by nishanttotla** [comment]
@mstanleyjones this PR just deletes old docs references. I wasn't sure if the new docs had been updated for `docker/swarm` as well (I don't think they are).

**Comment by mstanleyjones** [comment]
There has only been one PR against the standalone swarm docs since the migration and it is for a not-yet-released version of swarm. so no updates yet.

**Pull request merged**
