### PR TITLE
Request for review - Register Mesos with a specified role.

### PR DESCRIPTION
**Pull request by gradywang**
This patch will do:
1. Make Swarm can register Mesos with a specified role.
2. Make Swarm can use the reserved resources to create container.
3. Add the integration tests.

Signed-off-by: Yongqiao Wang yqwyq@cn.ibm.com

### CODE REVIEW

**Comment by gradywang** [comment]
@jimenez , @vieux , @aluzzardi  , @abronan cloud you help to review this patch? Thanks!

**Comment by gradywang** [comment]
@jimenez , cloud you help to review this patch? In this patch, I add a cluster option `mesos.role` to specify a role when register Mesos, and enable swarm to use reserved resources. One integration test also be added. Thanks!

**Comment by gradywang** [comment]
@jimenez , cloud you help to review this patch? In this patch, I add a cluster option `mesos.role` to specify a role when register Mesos, and enable swarm to use reserved resources of the registered role. One integration test also be added. Thanks!

**Comment by gradywang** [comment]
@dongluochen cloud you help to review this patch?

**Comment by nishanttotla** [comment]
Closing due to https://github.com/docker/swarm/pull/2853

**Pull request closed without merging**
