### PR TITLE
prevent double logs with mesos

### PR DESCRIPTION
**Pull request by vieux**
`/create` with with Mesos backend will also start the container.

When you do a `docker run` the cli is doing `/create` and `/start`
For short lived containers, like `busybox ls` it's an issue because it will start the container another time.
You will see 2 `ls` in the logs

With this PR the start is handled by the cluster, it's not proxied anymore. So the mesos backend can choose to no start the container.

### CODE REVIEW

**Comment by abronan** [comment]
@vieux Seems like the build is timing out for Mesos on Jenkins :confused:

**Comment by chanwit** [comment]
@vieux both `janky` and my local regression hang after displaying this line:
`ok 89 mesos - docker commit`.

**Comment by abronan** [comment]
LGTM

**Comment by chanwit** [comment]
LGTM

**Comment by vieux** [comment]
It's my fault but we shouldn't have merge this one, there is a bug in it, that's why `mesos - docker run short lived` never ends.

**Comment by chanwit** [comment]
should we revert it then?

**Comment by vieux** [comment]
@chanwit https://github.com/docker/swarm/pull/1192 :)

**Comment by vieux** [comment]
again, it's my fault, I should have added the `mesos - docker run short lived` test in this PR instead of a new one.

**Pull request merged**
