### PR TITLE
Use ParseRepositoryTag() from engine

### PR DESCRIPTION
**Pull request by dnephin**
While looking into #1293 I noticed this function is a re-implementation of the one from engine, but it doesn't know about digests.

By using `ParseRepositoryTag` we can remove a bunch of code, and simplify `Image.Match()`.

### CODE REVIEW

**Comment by vieux** [comment]
@chanwit can you please take a look since you did https://github.com/docker/swarm/pull/878 ? Thanks.

**Comment by vieux** [comment]
Tested locally: LGTM

**Comment by abronan** [comment]
LGTM

**Comment by chanwit** [comment]
Cool, it seems to solve #878.

LGTM

**Comment by Yam408** [comment]
Good day

Sent from Yahoo Mail on Android 
 
  On الجمعة, أكتوبر ١٦, ٢٠١٥ at ٢:٤٣ ص, Victor Vieux<notifications@github.com> wrote:   
Merged #1299.

**Pull request merged**
