### PR TITLE
use Godep to install from source

### LINKED ISSUE #419: Can't build on Mac OS X
Following build instructions at https://github.com/docker/swarm#2---alternative-download-and-install-from-source

```
go get -u github.com/docker/swarm
# github.com/docker/swarm/cluster
src/github.com/docker/swarm/cluster/node.go:368: not enough arguments in call to n.client.RemoveContainer
```

pat-2:gocode pat$ go version
go version go1.4.2 darwin/amd64
pat-2:gocode pat$ uname -a
Darwin pat-2.local 14.1.0 Darwin Kernel Version 14.1.0: Mon Dec 22 23:10:38 PST 2014; root:xnu-2782.10.72~2/RELEASE_X86_64 x86_64
pat-2:gocode pat$ git version
git version 1.9.3 (Apple Git-50)
pat-2:gocode pat$ docker --version
Docker version 1.5.0, build a8a31ef

### LINKED ISSUE #431: [compile error]: warm/cluster/node.go:368: not enough arguments in call to n.client.RemoveContainer
Getting a compile error with ``0.1.0`` tag:

```#!bash
prologic@daisy
Fri Feb 27 22:21:20
~/contrib/docker-swarm
$ pkgmk -d
=======> WARNING: Packages should be built as root.
=======> Building '/data/packages/docker-swarm#0.1.0-1.pkg.tar.gz'.
bsdtar -p -o -C /home/prologic/contrib/docker-swarm/work/src -xf /data/sources/swarm-0.1.0.tar.gz
+ build
++ pwd
+ export GOPATH=/home/prologic/contrib/docker-swarm/work/src
+ GOPATH=/home/prologic/contrib/docker-swarm/work/src
+ cd swarm-0.1.0
+ go get -d
+ go build
# github.com/docker/swarm/cluster
/home/prologic/contrib/docker-swarm/work/src/src/github.com/docker/swarm/cluster/node.go:368: not enough arguments in call to n.client.RemoveContainer
=======> ERROR: Building '/data/packages/docker-swarm#0.1.0-1.pkg.tar.gz' failed.
```

### PR DESCRIPTION
**Pull request by bacongobbler**
Fixes up the build process to *properly* build `swarm` from source.

closes #431 
closes #419

### CODE REVIEW

**Comment by bacongobbler** [comment]
Forgot about the DCO when making the change. one sec

**Comment by bacongobbler** [comment]
Okay we're good now :)

**Comment by vieux** [comment]
can we add a `go install` so the binary is in your PATH as before ?

**Comment by bacongobbler** [comment]
indeed :)

**Comment by bacongobbler** [comment]
okay done

**Comment by aluzzardi** [comment]
LGTM

@SvenDowideit ?

**Comment by vieux** [comment]
ping @SvenDowideit

**Comment by SvenDowideit** [comment]
LGTM

**Pull request merged**
