### PR TITLE
fix two swarm apis' response status code

### LINKED ISSUE #1929: API: Some Swarm response status codes are different from Docker response status codes
Hi, All:

Recently I found that swarm response status codes are not completely the same as docker native api response status code. For example:

When I do a request  `POST /volumes/create`,  swarm returns a response of 200, while docker will return 201. This kind of incompatible issue exists in lots of Swarm APIs.

I think it's not so good for swarm which aims at supporting totally compatible APIs with docker.

WDYT, my friend.  I will do something to change this case.

### PR DESCRIPTION
**Pull request by allencloud**
Fix two swarm apis' response status code.
Make them compatible with Docker Remote API.
fix #1929 
Signed-off-by: Sun Hongliang <allen.sun@daocloud.io>

### CODE REVIEW

**Comment by nishanttotla** [comment]
@allencloud does this fix #1929 entirely? Could you share the list of endpoints you made? Thanks!

**Comment by allencloud** [comment]
@nishanttotla 
Actually this pr did not fix #1929 entirely, as there are a lot of difference between docker and swarm api response status code and entire fix may need reconstruct many swarm's codes in /api/handlers.go.

And I shared the list of endpoints you mentioned via another PR.
https://github.com/docker/swarm/pull/1942

**Comment by allencloud** [comment]
WDYT this pr ?@nishanttotla @vieux 

Can this be considered a single complete pr ?
Or just a part of feature implementation? As we can make api response status codes better in other places.

**Comment by allencloud** [comment]
docker/docker#20977
this pr has been merged into docker-master.
So delete network return a status code of 204.
And I remove the delete network part of code change.

**Comment by vieux** [comment]
LGTM ping @dongluochen @nishanttotla

**Comment by dongluochen** [comment]
LGTM

**Pull request merged**
