### PR TITLE
Fix images affinity for local registry and digest

### LINKED ISSUE #1676: The image affinity filter doesn't work with local registry and digest
When I run a container with local registry and try to use affinity to filter the image. I get the message "unable to find a node that satisfies", actually there is a container run with the specific images.

The steps:
* run a container
```
docker run -d localhost:5000/mysql
```
*  run another container with affinity filter
```
docker run -e affinity:image==localhost:5000/mysql -d busybox:latest sh
```
and get the message as below:

```
unable to find a node that satisfies image==localhost:5000/mysql
```

And there are more case:
```
localhost.localdomain:5000/samalba/hipache:latest
localhost:5000/foo/bar@sha256:bc8813ea7b3603864987522f02a76101c17ad122e1c46d790efc0fca78ca7bfb

```

docker info output as below:
```
docker info
Containers: 7
Images: 184
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 198
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-33-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 1
Total Memory: 993.1 MiB
Name: c1e97ee2137454b699d0547f0ef058fbc-node1
ID: J7LJ:KIQK:6QQA:MHKG:GUY3:WM55:JUEM:GELK:LCRM:BVZH:2UEU:CG4H
WARNING: No swap limit support
Labels:
 provider=aliyunecs
 aliyun.zone=cn-beijing-c
 aliyun.cluster=c1e97ee2137454b699d0547f0ef058fbc
 aliyun.node=c1e97ee2137454b699d0547f0ef058fbc-node1
...
```

### PR DESCRIPTION
**Pull request by vieux**
Replace #1679
Fix #1676

### CODE REVIEW

**Comment by vieux** [comment]
ping @abronan @dongluochen

**Comment by abronan** [comment]
LGTM

**Comment by vieux** [comment]
ping @nishanttotla

**Comment by navinSing** [comment]
hi, quick q,, have we checked registry on swarm with compose..

**Comment by dongluochen** [comment]
LGTM.

**Comment by navinSing** [comment]
hi, quick q,, have we test'd registry on swarm with compose.. docker engine 1.10 and swarm v1.1.0 and compose 1.6.0. Is this tested ?

**Comment by vieux** [comment]
@navinSing what do you mean ?

**Comment by navinSing** [comment]
@vieux 
Pls find the link to the [issue](https://github.com/docker/compose/issues/2793) with swarm, compose and images/registry.

**Comment by navinSing** [comment]
Any updates?

**Comment by navinSing** [comment]
Did not work ??
started docker daemons with insecure-registry ,, still compose command on swarm was not able to pick the  image...

**Pull request merged**
