### PR TITLE
small refactor retry with soft-image-affinity

### PR DESCRIPTION
**Pull request by vieux**
Signed-off-by: Victor Vieux <vieux@docker.com>

### CODE REVIEW

**Comment by vieux** [comment]
ping @jimmyxian I think it's cleaner with way but I'm wondering if we should store the soft affinity.

@abronan what do you think ?

**Comment by chanwit** [comment]
LGTM

**Comment by jimmyxian** [comment]
@vieux We can't do this. :)
Same as https://github.com/docker/swarm/pull/1099

**Comment by vieux** [comment]
right :)

**Pull request closed without merging**
