### PR TITLE
cleanup: SwarmCluster -> Cluster && Node to node

### PR DESCRIPTION
**Pull request by vieux**

### CODE REVIEW

**Comment by vieux** [comment]
ping @tnachen what do you think about the new method in the interface ?

**Comment by tnachen** [comment]
Hey there, what is the method for? I can't tell from your change

**Comment by vieux** [comment]
It is used only in one specific place for now, on `docker exec`

Same as `docker run`, `docker exec` in in fact `start + attach` so, after the `start` we need the refresh the container before the client does the attach. That's why we explicitly call `RefreshContainer` in `api.go`

**Comment by aluzzardi** [comment]
I'm actually concerned about this. Nodes shouldn't leak to the API at all.

They are an internal thing of a cluster and only Swarm and Mesos with a Swarm framework will ever use them (for instance, if we have a marathon backend, they shouldn't deal with the nodes at all)

**Comment by vieux** [comment]
@aluzzardi You are right, thanks to #441 `api.go` doesn't use node anymore, I'll update this PR right away

**Comment by vieux** [comment]
@aluzzardi PTAL

**Comment by aluzzardi** [comment]
:+1:

**Pull request merged**
