### PR TITLE
eg. should be e.g.

### PR DESCRIPTION
**Pull request by YuPengZTE**
Signed-off-by: YuPengZTE <yu.peng36@zte.com.cn>

### CODE REVIEW

**Comment by allencloud** [comment]
LGTM

**Comment by allencloud** [comment]
@YuPengZTE 
Thanks for your contribution. I found that there is still some other places using `eg.` instead of `e.g.`.
Would you mind change those as well?

**Comment by YuPengZTE** [comment]
Thanks @allencloud , I found the other places using 'eg.' are in '\swarm\vendor', is it better to change them in 'docker' project than in 'swarm' project?
  C:\Go\src\github.com\docker\swarm\vendor\github.com\docker\engine-api\types\container\config.go (1 hit)
	Line 51: 	Image           string                // Name of the image as it was passed by the operator (eg. could be symbolic)
  C:\Go\src\github.com\docker\swarm\vendor\github.com\docker\go-units\duration.go (1 hit)
	Line 11: // (eg. "About a minute", "4 hours ago", etc.).
  C:\Go\src\github.com\docker\swarm\vendor\github.com\docker\go-units\size.go (3 hits)
	Line 52: // capped at 4 valid numbers (eg. "2.746 MB", "796 KB").
	Line 58: // mebibytes, gibibytes, or tebibytes (eg. "44kiB", "17MiB").
	Line 64: // size using SI standard (eg. "44kB", "17MB").
  C:\Go\src\github.com\docker\swarm\vendor\github.com\ugorji\go\codec\gen.go (1 hit)
	Line 589: 	// check if this refers to any xtra types eg. a slice of array: add the array

**Comment by YuPengZTE** [comment]
@allencloud
PTAL https://github.com/docker/docker/pull/26770

**Comment by allencloud** [comment]
@YuPengZTE 
Thanks a lot. It is my fault not to notice it is vendor. I think it is OK to change this one. revendor package will involve more things. We will do more work then.

re-LGTM, merging.

**Pull request merged**
