### PR TITLE
fix image matching in push

### LINKED ISSUE #1028: "No such image" error during build + push
I'm using swarm to build images and push them to DockerHub. For some reason I'm unable to push after building, even though `docker images` shows my newly-built image. Adding a 10s delay between build and push doesn't seem to help.

@aluzzardi asked me to add some debug output to my build; I've got a [gist with failing build output](https://gist.github.com/tony-spataro-rs/a34fed2c404b7fef66b4).

### PR DESCRIPTION
**Pull request by vieux**
close #1028

### CODE REVIEW

**Comment by vieux** [comment]
ping @jimmyxian @aluzzardi @abronan

**Comment by jimmyxian** [comment]
LGTM

**Comment by aluzzardi** [comment]
Is the tag mandatory for other `proxyImage` requests?

**Comment by jimmyxian** [comment]
@aluzzardi 
I have checked, others is OK : )

**Comment by vieux** [comment]
@aluzzardi yes

**Comment by abronan** [comment]
LGTM

ping @aluzzardi

**Pull request merged**
