### PR TITLE
Revert "prevent double starts with mesos"

### PR DESCRIPTION
**Pull request by vieux**
This reverts commit 9a93dcf46bf2a223248c735f2e5bf06b0b87852a.

Signed-off-by: Victor Vieux <vieux@docker.com>

### CODE REVIEW

**Comment by chanwit** [comment]
LGTM
May I merge it now?

**Comment by vieux** [comment]
ping @chanwit @abronan

**Comment by vieux** [comment]
@chanwit yes!

**Comment by chanwit** [comment]
thank you @vieux
I'm going back to rebase my PR.

**Pull request merged**
