### PR TITLE
add ./script/doc to build swarm documentation using the docs.docker.com tooling

### PR DESCRIPTION
**Pull request by SvenDowideit**
Signed-off-by: Sven Dowideit <SvenDowideit@home.org.au>

This also fixes some broken links.

Once merged, I'll add another commit to https://github.com/docker/docker/pull/10869 to use the `docs/mkdocs.yml` in this repository.

### CODE REVIEW

**Comment by SvenDowideit** [comment]
@aluzzardi  @vieux @bfirsh @fredlf

**Comment by aluzzardi** [comment]
@SvenDowideit: How about creating a `docs` or `doc` directory?

That directory would contain:
- `userguide.md` which is currently in the root directory
- A `Dockerfile` (which would be `Dockerfile.docs`)
- A `build.sh` script

This way we could have all docs and docs-related things in the same place.

Eventually (probably not now), I think we could move there the other docs READMEs, such as `scheduler/filter/README.md` etc.

**Comment by SvenDowideit** [comment]
yup, I'd be happy to move the docs stuff to a dir - I was basically going off what you have, on the assumption you like it ;)

**Comment by SvenDowideit** [comment]
@aluzzardi @vieux @bfirsh @fredlf

how's that?

**Comment by aluzzardi** [comment]
Awesome!

LGTM

@vieux ?

**Comment by vieux** [comment]
LGTM

**Pull request merged**
