### PR TITLE
use docker pull <node>...<image>

### PR DESCRIPTION
**Pull request by vieux**
I'm opening this PR even though it will likely never get merged :D

@aluzzardi I can't find the PR you suggested using docker pull node@image, but I thougt about that also, and it's not possible, because the docker cli checks that the repository should be valid.

As an example in this PR I used `...`

It's working great :D

### CODE REVIEW

**Comment by chanwit** [comment]
Hi @vieux I'd like to see a command to explicitly pull an image simultaneously to all Docker instances. Not sure if it's the current behaviour of `pull`?

**Comment by vieux** [comment]
yes I have a branch (not opened the PR yet, where pull and rmi applies to
all the nodes)

On Fri, Jan 30, 2015 at 6:40 PM, Chanwit Kaewkasi <notifications@github.com>
wrote:

> Hi @vieux <https://github.com/vieux> I'd like to see a command to
> explicitly pull an image simultaneously to all Docker instances. Not sure
> if it's the current behaviour of pull?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docker/swarm/pull/337#issuecomment-72300916>.
>



-- 
Victor Vieux
Docker Core Engineer
vieux@docker.com

**Comment by vieux** [comment]
@chanwit see #349

**Comment by vieux** [comment]
this PR was mainly a test, but itn't viable in the long run, closing.

**Pull request closed without merging**
