### PR TITLE
Docker issue #14203 affects nodemanagement tests in Docker 1.9.

### PR DESCRIPTION
**Pull request by dongluochen**
Skip these tests in Docker 1.9. 
Signed-off-by: Dong Chen <dongluo.chen@docker.com>

### CODE REVIEW

**Comment by nishanttotla** [comment]
It's likely unrelated, but why is the following test failing?
```
not ok 159 mesos - docker info
# (from function `retry' in file mesos/api/../../helpers.bash, line 80,
#  from function `discovery_check_swarm_info' in file mesos/api/../../helpers.bash, line 95,
#  from function `swarm_manage' in file mesos/api/../../helpers.bash, line 110,
```

**Comment by dongluochen** [comment]
Thanks @nishanttotlat. It's failing frequently. I'm trying to get a repro of the issue.

**Comment by nishanttotla** [comment]
LGTM

**Comment by vieux** [comment]
LGTM

**Pull request merged**
