### PR TITLE
Removing hard-coded ips from swarm w/ machine doc

### PR DESCRIPTION
**Pull request by nishanttotla**
Using `docker-machine ip` to get rid of hard-coded ip addresses.

Signed-off-by: Nishant Totla <nishanttotla@gmail.com>

### CODE REVIEW

**Comment by nishanttotla** [comment]
ping @moxiegirl @dongluochen

**Comment by MHBauer** [comment]
Do we still want the step ` 1. Get the IP addresses of the three VMs. For example:` around? Maybe add a sentence like L#147 within that step. Specifically the `You can show a docker-machine IPaddr by name` part.

**Comment by nishanttotla** [comment]
@MHBauer you're right. Perhaps we could change it to something like "Check that the machines are running" or something. Since this tutorial is a very basic one, it would be good to leave some redundancy IMO.

**Comment by MHBauer** [comment]
I do agree about using `docker-machine ip` though. If we have it, we should use it, and I think it is good to show that you can both list all of the machines, as well as get the ip of a specific machine by name. It should prevent confusion about mixing up ip addresses in use.

**Comment by dongluochen** [comment]
LGTM. I think using `docker-machine ip` is better than hard coding IP address.

**Comment by nishanttotla** [comment]
Updated with better descriptions.

**Comment by vieux** [comment]
LGTM ping @moxiegirl

**Comment by moxiegirl** [comment]
LGTM

**Pull request merged**
