### PR TITLE
Add support do with image digest

### PR DESCRIPTION
**Pull request by jimmyxian**
Fix: https://github.com/docker/swarm/issues/1293
Signed-off-by: Xian Chaobo <xianchaobo@huawei.com>

### CODE REVIEW

**Comment by abronan** [comment]
It still seems that there are faulty Jenkins hosts :/ we'll investigate.

/cc @vieux

**Comment by jimmyxian** [comment]
Ready to review. :)
ping @vieux @chanwit @abronan

**Comment by abronan** [comment]
LGTM

But we need to bring back the CI from the dead :smile:

**Comment by chanwit** [comment]
LGTM for both codes and tests.

**Pull request merged**
