### PR TITLE
Fix api/ps tests

### PR DESCRIPTION
**Pull request by dongluochen**
`--before` is deprecated. 
Signed-off-by: Dong Chen <dongluo.chen@docker.com>

### CODE REVIEW

**Comment by vieux** [comment]
LGTM

**Comment by nishanttotla** [comment]
LGTM

**Comment by MHBauer** [comment]
Would have been nice to see a `--filter before=CID` test to replace it.

**Comment by nishanttotla** [comment]
@MHBauer add it 😸

**Pull request merged**
