### PR TITLE
add support for docker volume ls & inspect

### PR DESCRIPTION
**Pull request by vieux**
Related to #1189

Add support for `docker volume ls` & `docker volume inspect`

### CODE REVIEW

**Comment by chanwit** [comment]
@vieux are you going to have `/volumes/json` similar to `/images/json` in this PR?

**Comment by vieux** [comment]
@chanwit no because unfortunately, the engine didn't respect the same convention /cc @icecrime @cpuguy83

**Comment by chanwit** [comment]
@vieux also does `volume ls` support `--filter`? 
it's going to be similar to `images` when we'd like to filter by a node name (and maybe in another PR).

/cc @icecrime @cpuguy83

**Comment by cpuguy83** [comment]
@vieux We can have it follow the same convention, I think that makes sense.  @icecrime ?

**Comment by vieux** [comment]
@cpuguy83 @icecrime as you want, I know the `/json` is ugly and not rest like (especially because we never did the `/xml`) but it would follow the same convention

**Comment by vieux** [comment]
@chanwit I think you should open an issue on https://github.com/docker/docker to propose --filter on volume

**Comment by vieux** [comment]
I think this one is good to merge as is as a 1st step /cc @abronan @chanwit @jimmyxian

**Comment by abronan** [comment]
:+1: LGTM

**Comment by chanwit** [comment]
LGTM

**Pull request merged**
