### PR TITLE
Add cross-compile back to Travis and Go 1.4

### PR DESCRIPTION
**Pull request by tianon**
I discussed this with @vieux in `#docker-dev`, and he mentioned that I should open a PR so we can test the speed. :+1:

### CODE REVIEW

**Comment by vieux** [comment]
@tianon tests fail

**Comment by tianon** [comment]
Whoo DCO! :smile:

**Comment by tianon** [comment]
Looks like it needs to exclude `go vet` on not host platforms too :innocent:

**Comment by tianon** [comment]
So I guess the benefits are getting smaller and smaller now, reintroducing complexity in `.travis.yml`... :disappointed:

**Pull request closed without merging**
