### PR TITLE
Move note on top of Nodes config to avoid confusion

### PR DESCRIPTION
**Pull request by abronan**
Moving the Note at the bottom of the Nodes Configuration part for better visibility. Saw a lot of confusion on IRC and a few Issues on the setup part (and the fact that you need to launch the docker daemon listening on TCP).

ping @SvenDowideit

### CODE REVIEW

**Comment by vieux** [comment]
@abronan can you please sign your commit :P

**Comment by abronan** [comment]
@vieux Errr just changed my git aliases and forgot the -s :ghost:

**Comment by aluzzardi** [comment]
LGTM

@SvenDowideit ?

**Comment by abronan** [comment]
ping @moxiegirl

**Comment by moxiegirl** [comment]
@abronan When you have a document with this many notes in odd places, it can indicate structural problems.  I think you would get a better performance on the page by clarifying what is required to run Swarm in a prereq section. Then, making the Setup procedure look like one.  So, I recommend this:

https://gist.github.com/moxiegirl/5874c99da108bb630763

**Comment by abronan** [comment]
Thank you for the feedback! I definitely agree, will update with the proper structure.

**Comment by abronan** [comment]
@moxiegirl Updated thanks to your feedback and added a few details.

**Comment by moxiegirl** [comment]
@abronan You lost the alignment on the indented procedure i. and ii. --- Also, just as an fyi it isn't good practice to preface with at `$` if you are only showing command syntax.  That is why I removed them.  People expect to see a real command line example and you are actually illustrating the command line syntax/format.

**Comment by vieux** [comment]
@moxiegirl can you please give me one last LGTM ? Thanks

**Comment by moxiegirl** [comment]
LGTM

**Comment by abronan** [comment]
@moxiegirl Thanks for the thorough review :+1:

**Pull request merged**
