### PR TITLE
fix push image

### PR DESCRIPTION
**Pull request by jimmyxian**
Fix: https://github.com/docker/swarm/issues/1354

`tag` in push url is a `Query Parameter`

Signed-off-by: Xian Chaobo <xianchaobo@huawei.com>

### CODE REVIEW

**Comment by jimmyxian** [comment]
ping @linecheng 
Try this and see if it works. Thanks

**Comment by jimmyxian** [comment]
ping @vieux @abronan 
The integration test for `Push` need a registry. Maybe we can add later.

**Comment by linecheng** [comment]
ping @jimmyxian 
I have already test  it  and it works very well.
Thanks for your job .

**Comment by vieux** [comment]
LGTM

**Pull request merged**
