### PR TITLE
Update libkv Godeps

### PR DESCRIPTION
**Pull request by abronan**
Updates `libkv` Godeps.

This includes a lot of small fixes and refactor thanks to the contributions from @chenchun and @springi99

**Do not merge** until I fully test this udpate with the 3 backends (I have tested etcd and zookeeper but not Consul yet).

Signed-off-by: Alexandre Beslic <abronan@docker.com>

### CODE REVIEW

**Comment by abronan** [comment]
@vieux PTAL ready for review

**Comment by jimmyxian** [comment]
LGTM

**Comment by vieux** [comment]
LGTM

**Pull request merged**
