### PR TITLE
Point to documentation in the readme

### PR DESCRIPTION
**Pull request by bfirsh**
So the docs aren't duplicated in two places. What do you think?

### CODE REVIEW

**Comment by vieux** [comment]
hum, I'm not sure. @aluzzardi ?

**Comment by bfirsh** [comment]
FWIW, we do something along these lines for both Machine and Compose and it seems to work pretty well:

https://github.com/docker/machine
https://github.com/docker/compose

**Comment by aluzzardi** [comment]
I like that. Makes the README to the point and we don't have to update the docs twice.

@SvenDowideit, @vieux ?

LGTM

**Comment by vieux** [comment]
ok, LGTM

**Comment by vieux** [comment]
@SvenDowideit ?

**Comment by bfirsh** [comment]
or @fredlf, perhaps?

**Comment by SvenDowideit** [comment]
yup, very LGTM - if the README.md contains contributor centric info only, then users will always be pointed to the one place :)

**Comment by fredlf** [comment]
Yes, absolutely yes. One source to rule them all! LGTM. Don't have priv. to merge, however.

**Pull request merged**
