### PR TITLE
Fixed typos

### LINKED ISSUE #1380: Dead links in docs
@docker I found a typo on https://t.co/pS7bqR17wY  it should be `$ docker network ls` not `$ docker networks ls` under h2::Create a network

### PR DESCRIPTION
**Pull request by auzias**
A copy/paste containing a typos was made. I just replace `$ docker networks ls` with `$ docker network ls`.

Fix #1380

### CODE REVIEW

**Comment by vieux** [comment]
LGTM thanks @auzias

**Comment by vieux** [comment]
@moxiegirl you might want to cherry-pick this somehow

**Comment by moxiegirl** [comment]
@vieux Did you reset the `docs` branch?

**Comment by vieux** [comment]
@moxiegirl yes :)

**Comment by vieux** [comment]
@moxiegirl can you please cherry pick this one when you have time ?
Thanks.

**Pull request merged**
