### PR TITLE
Reduce CPU usage

### PR DESCRIPTION
**Pull request by xianlubird**
In my case, I start 1000 goroutine to create container. I monitor the swarm find that it's CPU usage is very high, almost beyond 300%(equal to 3 core). Using golang profile message, we find that it's regular expressions `Compile`. This action cost much CPU and I fix this problem by reducing compile times.  Having this PR, CPU usage could reduce to 130%(equals to 1.3 core).

@allencloud @dongluochen @nishanttotla WDYT ?

Signed-off-by: Xianlu <xianlu.cxl@alibaba-inc.com>

### CODE REVIEW

**Comment by dongluochen** [comment]
LGTM.

**Comment by nishanttotla** [comment]
LGTM. Test failures are unrelated, but let's wait to rebase on top of #2522.

**Comment by dongluochen** [comment]
@xianlubird Can you rebase to rebuild your PR in go1.7?

**Comment by xianlubird** [comment]
@dongluochen @nishanttotla Done.

**Pull request merged**
