### PR TITLE
Updating with new tooling that supports GitHub source Markdown

### PR DESCRIPTION
**Pull request by moxiegirl**
Fixes content so it returns no linking errors

Signed-off-by: Mary Anthony <mary@docker.com>

### CODE REVIEW

**Comment by vieux** [comment]
@moxiegirl do you want this merged for 0.5 ?

**Comment by moxiegirl** [comment]
@vieux Yes please.

**Comment by vieux** [comment]
LGTM ... I guess :)

**Comment by abronan** [comment]
LGTM

**Comment by moxiegirl** [comment]
@vieux you make me cry with your "i guess" :cry:   but you merged it anyway! :sunglasses:

**Pull request merged**
