### PR TITLE
Fix nullptr panic in pending containers.

### LINKED ISSUE #1289: runtime error in port filter
I'm running master with 1f66308

```
swarm.master_1 | 2015/10/13 22:02:51 http: panic serving 172.17.42.1:47556: runtime error: invalid memory address or nil pointer dereference
swarm.master_1 | goroutine 567 [running]:
swarm.master_1 | net/http.(*conn).serve.func1(0xc82086d6b0, 0x7fbaf36c0058, 0xc82014ac08)
swarm.master_1 |        /usr/local/go/src/net/http/server.go:1287 +0xb5
swarm.master_1 | github.com/docker/swarm/scheduler/filter.(*PortFilter).portAlreadyInUse(0x11a9ae0, 0xc82025ab40, 0x0, 0x0, 0x0, 0x0, 0x0)
swarm.master_1 |        /go/src/github.com/docker/swarm/scheduler/filter/port.go:92 +0xb2
swarm.master_1 | github.com/docker/swarm/scheduler/filter.(*PortFilter).filterBridge(0x11a9ae0, 0xc820fa6380, 0xc82014ac48, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
swarm.master_1 |        /go/src/github.com/docker/swarm/scheduler/filter/port.go:52 +0x27e
swarm.master_1 | github.com/docker/swarm/scheduler/filter.(*PortFilter).Filter(0x11a9ae0, 0xc820fa6380, 0xc82014ac48, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
swarm.master_1 |        /go/src/github.com/docker/swarm/scheduler/filter/port.go:28 +0x15a
swarm.master_1 | github.com/docker/swarm/scheduler/filter.ApplyFilters(0xc82007e800, 0x5, 0x8, 0xc820fa6380, 0xc82014ac48, 0x1, 0x1, 0x0, 0x0, 0x0, ...)
swarm.master_1 |        /go/src/github.com/docker/swarm/scheduler/filter/filter.go:61 +0x12d
swarm.master_1 | github.com/docker/swarm/scheduler.(*Scheduler).SelectNodesForContainer(0xc820108360, 0xc82014ac38, 0x1, 0x1, 0xc820fa6380, 0x0, 0x0, 0x0, 0x0, 0x0)
swarm.master_1 |        /go/src/github.com/docker/swarm/scheduler/scheduler.go:37 +0xb3
```

This failure is triggered by [this](https://github.com/docker/compose/blob/c06d9ec6723beae80f63f7b251d31f393502536b/tests/integration/cli_test.py#L591) test in the `docker-compose` test suite. It fails when compose tried to create two containers with the same port.  The create container call runs in parallel on the client, so both containers are created at approximately the same time. This failure seems to be easily reproducible (every run causes this failure).

You can reproduce the failure with:

```
parallel docker run -d -p 8888 alpine:edge sleep ::: 2 2
```

### PR DESCRIPTION
**Pull request by aluzzardi**
Fixes #1289

Signed-off-by: Andrea Luzzardi <aluzzardi@gmail.com>

### CODE REVIEW

**Comment by dnephin** [comment]
@aluzzardi Thanks for the fix!

I confirmed this patch fixes the issue for the compose test suite and the `parallel docker run`

**Comment by abronan** [comment]
LGTM

ping @vieux

**Comment by chanwit** [comment]
I know that a parallel thing is hard to write test. 

But could you please having an integration test spinning 2-3 docker run at the same time to cover this?

**Comment by jimmyxian** [comment]
This might be tricky to write a test for this one. :)
LGTM

**Comment by abronan** [comment]
@chanwit @jimmyxian Let's merge this asap as we are going to release a new RC soon. We can implement the tests in a follow up PR.

**Comment by chanwit** [comment]
@abronan No problem.

But please start a new PR for its integration test.

This issue is a good demonstration that with a hurry to meet the *deadline*, we got a blocker bug slipped through the RC.

This will be a bigger problem as we have already declared that Swarm is *production-ready* ;-)

**Comment by abronan** [comment]
@chanwit I understand the concern.

I think we are good example of having a lot of tests and this one bug was obvious so I don't want to block people testing with swarm Master and Compose in a time of code freeze :)

Not saying we shouldn't implement tests but bad timing really as we went on a company event and I was preparing the PR with the test.

**Pull request merged**
