### PR TITLE
add build-arg for architecture

### PR DESCRIPTION
**Pull request by firecyberice**
Add GOARCH as build-arg so we can build for arm too.

Signed-off-by: Andreas Eiermann andreas@hypriot.com

### CODE REVIEW

**Comment by xiaods** [comment]
GOARCH is introduce by go 1.5 and give a complete list. so it well done.

**Comment by allencloud** [comment]
ping @dongluochen @nishanttotla

**Comment by dongluochen** [comment]
It sounds good to me. @vieux, any concern of adding GOARCH?

**Comment by firecyberice** [comment]
ping @dongluochen @vieux @allencloud @nishanttotla Can you please merge this PR or give me a hint what needs an improvement?

**Comment by dongluochen** [comment]
@firecyberice Sorry for my delay. Please rebase.

**Comment by firecyberice** [comment]
@dongluochen rebase done :-)

**Comment by firecyberice** [comment]
ping

**Comment by dongluochen** [comment]
rekick CI to check the failure on `not ok 9 build with node constraint and buildarg` in `engine-master`.

**Comment by firecyberice** [comment]
How can this failing [engine-master](https://jenkins.dockerproject.org/job/Swarm-PRs%20%28engine%20master%29/3101/console) test get fixed? Does anyone have an idea?

**Comment by nishanttotla** [comment]
I don't think this is related, I've seen these mesos tests fail on `engine-master` on some other PRs as well.

LGTM

**Comment by firecyberice** [comment]
There is another [PR](https://github.com/docker/swarm-library-image/pull/10) waiting for this.

**Comment by dongluochen** [comment]
LGTM.

**Pull request merged**
