### PR TITLE
Fix integration tests, --exec-driver has been removed in docker master

### PR DESCRIPTION
**Pull request by abronan**
ping @docker/swarm-maintainers 

Signed-off-by: Alexandre Beslic <abronan@docker.com>

### CODE REVIEW

**Comment by vieux** [comment]
@abronan can you remove every `EXEC_DRIVER` ? 


````
./test/integration/helpers.bash:29:EXEC_DRIVER=${EXEC_DRIVER:-native}
./test/integration/helpers.bash:182:					--storage-driver=$STORAGE_DRIVER --exec-driver=$EXEC_DRIVER \
./test/integration/run.sh:26:	-e "EXEC_DRIVER=$EXEC_DRIVER" \
./test/integration/test_runner.sh:29:	--storage-driver="$STORAGE_DRIVER" --exec-driver="$EXEC_DRIVER" &
```

**Comment by abronan** [comment]
@vieux updated

**Comment by jimmyxian** [comment]
LGTM,  CI works now

**Comment by dongluochen** [comment]
LGTM. Thanks @abronan!

**Pull request merged**
