### PR TITLE
docker volume create & docker volume delete

### PR DESCRIPTION
**Pull request by vieux**

### CODE REVIEW

**Comment by vieux** [comment]
@lukemarsden can you try flocker with this PR and tell me how it goes ? Thanks.

**Comment by lukemarsden** [comment]
Hey @vieux, sure, we'll take a look.

**Comment by ehazlett** [comment]
LGTM

**Comment by vieux** [comment]
@lukemarsden any news on this PR ? Thank you

**Comment by wallnerryan** [comment]
@vieux will this PR support opts as well?

**Comment by vieux** [comment]
yes, it includes `DriverOpts map[string]string`

**Comment by abronan** [comment]
LGTM. Let's merge this now, if there is any feedback on this one feel free to comment on this PR or in a separate issue.

**Comment by lukemarsden** [comment]
Sorry for the delay, @vieux - the person I asked to take a look at this went on vacation. I'm trying to organize a followup now. We would very much like this to work with Flocker and it's not necessarily obvious that my reasoning in https://github.com/docker/swarm/issues/1189#issuecomment-138583580 will hold for the current incarnation of the Flocker Docker plugin, so this is high priority for us.

**Comment by klaus1982** [comment]
Any design document for this?

**Pull request merged**
