### PR TITLE
digital ocean discovery

### PR DESCRIPTION
**Pull request by xcrezd**
Signed-off-by: dmitrik <dmitrik@ironsrc.com>

Adds digital ocean discovery package

All the droplets will be fetched periodically from DO API and added to swarm

optional env variables

SWARM_DISCOVERY_DIGITALOCEAN_PORT
docker port in digital ocean droplet

SWARM_DISCOVERY_DIGITALOCEAN_NETWORK
network type (public/private)

### CODE REVIEW

**Comment by vieux** [comment]
@xcrezd something is wrong with your PR can you rebase on the last master and to a force push ?

**Comment by aluzzardi** [comment]
I wouldn't want to go down the rabbit hole - if we add discovery for one provider then we'd need to add it to a bunch of different providers.

The same today can be achieved by using `docker-machine`: It has drivers for digital ocean and will set up swarm with discovery automatically for you.

/cc @vieux

**Comment by xcrezd** [comment]
@aluzzardi 
Can you please explain how can i achieve this now by docker-machine.

**Comment by xcrezd** [comment]
@vieux 

$ git ch master
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.
$ git pull
Already up-to-date.
$ git ch digital_ocean_discovery
Switched to branch 'digital_ocean_discovery'
$ git rebase master
Current branch digital_ocean_discovery is up to date.

**Comment by shimont** [comment]
+1 great commit
i really love it

**Comment by vieux** [comment]
@xcrezd don't you see your PR has more than 7k new lines and 51 lines changed ? I think there is an issue.

**Comment by vieux** [comment]
@xcrezd my bad, it's godep :D

**Comment by aluzzardi** [comment]
@xcrezd: Basically, docker-machine would create the nodes for you and then automatically set them up for discovery

**Comment by abronan** [comment]
Thank you for the contribution @xcrezd, although as @aluzzardi mentioned, merging this would mean accepting PRs to include discovery mechanisms from many other providers, which will be hard for us to maintain in the long term as the code base increases. DiscoveryThis change would probably make more sense in a repository like `docker-machine` where the discovery mechanism would be directly handled by the tool when using the *Digital Ocean* driver, without relying on the Hub discovery service.

I'm closing this for now but feel free to comment below.

**Pull request closed without merging**
