### PR TITLE
Godeps for Mesos

### PR DESCRIPTION
**Pull request by jimenez**
Signed-off-by: Isabel Jimenez <contact.isabeljimenez@gmail.com>

### CODE REVIEW

**Comment by jimenez** [comment]
I'm know this is huge, but once compiled, the binary will be only 2 mb bigger. Also, as soon as we have out of process plugins for swarm, this code will go away, so this is only "temporary"

**Comment by abronan** [comment]
@jimenez :+1:

**Comment by vieux** [comment]
LGTM

**Comment by abronan** [comment]
LGTM

**Pull request merged**
