### PR TITLE
Fix typo in the rescheduling doc

### LINKED ISSUE #2438: Docs for rescheduling typo
The docs on swarm rescheduling at https://docs.docker.com/swarm/scheduler/rescheduling/ currently say:

> To set the on-node-failure policy with a reschedule environment variable:
> 
> $ docker run -d -e reschedule:on-node-failure redis

I'm pretty sure it should actually say`-e reschdule=on-node-failure` with an `=` sign, unless there is a syntax I'm unaware of. At any rate with Docker 1.12:

```
amouat@marvin proj$ docker run --env="reschedule:on-node-failure" debian env
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=5109c5e59dca
HOME=/root
amouat@marvin proj$ docker run --env="reschedule=on-node-failure" debian env
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=1ee10bbd48f2
reschedule=on-node-failure
HOME=/root
```

### PR DESCRIPTION
**Pull request by mstanleyjones**
Fixes #2438

Signed-off-by: Misty Stanley-Jones <misty@docker.com>

### CODE REVIEW

**Comment by mstanleyjones** [comment]
@nishanttotla PTAL

**Comment by allencloud** [comment]
Good Catch. Thanks a lot @mstanleyjones 
LGTM

**Comment by mstanleyjones** [comment]
I made a mistake and will fix it. I was trying to address #2438.

**Comment by mstanleyjones** [comment]
I fixed my typo, and verified that the syntax with the = sign works correctly. Ping @nishanttotla @allencloud @thaJeztah

**Comment by allencloud** [comment]
ping @mstanleyjones 
I am afraid we got conflict. Maybe we need to rebase this and solve this. Thanks a lot.

**Comment by thaJeztah** [comment]
@mstanleyjones this doc was moved; can you reopen this one in https://github.com/docker/docker.github.io/tree/master/swarm ?

**Comment by mstanleyjones** [comment]
Moved to https://github.com/docker/docker.github.io/pull/236.

**Pull request closed without merging**
