### PR TITLE
Add support some run options

### PR DESCRIPTION
**Pull request by jimmyxian**
Fix : https://github.com/docker/swarm/issues/1312
Depends on : https://github.com/samalba/dockerclient/pull/178

Add following `run` options:
+       StopSignal      string
+       MemoryReservation int64
+       KernelMemory    int64
+       MemorySwappiness int64
+       DNSOptions      []string
+       GroupAdd        []string

Signed-off-by: Xian Chaobo <xianchaobo@huawei.com>

### CODE REVIEW

**Comment by jimmyxian** [comment]
The _test file is removed due to (https://github.com/docker/swarm/issues/1319)

**Comment by chanwit** [comment]
Haven't review this PR yet, but I think removal of test files by `godep` should be OK.
ping @docker/swarm-maintainers

**Comment by jimmyxian** [comment]
@chanwit
Yeah, if `godep` remove `_test` file is OK , all of us should switch to the latest `godep` :)

**Comment by abronan** [comment]
I'm OK with removing the test files with godep. It was unnecessary.

changes LGTM once PR is merged in dockerclient :)

**Comment by vieux** [comment]
@jimmyxian changes were merged in dockerclient, can you please rebase ?

Thanks

**Comment by jimmyxian** [comment]
@abronan @vieux 
Rebased,
Reviewed again. Thanks

**Comment by dongluochen** [comment]
LGTM.

Thanks,
Dong

**Pull request merged**
