### PR TITLE
Improve godocs for exported values in api pkg

### PR DESCRIPTION
**Pull request by peggyl**
Adds more specific documentation for exported values in the swarm/api package. 

This will probably need to be rebased onto https://github.com/docker/swarm/pull/514 once that gets merged.

### CODE REVIEW

**Comment by abronan** [comment]
Thank you @peggyl!! Agreed, we will wait for #500 to be merged first :)

**Comment by abronan** [comment]
@peggyl You can rebase now :+1:

**Comment by vieux** [comment]
thanks!

**Comment by vieux** [comment]
LGTM

**Comment by technolo-g** [comment]
Nice!

**Pull request merged**
