### PR TITLE
fix event deletion under lock

### PR DESCRIPTION
**Pull request by vieux**
Signed-off-by: Victor Vieux <victorvieux@gmail.com>

### CODE REVIEW

**Comment by MHBauer** [comment]
What does this do that https://github.com/docker/swarm/pull/1414/files#diff-66d73e49acd1e88edc3f9f514d0a8f4cR58 doesn't? (I hope that link came out right, but L#58 in the same file.)

**Comment by aluzzardi** [comment]
@abronan @dongluochen Hey, can you guys try to review this PR?

It's quite tricky but we think this solves a panic.

**Comment by abronan** [comment]
@MHBauer It just fixes a very rare race when an event channel can be deleted before we attempt to close it (but go panics when you try to close an already closed channel).

LGTM (sorry for the delay, the *DO NOT MERGE* didn't helped)

The fixes a panic but not sure #1426 is quite the same issue. 

This can be safely included though.

**Comment by MHBauer** [comment]
I think I see it now. There's nothing that says we're not already in the middle of `handle`ing an event before we `handle` the next one. Concurrent programming is hard.

**Comment by abronan** [comment]
ping @dongluochen

**Comment by dongluochen** [comment]
LGTM.

**Comment by jimmyxian** [comment]
LGTM

**Comment by agsmorodin** [comment]
Hi,

In which swarm release can I expect to see this fix?  thanks.

**Pull request merged**
