### PR TITLE
Update consul api and Token support in Consul

### PR DESCRIPTION
**Pull request by ch3lo**
With this update is possible to use ACL Token in the Consul backend, because the  new Consul API uses the CONSUL_HTTP_TOKEN environment to setup a default token in the initializer. I think this solution is better than use the anonymous token with the needed permissions.

Regards

### CODE REVIEW

**Comment by aluzzardi** [comment]
ping @abronan

**Comment by abronan** [comment]
Hi @ch3lo, thanks for the contribution. ACL is a new feature of Consul `0.6` which is not released yet so this should be documented somehow.

I'm unsure whether we should merge this now or wait a little bit. I also need to test Consul `0.6` with `libkv`, even if the tests appears to be fine.

**Comment by ch3lo** [comment]
Sounds good, tell me if I can help.

Regards

**Comment by abronan** [comment]
@ch3lo Thanks. Let's wait for the official release of Consul 0.6 (which is still in RC phase) and update the docs accordingly to mention that ACL is a new feature in Consul 0.6 :)

**Comment by abronan** [comment]
Hey @ch3lo, `0.6.0` is out now, is it possible to update this PR to include it in the Godeps instead of `v0.6.0-rc2`? Thanks!

Otherwise LGTM, seems like `CONSUL_HTTP_TOKEN` was there before `0.6.0`, good to know! :)

**Comment by ch3lo** [comment]
sure I can. Good news :)

**Comment by ch3lo** [comment]
yep Im having conflicts with amend. Sorry

**Comment by vieux** [comment]
@ch3lo something is still not right in your godep

**Comment by vieux** [comment]
@ch3lo can you please squash your commits ?

**Comment by abronan** [comment]
@ch3lo I'm not quite sure what this does now and why we would need a dependency on `serf/coordinate` or `goclean-http`. It also seems that Consul API version is still `0.5.0` in Godeps. Can you update the PR in its old state, but just doing a `godep update` on `github.com/hashicorp/consul/api` (making sure it's checked out in your go env to `v0.6.0`)? Let me know if I'm missing something obvious. Thanks!

**Comment by abronan** [comment]
Closing as this was updated by #1589.

Thanks for opening this one in the first place @ch3lo!

**Pull request closed without merging**
