### PR TITLE
fix CI

### PR DESCRIPTION
**Pull request by vieux**
Signed-off-by: Victor Vieux <vieux@docker.com>

### CODE REVIEW

**Comment by abronan** [comment]
LGTM

ping @aluzzardi

**Comment by aluzzardi** [comment]
Why overlay?

**Comment by vieux** [comment]
@aluzzardi the CI was switched to overlay, dind has to use the same

**Comment by vieux** [comment]
It will require other fixed (mostly mesos) but the CI is now green. It's good to merge

**Comment by aluzzardi** [comment]
LGTM

**Pull request merged**
