### PR TITLE
bugfix:  remove "tcp user timeout" setting 

### LINKED ISSUE #1838: Crash using 1.1.1
Hi,
I started swarm 1.1.1 and now I got this after a while:

```
runtime: program exceeds 10000-thread limit
fatal error: thread exhaustion

runtime stack:
runtime.throw(0xfb3400, 0x11)
	/usr/local/go/src/runtime/panic.go:527 +0x90
runtime.checkmcount()
	/usr/local/go/src/runtime/proc1.go:93 +0x94
runtime.mcommoninit(0xc845ae4480)
	/usr/local/go/src/runtime/proc1.go:113 +0xf2
runtime.allocm(0xc82001f500, 0x10ce9e0, 0x40dc74)
	/usr/local/go/src/runtime/proc1.go:868 +0x9c
runtime.newm(0x10ce9e0, 0xc82001f500)
	/usr/local/go/src/runtime/proc1.go:1099 +0x2f
runtime.startm(0xc82001f500, 0x100000001)
	/usr/local/go/src/runtime/proc1.go:1186 +0xef
runtime.wakep()
	/usr/local/go/src/runtime/proc1.go:1258 +0x59
runtime.ready(0xc846c61680, 0x3)
	/usr/local/go/src/runtime/proc1.go:149 +0x132
runtime.goready.func1()
	/usr/local/go/src/runtime/proc.go:196 +0x29
runtime.systemstack(0xc820026000)
	/usr/local/go/src/runtime/asm_amd64.s:262 +0x79
runtime.mstart()
	/usr/local/go/src/runtime/proc1.go:668

........ lots of stack...
```

And heaps and heaps of stack info... like 13MB if anyone interested.

Not sure what happened here.

Running on CoreOS.
Marathon 0.15.1
Mesos 0.26
Logging to AWS

### PR DESCRIPTION
**Pull request by skoo87**
fix #1838  #1859

conn.File()  in setTCPUserTimeout(), is root cause of the bug.

If understand Chinese, can refer to  http://zhuanlan.zhihu.com/p/22474724

### CODE REVIEW

**Comment by skoo87** [comment]
other, the tcp option is not supported by all kernel. so the setting is not right.

If must set it,  can use the unsafe or reflect package to get 'fd' of the connetion, then do it. But it's not  enough safe.

**Comment by s7v7nislands** [comment]
can just add syscall.SetNonblock in setTCPUserTimeout() ?

**Comment by hubo1016** [comment]
It is simple to add SetNonblock again and that should solve the problem. But I'm curious at:

- is it always safe to set this option, even on a kernel which does not support it?
- are there any more unexpected results to duplicate the fd and set the option on the duplicated fd e.g. the option does not work or more side effects?
- is it really important to set this option?

If that option is not that important and may cause further problems, maybe it is wise to remove it entirely. Anyway not all kernel versions support it.

**Comment by skoo87** [comment]
@hubo1016  @s7v7nislands  

The returned os.File's file descriptor is different from the connection's. Attempting to change properties of the original using this duplicate may or may not have the desired effect.

This is the comments of conn.File().

**Comment by s7v7nislands** [comment]
why may not have the desired effect? @skoo87

**Comment by hubo1016** [comment]
@s7v7nislands I think it depends on the kernel implementation

**Comment by skoo87** [comment]
http://www.gnu.org/software/libc/manual/html_node/Descriptor-Flags.html 

File descriptor flags are miscellaneous attributes of a file descriptor. These flags are associated with particular file descriptors, so that if you have created duplicate file descriptors from a single opening of a file, each descriptor has its own set of flags.

Or "man 2 dup"

**Comment by s7v7nislands** [comment]
Currently there is just one file descriptor flag: FD_CLOEXEC, which causes the descriptor to be closed if you use any of the exec… functions

I think Nonblocking is different.

**Comment by s7v7nislands** [comment]
https://www.gnu.org/software/libc/manual/html_node/File-Status-Flags.html#File-Status-Flags

**Comment by allencloud** [comment]
Thanks a lot for your contribution, and thorough research, and details provided as well.

ping @dongluochen 
Maybe Chinese reference can be helpful.

ping @nishanttotla @vieux @jimmyxian

**Comment by dongluochen** [comment]
@skoo87 Thanks for submitting the PR. This change makes sense. 

LGTM.

**Comment by allencloud** [comment]
Thanks for your contribution, @skoo87 
It is indeed a good work for swarm.
Just one more thing may be needed to change. Since func `setTCPUserTimeout` is not used. Can your remove this definition from `utils_unix.go`, `utils_windows.go` and `utils_darwin.go`?
Thanks a lot again.

**Pull request closed without merging**
