### PR TITLE
Remove setTCPUserTimeout 

### LINKED ISSUE #1838: Crash using 1.1.1
Hi,
I started swarm 1.1.1 and now I got this after a while:

```
runtime: program exceeds 10000-thread limit
fatal error: thread exhaustion

runtime stack:
runtime.throw(0xfb3400, 0x11)
	/usr/local/go/src/runtime/panic.go:527 +0x90
runtime.checkmcount()
	/usr/local/go/src/runtime/proc1.go:93 +0x94
runtime.mcommoninit(0xc845ae4480)
	/usr/local/go/src/runtime/proc1.go:113 +0xf2
runtime.allocm(0xc82001f500, 0x10ce9e0, 0x40dc74)
	/usr/local/go/src/runtime/proc1.go:868 +0x9c
runtime.newm(0x10ce9e0, 0xc82001f500)
	/usr/local/go/src/runtime/proc1.go:1099 +0x2f
runtime.startm(0xc82001f500, 0x100000001)
	/usr/local/go/src/runtime/proc1.go:1186 +0xef
runtime.wakep()
	/usr/local/go/src/runtime/proc1.go:1258 +0x59
runtime.ready(0xc846c61680, 0x3)
	/usr/local/go/src/runtime/proc1.go:149 +0x132
runtime.goready.func1()
	/usr/local/go/src/runtime/proc.go:196 +0x29
runtime.systemstack(0xc820026000)
	/usr/local/go/src/runtime/asm_amd64.s:262 +0x79
runtime.mstart()
	/usr/local/go/src/runtime/proc1.go:668

........ lots of stack...
```

And heaps and heaps of stack info... like 13MB if anyone interested.

Not sure what happened here.

Running on CoreOS.
Marathon 0.15.1
Mesos 0.26
Logging to AWS

### PR DESCRIPTION
**Pull request by skoo87**
The #2494 is bad, I can't recover it, so open a new pr.

Fix #1838 #1859
conn.File() in setTCPUserTimeout(), is root cause of the bug.

### CODE REVIEW

**Comment by allencloud** [comment]
Thanks a lot for your contribution. @skoo87 

I was wondering if we could remove these three files `utils_windows.go`, `utils_unix.go` and `utils_darwin.go`? 
WDYT? ping @dongluochen @nishanttotla

**Comment by dongluochen** [comment]
@skoo87 We have updated Go version to fix CI problem. Please rebase. Please remove the unused files. Thanks.

**Comment by dongluochen** [comment]
@skoo87 Thanks for the update. Please squash your commits.

**Comment by skoo87** [comment]
@dongluochen I have squashed the commits. Thank you.

**Comment by dongluochen** [comment]
LGTM

**Comment by allencloud** [comment]
Thanks a lot for your contribution @skoo87

**Pull request merged**
