### PR TITLE
add jenkins badge

### PR DESCRIPTION
**Pull request by MHBauer**
both jenkins and travis are set up, so I figure we might as well show both.

I looked at how it was configured in base docker and configured it the same.

### CODE REVIEW

**Comment by chanwit** [comment]
LGTM

**Comment by chanwit** [comment]
ping @abronan @jimmyxian

**Comment by chanwit** [comment]
ping @moxiegirl @thaJeztah

**Comment by thaJeztah** [comment]
I see a nice green badge, and the link works, so LGTM. Thanks @MHBauer !

**Pull request merged**
