### PR TITLE
Cleanup state folder with local file persistence

### PR DESCRIPTION
**Pull request by abronan**
Remove the `state` folder with the filestore that is not used by Mesos and of limited utility for Swarm.

/cc @aluzzardi @vieux 

Signed-off-by: Alexandre Beslic <abronan@docker.com>

### CODE REVIEW

**Comment by chanwit** [comment]
All tests passed locally with an `aufs` box. LGTM.

**Comment by vieux** [comment]
LGTM ping @aluzzardi

**Comment by vieux** [comment]
:hamster:

**Comment by aluzzardi** [comment]
LGTM

A moment of silence for `state.Store`.

**Comment by vieux** [comment]
:fallen_leaf: 
:fallen_leaf: 
:fallen_leaf:

**Comment by abronan** [comment]
:wave: :cry:

**Comment by aluzzardi** [comment]
> and now his watch is ended

**Pull request merged**
