### PR TITLE
Add support images save

### PR DESCRIPTION
**Pull request by aluzzardi**
@jimmyxian I took your PR and added a commit on top of it to simplify the code logic (your original commits are still part of this PR).

Could you take a look?

Replaces #739

### CODE REVIEW

**Comment by jimmyxian** [comment]
@aluzzardi LGTM +1 +1 +1
Great! It looks more easy for us to understand the logic.

**Comment by abronan** [comment]
LGTM

/cc @vieux

**Comment by aluzzardi** [comment]
Rebased off master to get the new Jenkins fixes

**Comment by vieux** [comment]
LGTM

**Pull request merged**
