### PR TITLE
update swarm logo

### PR DESCRIPTION
**Pull request by vieux**
Signed-off-by: Victor Vieux <victorvieux@gmail.com>

### CODE REVIEW

**Comment by abronan** [comment]
LGTM :heart_eyes:

**Comment by thaJeztah** [comment]
Looks good! Does it need the whitespace around it?

**Comment by chanwit** [comment]
LGTM :)

**Comment by MHBauer** [comment]
The whales look so happy.

**Comment by vieux** [comment]
@thaJeztah It's to center the picture

**Comment by thaJeztah** [comment]
@vieux on the README.md, or in the docs (haven't checked where it's used)

**Comment by vieux** [comment]
@thaJeztah on the Readme

**Comment by thaJeztah** [comment]
Hm, if you don't mind some HTML in the Markdown, that could be fixed with CSS, but yeah, that's probably not the cleanest solution as well. There's an extension to Markdown to support centering, unfortunately, not on GitHub ¯\_(ツ)_/¯

LGTM :)

(the logo is looking great btw!)

**Comment by jimmyxian** [comment]
LGTM :)

**Pull request merged**
