### PR TITLE
Update dockerclient

### PR DESCRIPTION
**Pull request by jimmyxian**
Update dockerclient for improving rename
Signed-off-by: Xian Chaobo <xianchaobo@huawei.com>

### CODE REVIEW

**Comment by abronan** [comment]
LGTM

/ping @vieux

**Comment by vieux** [comment]
hey @jimmyxian can you update godep at the same time you send the PR to improve rename ?

**Comment by vieux** [comment]
I updated Godeps in #667

**Comment by jimmyxian** [comment]
@vieux OK..i will close this PR

**Pull request closed without merging**
