### PR TITLE
fix network filter with global network

### LINKED ISSUE #1682: Network List API Name Filters
When requesting a list of networks from the Swarm API endpoint with a name filter, overlay networks that match the filter are not returned. The network is returned in an unfiltered list request.

### PR DESCRIPTION
**Pull request by vieux**
fix #1682 

@tacchino @chanwit can you try with patch to see if it fixes your issue ?

### CODE REVIEW

**Comment by tacchino** [comment]
@chanwit are you able to easily verify? I don't have a dev environment set up

**Comment by chanwit** [comment]
@vieux @tacchino I'm testing it. Please stay tuned.

**Comment by chanwit** [comment]
LGTM

Work great when filtering by name.

```
debian-1gb-sgp1-01:~
# docker version
Client:
 Version:      1.10.0-rc1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   677c593
 Built:        Fri Jan 15 18:21:13 2016
 OS/Arch:      linux/amd64

Server:
 Version:      swarm/1.1.0
 API version:  1.21
 Go version:   go1.5.2
 Git commit:   074df4d
 Built:        Wed Jan 27 13:02:33 UTC 2016
 OS/Arch:      linux/amd64
debian-1gb-sgp1-01:~
# docker network ls
NETWORK ID          NAME                  DRIVER
e27b1efabb40        ocean-master/bridge   bridge
d3e6d18cb9f8        ocean-master/host     host
16d90fcd2b85        ocean-1/bridge        bridge
9efa737f3066        ocean-1/none          null
4651db36f3b6        ocean-1/host          host
dd26873d7a00        multihost             overlay
b33a5b00be5d        ocean-2/bridge        bridge
bd6fd6aa0d00        ocean-2/none          null
0c52b61a3f71        ocean-2/host          host
770a253be8fc        ocean-master/none     null
debian-1gb-sgp1-01:~
# docker network ls --filter name=multihost
NETWORK ID          NAME                DRIVER
dd26873d7a00        multihost           overlay
debian-1gb-sgp1-01:~
#
```

**Comment by chanwit** [comment]
@vieux but not sure if you'd like to include `--filter type=custom` into this PR?
Or maybe in a separate one.
(Or maybe if you can point out where to tackle, I can help fix it)

```
debian-1gb-sgp1-01:~
# eval $(docker-machine env --swarm ocean-master)
debian-1gb-sgp1-01:~
# docker network ls --filter type=custom
NETWORK ID          NAME                  DRIVER
e27b1efabb40        ocean-master/bridge   bridge
16d90fcd2b85        ocean-1/bridge        bridge
4651db36f3b6        ocean-1/host          host
9efa737f3066        ocean-1/none          null
b33a5b00be5d        ocean-2/bridge        bridge
bd6fd6aa0d00        ocean-2/none          null
0c52b61a3f71        ocean-2/host          host
dd26873d7a00        multihost             overlay
770a253be8fc        ocean-master/none     null
d3e6d18cb9f8        ocean-master/host     host
debian-1gb-sgp1-01:~
# eval $(docker-machine env ocean-1)
debian-1gb-sgp1-01:~
# docker network ls --filter type=custom
NETWORK ID          NAME                DRIVER
dd26873d7a00        multihost           overlay
debian-1gb-sgp1-01:~
#
```

**Comment by vieux** [comment]
@chanwit let's handle filter in another PR

**Comment by vieux** [comment]
ping @dongluochen

**Comment by abronan** [comment]
LGTM

**Comment by dongluochen** [comment]
LGTM.

**Pull request merged**
