### PR TITLE
Issue 2134

### PR DESCRIPTION
**Pull request by ojongerius**
See #2134. 

This PR adds:
* Bool Maintenance to engine/Engine
* Methods SetMaintenance, GetMaintenance to the engine interface
* Methods EngineExists and EngineHealhty to the cluster interface
* Refactor scheduler prevent from scheduling on nodes that are under maintenance.
* Add GET "/engines/{name:.*}/state"
* Add GET "/engines/{name:.*}/maintenance"
* Add POST "/engines/{name:.*}/maintenance/start"
* Add POST "/engines/{name:.*}/maintenance/stop"
* Integration tests in test/integration/nodemanagement/maintenance_state.bats

Happy to rebase and sign my commits if we get some buy in for this work.

### CODE REVIEW

**Comment by yank1** [comment]
LGTM

**Comment by nishanttotla** [comment]
@ojongerius could you please clean up the branch so that it has only your commits and no merge commits? This is hard to review in its current form.

**Comment by ojongerius** [comment]
@nishanttotla not sure what went wrong with merging upstream into my branch. I'll get this cleaned up asap.

**Comment by ojongerius** [comment]
Closing this in favour of crispy new branch #2139 with just 3, signed, commits.

**Pull request closed without merging**
