### PR TITLE
Cleanup: cast int64 to make it works everywhere

### PR DESCRIPTION
**Pull request by chanwit**
Signed-off-by: Chanwit Kaewkasi <chanwit@gmail.com>

### CODE REVIEW

**Comment by vieux** [comment]
@chanwit where do you see tests failing without this fix ?

**Comment by chanwit** [comment]
@vieux on my ARM cluster, which is not 64-bit.

**Comment by vieux** [comment]
LGTM

**Comment by abronan** [comment]
LGTM

**Pull request merged**
