### PR TITLE
fix restart docker in tests

### LINKED ISSUE #2002: Integration tests failing on master
Most integration tests started failing around Friday (as pointed out by @dongluochen), and the error seems to be
```
# Command "docker -H 127.0.0.1:5249 info" failed 15 times. Output: Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```
It's possible that #1997 introduced new `engine-api` behavior that is causing this, because the text corresponds with `ErrConnectionFailed`. It's not clear though, since tests passed on #1997. Good news is that the client is working with manual testing, so it's likely only the integration tests need to be fixed.

Another possible culprit might be https://github.com/docker/docker/pull/20662 (as pointed out by @vieux), leading to `dind` not working.

### PR DESCRIPTION
**Pull request by vieux**
Fix #2002

### CODE REVIEW

**Comment by dongluochen** [comment]
LGTM

**Comment by abronan** [comment]
LGTM

**Comment by abronan** [comment]
:green_apple:

**Comment by vieux** [comment]
lgtm

**Comment by dongluochen** [comment]
Fix #2002.

**Comment by nishanttotla** [comment]
Nice!

**Pull request merged**
