### PR TITLE
Reformat to make it look more graceful

### PR DESCRIPTION
**Pull request by wenchma**
Signed-off-by: Wen Cheng Ma <wenchma@cn.ibm.com>

### CODE REVIEW

**Comment by dongluochen** [comment]
LGTM. Thanks @wenchma!

ping @moxiegirl

**Comment by nishanttotla** [comment]
Thanks @wenchma! Since you're reformatting, can you also use markdown for `manager0` and `consul0`?

**Comment by wenchma** [comment]
@nishanttotla  I already markdown `manger0` and `consul0`, PTAL :smile:

**Comment by moxiegirl** [comment]
@wenchma Thanks for discovering the problems and providing a fix. I found a few more and combined your change with my fixes.

**Comment by wenchma** [comment]
@moxiegirl yes, yours looks better to fix more, :+1:

**Pull request closed without merging**
