### PR TITLE
Docker changes hostname/domain in container config

### PR DESCRIPTION
**Pull request by dongluochen**
Docker changes hostname/domain in container config with [#20200](https://github.com/docker/docker/pull/20200). Update Swarm test. 
Signed-off-by: Dong Chen <dongluo.chen@docker.com>

### CODE REVIEW

**Comment by dongluochen** [comment]
Missed mesos test, updating.

**Comment by dongluochen** [comment]
ping @vieux @nishanttotla .

**Comment by vieux** [comment]
LGTM

**Comment by MHBauer** [comment]
nice. LGTM.

**Pull request merged**
