### PR TITLE
Close tcp connection when client stops '/events' request.

### PR DESCRIPTION
**Pull request by dongluochen**
It's a minor bug from #1267. 
Signed-off-by: Dong Chen <dongluo.chen@docker.com>

### CODE REVIEW

**Comment by MHBauer** [comment]
I thought it had something to do with the writer closing. I am interested in if this fixes it.

**Comment by dongluochen** [comment]
@MHBauer I think #1267 might include several issues. We will need reproduce steps to identify them. I validate this one manually.

**Comment by abronan** [comment]
LGTM

I confirm this gets rid of the issue after reproducing the steps from @riuvshin before and after this PR.

**Comment by vieux** [comment]
LGTM, thanks @dongluochen

**Pull request merged**
