### PR TITLE
Fixed #2460, go vetting warning unkeyed fields

### LINKED ISSUE #2460: Came across golang composite literal uses unkeyed fields warning. want to report it.
the go vet always report composite literal uses unkeyed fields warning, so i report here. try to fix it later.

```
$ go vet `go list ./...|grep -v /vendor/`
api/handlers.go:189: github.com/docker/swarm/cluster.ImageFilterOptions composite literal uses unkeyed fields
exit status 1
scheduler/filter/dependency_test.go:60: github.com/docker/swarm/cluster.ContainerConfig composite literal uses unkeyed fields
scheduler/filter/dependency_test.go:69: github.com/docker/swarm/cluster.ContainerConfig composite literal uses unkeyed fields
scheduler/filter/dependency_test.go:78: github.com/docker/swarm/cluster.ContainerConfig composite literal uses unkeyed fields
scheduler/filter/dependency_test.go:87: github.com/docker/swarm/cluster.ContainerConfig composite literal uses unkeyed fields
scheduler/filter/dependency_test.go:96: github.com/docker/swarm/cluster.ContainerConfig composite literal uses unkeyed fields
scheduler/filter/dependency_test.go:105: github.com/docker/swarm/cluster.ContainerConfig composite literal uses unkeyed fields
scheduler/filter/dependency_test.go:160: github.com/docker/swarm/cluster.ContainerConfig composite literal uses unkeyed fields
scheduler/filter/dependency_test.go:169: github.com/docker/swarm/cluster.ContainerConfig composite literal uses unkeyed fields
scheduler/filter/dependency_test.go:178: github.com/docker/swarm/cluster.ContainerConfig composite literal uses unkeyed fields
scheduler/filter/dependency_test.go:187: github.com/docker/swarm/cluster.ContainerConfig composite literal uses unkeyed fields
scheduler/filter/dependency_test.go:241: github.com/docker/swarm/cluster.ContainerConfig composite literal uses unkeyed fields
scheduler/filter/dependency_test.go:252: github.com/docker/swarm/cluster.ContainerConfig composite literal uses unkeyed fields
exit status 1
```

### PR DESCRIPTION
**Pull request by xiaods**
Came across golang composite literal uses unkeyed fields warning. want to
report it.

Signed-off-by: Deshi Xiao <xiaods@gmail.com>

### CODE REVIEW

**Comment by allencloud** [comment]
Actually, I like this pr.
@dongluochen @nishanttotla

**Comment by nishanttotla** [comment]
Thanks @xiaods! Do you mind force pushing again so that all the tests can run?

**Comment by xiaods** [comment]
how do the force pushing?
```
$ git push -f origin devel
Everything up-to-date
```

**Comment by dongluochen** [comment]
LGTM

**Comment by nishanttotla** [comment]
LGTM. Rescheduling test failure is unrelated, but we need to investigate it.

**Pull request merged**
