### PR TITLE
fix Switch the primary docs

### PR DESCRIPTION
**Pull request by clhlc**
HI, i fix the issue [https://github.com/docker/swarm/issues/2356](url)

### CODE REVIEW

**Comment by nishanttotla** [comment]
Fixes #2356

**Comment by nishanttotla** [comment]
Actually the doc is a little confusing, it's not clear if the last section is meant for before the failover happened. I think we should move the whole "Switch the Primary" part to before the failover case.

cc @allencloud

**Comment by dongluochen** [comment]
@nishanttotla @clhlc I think the last section `Switch the primary` should be `Switch DOCKER_HOST pointing to new primary`. We may update text to make it clear.

**Comment by clhlc** [comment]
@nishanttotla  in swarm 1.2.3，primary node info is
`...
Server Version: swarm/1.2.3
Role: primary
Strategy: spread
Filters: health, port, containerslots, dependency, affinity, constraint
...`

**Comment by abronan** [comment]
Thanks @clhlc,

LGTM

(there are definitely some changes to be made but this fixes the immediate issue which was that the message was incorrectly mentioning `replica` instead of `primary`, let's not block this one and make further changes later on if the process is still unclear)

**Pull request merged**
