### PR TITLE
Support filtering networks by id or name

### LINKED ISSUE #1316: /networks filters param is not supported
https://github.com/docker/docker/blob/master/docs/reference/api/docker_remote_api_v1.21.md#list-networks

This param is required by compose

### PR DESCRIPTION
**Pull request by dnephin**
Fixes #1316

I looked at adding an integration test but the docker-cli doesn't support this filtering yet.

### CODE REVIEW

**Comment by dnephin** [comment]
test failures seems unrelated

**Comment by vieux** [comment]
LGTM

**Comment by vieux** [comment]
ping @dongluochen @abronan

**Comment by abronan** [comment]
LGTM

**Comment by dnephin** [comment]
Will this make it into 1.0.0 ?

We need it for compose compatibility

**Comment by abronan** [comment]
@dnephin It will be in the RC2 and then `1.0.0` yes.

**Pull request merged**
