### PR TITLE
Adding Drew Erny to maintainers list

### PR DESCRIPTION
**Pull request by dani-docker**
Drew has been the rock star maintainer of swarmkit, adding him to help maintaining swarm.
Welcome Drew!
cc: @dperny @thaJeztah 
Signed-off-by: Dani Louca <dani.louca@docker.com>

### CODE REVIEW

**Comment by raghavav** [comment]
LGTM

**Comment by andrewhsu** [comment]
LGTM

**Comment by andrewhsu** [comment]
nitpick (not blocker for merging) spacing is kinda weird

**Comment by dperny** [comment]
LGTM lol

**Comment by thaJeztah** [comment]
Let's merge this

**Pull request merged**
