### PR TITLE
etcd Integration test

### PR DESCRIPTION
**Pull request by snrism**
Similar to other discovery service, this PR addresses the integration test for etcd discovery please refer to https://github.com/docker/swarm/issues/644

### CODE REVIEW

**Comment by snrism** [comment]
@aluzzardi  In the `check_leader` function, I wanted to check if leader changed to swarm_etcd in the logs, but when I look into the logs, the $CONTAINER NAME is not picked up in the logs, rather only displays the container_id. Please refer to the last line in the following etcd log.

[etcd] May 11 18:44:37.652 WARNING   | Using the directory d50bb34a126b.etcd as the etcd curation directory because a directory was not specified.
[etcd] May 11 18:44:37.654 INFO      | d50bb34a126b is starting a new cluster
[etcd] May 11 18:44:37.662 INFO      | etcd server [name d50bb34a126b, listen on :4001, advertised url http://127.0.0.1:4001]
[etcd] May 11 18:44:37.663 INFO      | peer server [name d50bb34a126b, listen on :7001, advertised url http://127.0.0.1:7001]
[etcd] May 11 18:44:37.663 INFO      | d50bb34a126b starting in peer mode
[etcd] May 11 18:44:37.664 INFO      | d50bb34a126b: state changed from 'initialized' to 'follower'.
[etcd] May 11 18:44:37.665 INFO      | d50bb34a126b: state changed from 'follower' to 'leader'.
[etcd] May 11 18:44:37.665 INFO      | d50bb34a126b: leader changed from '' to 'd50bb34a126b'.

If we need to check for the leader change as well, then one way to do this is either use `docker_host ps` or `inspect` to get the Container ID and then use that to check as follows: 

docker_host logs $CONTAINER_NAME | grep "leader changed from '' to 'd50bb34a126b'"

Any thoughts?

**Comment by aluzzardi** [comment]
@snrism Thanks for your work.

I think just checking `leader changed from '' to` should be enough, right? We only have one leader.

**Comment by aluzzardi** [comment]
If on the other hand we really need the ID, then this should work:

```bash
function start_etcd() {
	id=$(docker_host run -p $ETCD_HOST:4001 --name=$CONTAINER_NAME -d coreos/etcd)
	# Check if etcd cluster leader is elected
	retry 30 1 check_leader $id
}

function check_leader {
    # "$1" is our leader container ID
}
```

**Comment by aluzzardi** [comment]
Let me know if you think it's required - if it works without that, then it's alright.

**Comment by snrism** [comment]
@aluzzardi thanks for the code snippet. I did think about that, but the container ID returned is the entire ID, while the etcd log gives the truncated one. I guess checking for `leader changed from '' to` should be fine since we only have one leader. Updated the code in the latest version.

**Comment by aluzzardi** [comment]
LGTM

Thanks a lot!

**Pull request merged**
