### PR TITLE
Initialize the key/directory before watching on kv discovery

### PR DESCRIPTION
**Pull request by abronan**
Before that change, etcd and zookeeper would fail to instantiate
the discovery without the key being already there in the store or
created beforehand and implicitely by a 'swarm join'.

Signed-off-by: Alexandre Beslic <abronan@docker.com>

### CODE REVIEW

**Comment by MHBauer** [comment]
Makes sense to me. I think you should be able to start join and manage in any order.

Unit test needs help with a mock of the new function.

**Comment by abronan** [comment]
@MHBauer Thanks for reviewing, yes forgot about the Mock.. the usual :smile:

**Comment by abronan** [comment]
I had to cheat with `testify` or it keeps the latest signature and throws a method mismatch error if done the right way...

On the other hand CI failures seems to be unrelated now.

**Comment by vieux** [comment]
@abronan can you try with

```diff
diff discovery/kv/kv_test.go gofmt/discovery/kv/kv_test.go
--- /tmp/gofmt363354986	2015-10-08 18:07:21.910441239 -0700
+++ /tmp/gofmt472320449	2015-10-08 18:07:21.910441239 -0700
@@ -92,7 +92,7 @@
 	assert.EqualError(t, <-errCh, "test error")
 	// We have to drain the error channel otherwise Watch will get stuck.
 	go func() {
-		for _ = range errCh {
+		for range errCh {
 		}
 	}()

```

**Comment by abronan** [comment]
Well, apparently that did the trick for `go fmt`.. :+1:

**Comment by abronan** [comment]
PTAL, errors in Jenkins are unrelated.

**Comment by vieux** [comment]
LGTM

**Pull request merged**
