### PR TITLE
add a reschedule test with compose

### PR DESCRIPTION
**Pull request by vieux**
Signed-off-by: Victor Vieux <vieux@docker.com>

### CODE REVIEW

**Comment by abronan** [comment]
LGTM

**Comment by vieux** [comment]
unrelated zk failure: https://github.com/docker/swarm/pull/1841

**Comment by abronan** [comment]
@vieux yeah it's weird, seems to be failing only with engine master. We can probably merge #1841 in the meantime.

**Comment by vieux** [comment]
ping @dongluochen @nishanttotla

**Comment by nishanttotla** [comment]
LGTM

**Pull request merged**
