### PR TITLE
[DOCS] Typo in scheduler/filter.md

### PR DESCRIPTION
**Pull request by LukasBacigal**
Link to the correct id #use-a-dependency-filter

### CODE REVIEW

**Comment by LukasBacigal** [comment]
Is it necessary to build for change in documentation? I think docker/docker doesn't

**Comment by dongluochen** [comment]
@LukasBacigal Thanks for the change. The document branch is not in sync with main branch. 

@SvenDowideit How should we resolve this?

**Comment by LukasBacigal** [comment]
I can close this and do it on main branch.

**Comment by dongluochen** [comment]
@LukasBacigal I think it's on our side.

**Comment by sfsmithcha** [comment]
@LukasBacigal , @dongluochen , this needs to go in to `master`, then either @SvenDowideit or I can make sure that it makes it into the docs build.

**Comment by SvenDowideit** [comment]
sorry - missed this ping, yup, @sfsmithcha is correct, changes need to go into `master`, and then we bring them into docs later.

**Comment by allencloud** [comment]
@LukasBacigal 
The Travis CI failed. Can you rebase the code  to the master?

LGTM, if the travis CI works.

**Comment by LukasBacigal** [comment]
Tbh, I don't know how or if it is possible. I can make new PR onto master, but :cry: 
kitty died for my sins. Is that what you meant?

**Comment by allencloud** [comment]
LukasBacigal  wants to merge 1 commit into **docker:docs** from LukasBacigal:patch-1

You can change  into **master** from your branch.

And I think you should submit a new PR to finish this. As long as you finish a PR to master, we can close this PR then.

@LukasBacigal

**Comment by SvenDowideit** [comment]
@LukasBacigal yes, please make a new PR and close this one :)

**Comment by LukasBacigal** [comment]
Totally forgot will look onto that today.

Dňa ut, 21. jún 2016 13:22 Sven Dowideit <notifications@github.com>
napísal(a):

**Comment by LukasBacigal** [comment]
Rebased onto master @ #2369.

**Pull request closed without merging**
