### PR TITLE
Add Plugin code from docker 

### PR DESCRIPTION
**Pull request by doronp**
Fulfill  #1593
Signed-off-by: Doron Podoleanu <doronp@il.ibm.com>

### CODE REVIEW

**Comment by doronp** [comment]
go test -v -race ./... is successful locally, Can you please advice why it is failing ?
Thanks
ping @docker/swarm-maintainers

**Comment by abronan** [comment]
@doronp sorry for the delay, It seems that there was something wrong with a rebase, some of your commits are interleaved with other commits that were included in the meantime :disappointed: 

For the CI, it seems that this is a dependency error and it cannot find a package, but I think that fixing that rebase issue should do the trick.

**Comment by doronp** [comment]
@abronan See:
https://github.com/docker/swarm/pull/1646
(Fresh clone and PR gets the same result after fixing the first two missing libs)

**Comment by doronp** [comment]
Continue on #1646

**Pull request closed without merging**
