### PR TITLE
update dockerclient to get labels on volumes, networks, etc...

### PR DESCRIPTION
**Pull request by vieux**
Signed-off-by: Victor Vieux <vieux@docker.com>

### CODE REVIEW

**Comment by vieux** [comment]
ping @dongluochen

**Comment by dongluochen** [comment]
LGTM. 

Test is broken, but not related to this change. 
```
not ok 24 leader election - rescheduling
# (from function `retry' in file ./helpers.bash, line 80,
#  in test file ./replication.bats, line 137)
#   `retry 5 1 containerRunning "c1" "node-1"' failed
```

**Comment by vieux** [comment]
@dongluochen I'm going to investigate

**Comment by abronan** [comment]
LGTM

**Pull request merged**
