### PR TITLE
Fix: deepcopy event to avoid concurrency problem

### PR DESCRIPTION
**Pull request by Azure22**
We currently encountered a panic reading from event.Actor.Attributes. The reason is because when swarm API handles the event it writes on it at the same time. To avoid this panic due to concurrent reading and writing on the map, a deep copy of the event is necessary.

Signed-off-by: xi.han <xi.han@sihuatech.com>

### CODE REVIEW

**Comment by nishanttotla** [comment]
@Azure22 CI is failing. Can you take a look?

**Comment by Azure22** [comment]
@nishanttotla Corrected the problem. Thanks!

**Comment by nishanttotla** [comment]
@Azure22 thanks for the work on this. I agree that there is a race condition here that must be fixed. In https://github.com/docker/swarm/pull/2747, we are restructuring the way events are handled, and I think the race condition will be fixed as part of that PR, which is urgently slated for the next release. If it fixes your panic, great. If not, we'll work to get this PR in as well.

**Comment by nishanttotla** [comment]
@Azure22 please let me know if your issue is now fixed in master.

**Comment by allencloud** [comment]
I am afraid this needs a rebase, @Azure22

**Comment by Azure22** [comment]
@nishanttotla @allencloud Current one is good enough for my issue. Thanks guys.

**Comment by nishanttotla** [comment]
@Azure22 thanks for the update, and for your contribution 😄

**Pull request closed without merging**
