### PR TITLE
update consul api

### PR DESCRIPTION
**Pull request by suryagaddipati**
This is a redo of https://github.com/docker/swarm/pull/1434 

I had to include https://github.com/docker/swarm/pull/1558 for `godep update` to work

### CODE REVIEW

**Comment by vieux** [comment]
we merged #1558 can you please rebase your PR ?

thanks.

**Comment by suryagaddipati** [comment]
thanks done @vieux

**Comment by abronan** [comment]
@suryagaddipati Oh! I was confused in the other PR (#1434 /cc @ch3lo) but apparently Consul API `0.6.0` **needs** `go-cleanhttp` and `serf/coordinate`. Can you add those dependencies as well and update Godep accordingly? Thanks!

**Comment by suryagaddipati** [comment]
@abronan will do. i just checked to see if  `godep go install . ` works before submitting this pr.

**Comment by suryagaddipati** [comment]
@abronan do you know if doing `go get .` to install missing deps is the right solution here ? Seems to have worked on travisci. 

Sorry new to golang.

**Comment by abronan** [comment]
@suryagaddipati I think that the only thing you need to do is `godep update github.com/hashicorp/consul` and this will also update `Godeps.json` with `go-cleanhttp` and `serf/coordinate` as a result.

**But first**: make sure you do a `go get -u github.com/hashicorp/consul` to grab all the dependencies as well.

**Comment by suryagaddipati** [comment]
@abronan this is what i get on current master 
```
 swarm$ g show head --name-only
commit 8c5b47b52773a64934ff7e618dafcd9471d76eb5

swarm$ go get -u github.com/hashicorp/consul
swarm$  godep update github.com/hashicorp/consul
godep: not in manifest: github.com/hashicorp/consul
godep: no packages can be updated
```

**Comment by abronan** [comment]
@suryagaddipati My bad, it should probably be `godep update github.com/hashicorp/consul/api`

**Comment by suryagaddipati** [comment]
hi @abronan doing  ` godep update github.com/hashicorp/consul/api` doesn't add `serf/coordinate` to `Godeps.json` . Just updates the version of `consul/api` like in the original PR. 

What are your thoughts on just doing `go get .` in `.travis.yml` like in this PR.

**Comment by vieux** [comment]
@suryagaddipati no we shouldn't use go get. the whole point of godep is to not use go get.

If tomorrow `serf/coordinate` get's removed from github for some reason, it won't work anymore.

**Comment by vieux** [comment]
Closing as it was updated #1589

**Pull request closed without merging**
