### PR TITLE
Fix all api tests which do not need to use "run"

### PR DESCRIPTION
**Pull request by jimmyxian**
Signed-off-by: Xian Chaobo <xianchaobo@huawei.com>

### CODE REVIEW

**Comment by jimmyxian** [comment]
ping @aluzzardi @vieux

**Comment by aluzzardi** [comment]
I just don't understand what's happening. I restarted jenkins 3 times and it still fails.

It doesn't seem to be related to this PR, but still?

**Comment by aluzzardi** [comment]
Thanks @jimmyxian for this, it's very helpful.

I'll check tomorrow and see what's wrong with jenkins

**Comment by aluzzardi** [comment]
LGTM

**Pull request merged**
