### PR TITLE
fix #927 check pull status code

### LINKED ISSUE #927: FATA[0000] Error response from daemon: invalid character 'I' looking for beginning of value
Getting this error while executing following command:
```
docker -H 192.168.34.7:2376 run --name my_container 4e8aa3148a132f19ec560952231c4d39522043994df7d2dc239942c0f9424ebd ip route list
```
Specified image exists on certain node only in the cluster (I've committed container from previous run). But seems swarm is unable to locate that node and run container there.
Anyways error message is misleading.

### PR DESCRIPTION
**Pull request by jimmyxian**
Fix: #927 
Signed-off-by: Xian Chaobo <xianchaobo@huawei.com>

### CODE REVIEW

**Comment by jimmyxian** [comment]
There are something wrong with dockerclient.go. I will fix it first. Then update this PR

**Comment by jimmyxian** [comment]
ping @vieux  @aluzzardi  @marc-

**Comment by aluzzardi** [comment]
LGTM

**Comment by vieux** [comment]
LGTM

**Pull request merged**
