### PR TITLE
Use os.Unsetenv in options_test

### PR DESCRIPTION
**Pull request by ahmetalpbalkan**
Go 1.4 introduced os.Unsetenv, also added errchecks for os.Setenv

Signed-off-by: Ahmet Alp Balkan

### CODE REVIEW

**Comment by ahmetalpbalkan** [comment]
apparently the build system still uses go1.3, will leave this here until it is bumped to 1.4.

**Comment by abronan** [comment]
I'd really like to see this merged and bump the version to go 1.4 for Godep at the same time. Thoughts? @aluzzardi @vieux

**Comment by vieux** [comment]
@ahmetalpbalkan can you please rebase your PR, travis errors out.

**Comment by ahmetalpbalkan** [comment]
Done

**Comment by abronan** [comment]
LGTM

**Comment by vieux** [comment]
LGTM

**Pull request merged**
