### PR TITLE
do not lower keys

### PR DESCRIPTION
**Pull request by vieux**
Fix https://github.com/docker/swarm/issues/1795

### CODE REVIEW

**Comment by vieux** [comment]
ping @chanwit any idea why we used `ToLower` ?

**Comment by dongluochen** [comment]
LGTM

**Comment by nishanttotla** [comment]
@vieux @chanwit Looking at the file's history, it seems like `ToLower` has been around for a while.

**Comment by vieux** [comment]
yes

On Thu, Feb 11, 2016 at 1:46 PM, Nishant Totla <notifications@github.com>
wrote:

> @vieux <https://github.com/vieux> @chanwit <https://github.com/chanwit>
> Looking at the file's history, it seems like ToLower has been around for
> a while.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docker/swarm/pull/1800#issuecomment-183070659>.
>



-- 
Victor Vieux
Docker Core Engineer
vieux@docker.com

**Comment by MHBauer** [comment]
Was there a limit on what the constraints could be at one point? Earliest valid matching code looks like 4726477dbe1dd5ac3a7eee6430aee2f54f516b50.

**Comment by chanwit** [comment]
It's started by having `node` and all other labels in lower cases. A bad design of me :(

Removal is just fine.

LGTM

**Comment by nishanttotla** [comment]
LGTM

(test failure seems unrelated)

**Pull request merged**
