### PR TITLE
add plugins PLEASE DO NOT REVIEW BEFORE looking at the other version at #1366  

### PR DESCRIPTION
**Pull request by doronp**
This also address (by importing packages from docker)#1593

### CODE REVIEW

**Comment by doronp** [comment]
@abronan 

I have the next commit (AuthZ plugin infra based on this generic plugin infra) ready and passing race -v test locally and here:

https://github.com/doronp/swarm/tree/authZPlugin

That commit should conclude AuthZ plugin support for Swarm (will be like in docker)

I think We should first resolve the test issue here before I push it.

**Comment by doronp** [comment]
ping @abronan

**Comment by doronp** [comment]
version with importing the generic plugin and duplicating the authz plugin available at #1366

**Comment by abronan** [comment]
ping @docker/swarm-maintainers

**Comment by doronp** [comment]
Will continue with #1366

**Pull request closed without merging**
