### PR TITLE
Cleaning up ROADMAP.md

### LINKED ISSUE #1799: Remove ROADMAP.md file
This file is extremely outdated, and the current roadmap is tracked using the Wiki. I don't think we should confuse users.

WDYT @vieux @dongluochen @amitshukla?

### PR DESCRIPTION
**Pull request by nishanttotla**
Fixes #1799. The ROADMAP.md file at the root of the project should be better. Since we track goals and checkpoints in the wiki, it makes sense to link to it. We could also duplicate the list of goals for the upcoming release, suggestions invited.

Signed-off-by: Nishant Totla nishanttotla@gmail.com

### CODE REVIEW

**Comment by vieux** [comment]
@nishanttotla I would like the main wiki page, otherwise this file will become outdated at some point.

**Comment by nishanttotla** [comment]
@vieux Unless we keep updating it? I'm fine either way, as long as we all agree.

Also ping @dongluochen @amitshukla @mgoelzer

**Comment by dongluochen** [comment]
@nishanttotla Thanks for bringing it up. I think ROADMAP.md should be a long term plan. Pointing it to next release plan may not be appropriate. I think we should update it based on recent proposal areas.

**Comment by mstanleyjones** [comment]
What's the status on this? It specifically say DO NOT MERGE and has not been worked on since Feb.

**Comment by nishanttotla** [comment]
@mstanleyjones this PR got forgotten about in time. I still think it is relevant, I'll update it and we'll merge it in.

**Comment by nishanttotla** [comment]
This PR will also address #2731, and should be merged immediately after 1.2.7 is released.

**Pull request merged**
