### PR TITLE
mitigate race in pull while we wait for a proper store

### PR DESCRIPTION
**Pull request by vieux**
Signed-off-by: Victor Vieux <vieux@docker.com>

### CODE REVIEW

**Comment by abronan** [comment]
LGTM

**Comment by abronan** [comment]
ping @aluzzardi

**Comment by chanwit** [comment]
Wow, we've got a new maintainer @abronan on board?
I am so glad to have more man-powers for code reviews, so my PRs could get merged faster :)

**Comment by aluzzardi** [comment]
Could you add a //FIXME or //TODO?

This is hack-ish but I know there's no other way around for now.

Other than that, LGTM

**Comment by aluzzardi** [comment]
Ohhh - actually, silly request: I see the code coverage decreased with this PR.

I'd like eventually to force all PRs to never decrease the coverage: do you think you could be able to do that as a test with this one?

You could possibly rely on mocks and return different data during the different calls.

It may be overkill though - it's up to you :)

**Pull request merged**
