### PR TITLE
update to go 1.5.4

### PR DESCRIPTION
**Pull request by vieux**
Signed-off-by: Victor Vieux <vieux@docker.com>

### CODE REVIEW

**Comment by vieux** [comment]
ping @docker/core-swarm-maintainers

**Comment by dongluochen** [comment]
LGTM

**Comment by chanwit** [comment]
LGTM

eagerly waiting for all test to be green !!

**Comment by nishanttotla** [comment]
LGTM

**Comment by vieux** [comment]
@chanwit your wish has been granted :)

**Pull request merged**
