### PR TITLE
update dockerclient & stretchr & add 'docker run --add-host' param

### PR DESCRIPTION
**Pull request by lokikiller**
update the dependency "dockerclient and strrtchr" and supported "docker run --add-host param"

### CODE REVIEW

**Comment by chanwit** [comment]
Hi @lokikiller I think you miss something :) When update the dependencies, the json file of Godeps should be changed and be a part of the commit too.

**Comment by aluzzardi** [comment]
Indeed!

`godep` is not very straightforward to use.

Anyway: One should **never** touch `Godeps/` manually.

In order to update `dockerclient` for instance, you should do something like:

```
go get -u github.com/samalba/dockerclient
godep update github.com/samalba/dockerclient
```

This should take care of updating both `Godeps/Godeps.json` and `Godeps/_workspace`

Maybe we should write something about that in the contributing docs.

@chanwit @jimmyxian thoughts?

**Comment by chanwit** [comment]
@aluzzardi it's partially there in:
https://github.com/docker/swarm/blob/master/CONTRIBUTING.md

I'll update the doc accordingly.

**Comment by jimmyxian** [comment]
@aluzzardi @chanwit 
Yeah.. Also, I think we should add some guidelines in Godeps/Readme

**Comment by vieux** [comment]
I'm closing this one, please ping us when you are ready and we will reopen.

**Pull request closed without merging**
