### PR TITLE
Remove /containers/ps from the api router

### PR DESCRIPTION
**Pull request by HackToday**
Docker itself have removed this api since 1.9.0, so it should same
for swarm to remove this old api.

Signed-off-by: Kai Qiang Wu(Kennan) <wkqwu@cn.ibm.com>

### CODE REVIEW

**Comment by vieux** [comment]
@HackToday swarm still supports docker 1.6.x so let's not remove it for now.

**Comment by HackToday** [comment]
Thanks @vieux  
One question about, where can find which version is supported in swarm ?

**Comment by vieux** [comment]
@HackToday here: https://github.com/docker/swarm/blob/master/cluster/engine.go#L33

**Comment by HackToday** [comment]
Thanks. I expected we could find it on our official docs, 
IMO just found it in code seems not good idea :0

**Pull request closed without merging**
