### PR TITLE
Give up leadership when manager shuts down

### PR DESCRIPTION
**Pull request by wsong**
Signed-off-by: Wayne Song <wsong@docker.com>

### CODE REVIEW

**Comment by nishanttotla** [comment]
Several more mesos tests are failing in this one on `engine-master`, even though some of those are failing on all new PRs.

cc @dongluochen

**Comment by wsong** [comment]
The test failures appear to be of the form "Failed to validate pending node: Error reading remote info: json: cannot unmarshal object into Go value of type string" Addr="127.0.0.1:5202"

This is a backwards incompatibility issue in the engine:

https://github.com/docker/docker/issues/28113

The fix would be to use v1.24 or earlier when making engine-api requests. Probably not relevant to this change, per se.

**Comment by nishanttotla** [comment]
@wsong right, thanks for the info. The code seems good on a first look. Have you tested this change thoroughly?

**Comment by wsong** [comment]
I tested this out manually and Swarm seemed to be able to shut down and come back up properly; it was also able to survive being killed and then restarting.

**Comment by wsong** [comment]
Does this PR still look reasonable? As mentioned above, the test failures appear unrelated.

**Comment by dongluochen** [comment]
LGTM

**Comment by nishanttotla** [comment]
LGTM

**Pull request merged**
