### PR TITLE
DO NOT MERGERT - fix-integration-test

### PR DESCRIPTION
**Pull request by jimmyxian**
Signed-off-by: Xian Chaobo <xianchaobo@huawei.com>

### CODE REVIEW

**Comment by jimmyxian** [comment]
ping @aluzzardi @abronan @vieux 
I have found that `file` cmd can not be found in `dockerswarm/swarm-test-env`.
`impot / export / save` integration test use `file` cmd to check tar file.
Have any good idea to solve this?

**Comment by vieux** [comment]
@jimmyxian it's my fault I'm going to correct this asap !!!

**Comment by jimmyxian** [comment]
@vieux :)

**Comment by abronan** [comment]
replaced by #1349 

Thanks a lot @jimmyxian for investigating :)

**Pull request closed without merging**
