### PR TITLE
Fix name of private key in configure-tls guide

### PR DESCRIPTION
**Pull request by RangerMauve**
Fixes https://github.com/docker/docker/issues/25823

### CODE REVIEW

**Comment by thaJeztah** [comment]
LGTM, thanks!

ping @sfsmithcha @cpuguy83 PTAL

**Comment by sfsmithcha** [comment]
LGTM.

**Comment by RangerMauve** [comment]
Awesome!

**Comment by thaJeztah** [comment]
Thank _you_ for catching this @RangerMauve, thanks for contributing, it's appreciated!

**Comment by RangerMauve** [comment]
Glad to help! Hopefully I'll find more little things like this in the future.

**Comment by thaJeztah** [comment]
Looking forward to it!

**Pull request merged**
