### PR TITLE
WIP. Request for review. Fixed some formatting issues and updated a link.

### PR DESCRIPTION
**Pull request by rolfedh**
Signed-off-by: Rolfe Dlugy-Hegwer rolfedh@gmail.com

### CODE REVIEW

**Comment by rolfedh** [comment]
@moxiegirl I noticed and fixed a formatting issue that was hiding some content and displaying other content incorrectly.

**Comment by nishanttotla** [comment]
LGTM

**Comment by abronan** [comment]
LGTM

ping @moxiegirl for the merge :)

**Comment by thaJeztah** [comment]
Oh, I think this needs a rebase, because my changes were merged, most things seem to be in there as well, apart from the changed Link https://github.com/docker/swarm/pull/1845/files

**Comment by abronan** [comment]
ping @rolfedh sorry for the trouble, this indeed needs a rebase.

**Comment by rolfedh** [comment]
@thaJeztah , If you used `make docs` to review your changes and saw that
the formatting issue was fixed, we can close my PR.  In the old version,
the formatting/content goes bad just below "CLI usage example using
username/password:"

Otherwise, if it is still broken, maybe you or @abronan could have someone
resolve it. I've had no luck resolving these types of conflicts in GitHub,
so I'm reluctant to take it on.

Thanks,

Rolfe

**Comment by nishanttotla** [comment]
Closing since docs have moved since.

**Pull request closed without merging**
