### PR TITLE
Update targets in Makefile

### PR DESCRIPTION
**Pull request by yuexiao-wang**
Update targets in Makefile

Signed-off-by: yuexiao-wang wang.yuexiao@zte.com.cn

### CODE REVIEW

**Comment by xiaods** [comment]
+1

**Comment by nishanttotla** [comment]
@yuexiao-wang can you please force push once, so that all tests can run?

**Comment by yuexiao-wang** [comment]
@nishanttotla PTAL
Thanks!

**Comment by nishanttotla** [comment]
@yuexiao-wang sorry this needs another rebase.

**Pull request closed without merging**
