### PR TITLE
fix possible data race with failure count

### PR DESCRIPTION
**Pull request by vieux**
Signed-off-by: Victor Vieux <vieux@docker.com>

### CODE REVIEW

**Comment by vieux** [comment]
ping @dongluochen

**Comment by dongluochen** [comment]
Line 388: 
```
     log.WithFields(log.Fields{"name": e.Name, "id": e.ID}).Infof("Engine came back to life after %d retries. Hooray!", e.failureCount)
```

**Comment by vieux** [comment]
@dongluochen PTAL

**Comment by dongluochen** [comment]
LGTM

**Comment by abronan** [comment]
LGTM

**Pull request merged**
