### PR TITLE
Edit docs/discovery.md

### PR DESCRIPTION
**Pull request by NanXiao**
Since only one "<node_ip>" is invisible in Markdown file, use "
node IP address" instead.

Signed-off-by: NanXiao <nan@chinadtrace.org>

### CODE REVIEW

**Comment by jimmyxian** [comment]
@NanXiao Good Catch!
But I think we can use \\\<node_ip\\>  instead

**Comment by NanXiao** [comment]
@jimmyxian Yes, we can use slash. I just read "`The node IP address ...`" at the beginning of the `discovery.md`, so I think maybe we should use the same words. Anyway, if you think ` \<node_ip\>` better, it is also OK. :-)

**Comment by NanXiao** [comment]
@jimmyxian 

For https://github.com/docker/swarm/pull/2342/commits/04b8fa8f1d7ccd82fa28cd3dfabd1c8c3a39c8fc, if you prefer `\<node_ip\>`, I can modify it.

For https://github.com/docker/swarm/pull/2342/commits/bccf8c5f6454e9d1c84495f65380410483117a50, could you help to review it? Thanks very much in advance!

**Comment by xiaods** [comment]
how about update?

**Comment by jimmyxian** [comment]
@NanXiao Thanks for the contribution.
Can you make a another PR about `Check whether channel is closed in monitorDiscovery`.
That will be good.:)

**Comment by NanXiao** [comment]
@jimmyxian 
Thanks for your reply!

According to your suggestion, a new PR #2370 is created. Please help to review it, thanks very much!

**Comment by jimmyxian** [comment]
LGTM

**Pull request merged**
