### PR TITLE
Implement  'docker commit' api

### PR DESCRIPTION
**Pull request by jimmyxian**
Implement  'docker commit' api (https://github.com/docker/swarm/issues/533)

Signed-off-by: Xian Chaobo <xianchaobo@huawei.com>

### CODE REVIEW

**Comment by vieux** [comment]
@jimmyxian can you also update `api/README.md` ?

**Comment by vieux** [comment]
and check gofmt

**Comment by jimmyxian** [comment]
@vieux  OK

**Comment by jimmyxian** [comment]
@vieux Done

**Comment by abronan** [comment]
LGTM

**Comment by vieux** [comment]
LGTM

**Pull request merged**
