### PR TITLE
remove BETA from docs

### PR DESCRIPTION
**Pull request by vieux**
We feel like 0.5 will be stable enough to be used in production,
therefore we are removing all the BETA notes from the docs.

@docker/swarm-maintainers @shykes what do you think ?

### CODE REVIEW

**Comment by samalba** [comment]
LGTM

**Comment by moxiegirl** [comment]
LGTM Vieux!

**Comment by abronan** [comment]
LGTM

**Comment by chanwit** [comment]
LGTM

**Comment by bfirsh** [comment]
:star2: :star2: :star2: :+1: :star2: :star2: :star2:

**Comment by thaJeztah** [comment]
Great! Would this warrant a bump to 1.0? Anything below 1.0 could still be considered "unstable" to users, even though the "beta" warning is removed

**Comment by aluzzardi** [comment]
LGTM

**Comment by jimmyxian** [comment]
LGTM

**Pull request merged**
