### PR TITLE
store: Zookeeper cas and consistent errors on failure

### PR DESCRIPTION
**Pull request by abronan**
Add Compare and Swap for Zookeeper.

Tested primitively using:

```go
package main

import (
	log "github.com/Sirupsen/logrus"
	"github.com/docker/swarm/pkg/store"
)

func main() {
	store, err := store.NewStore(store.ZK, []string{"localhost:2181"}, nil)
	if err != nil {
		log.Fatal(nil)
	}

	err = store.Put("hello", []byte("world"), nil)
	if err != nil {
		log.Fatal(err)
	}

	pair, err := store.Get("hello")
	if err != nil {
		log.Error("Get error: ", err)
	}

	// This CAS should succeed
	success, _, err := store.AtomicPut("hello", []byte("WORLD"), pair, nil)
	if err != nil {
		log.Info("CAS failed: ", err)
	}

	if success {
		log.Info("CAS succeeded")
	}

	// This CAS should fail
	pair.LastIndex = 0
	success, _, err = store.AtomicPut("hello", []byte("WORLDWORLD"), pair, nil)
	if err != nil {
		log.Info("CAS failed: ", err)
	}

	if success {
		log.Info("CAS succeeded")
	}
}
```

### CODE REVIEW

**Comment by chanwit** [comment]
@abronan can I use the current set of integration tests to verify this PR?

**Comment by abronan** [comment]
@chanwit That would be awesome! Thanks.

**Comment by chanwit** [comment]
Things look good locally as all tests passed.
```
80 tests, 0 failures, 5 skipped

real    8m32.544s
user    0m51.200s
sys     1m29.791s

```

**Comment by vieux** [comment]
LGTM

**Pull request merged**
