### PR TITLE
Issue #500 Run golint on codebase

### LINKED ISSUE #499: Add automated golint on pull requests
**Problem**

Automated golint on pull requests

**Solution**

Add golint to travis.yml

### PR DESCRIPTION
**Pull request by technolo-g**
This changeset should have TravisCI run golint on each PR. 
Submitting the PR to trigger Travis (is there a better way?)

### CODE REVIEW

**Comment by vieux** [comment]
@technolo-g can you update the code as well so golint doesn't output any error ? (I know it's a big task)

**Comment by technolo-g** [comment]
As discussed in person, Issue #500 will take care of that.

**Comment by aluzzardi** [comment]
Thanks @technolo-g !

As @vieux mentioned, we have to fix the linting of the code before merging this, otherwise all PRs will fail.

**Comment by technolo-g** [comment]
@vieux @aluzzardi sorry for all the force pushes; I'm still working on my goflow :) Anyways, this commit should both enable blocking golint (with a min_confidence of 1 setting) and fix the existing lint violations.

**Comment by technolo-g** [comment]
Also, I wanted to note that I have set min_confidence=1 in order to skip some of the suggestions by golint on this first increment. Currently, the errors that will be ignored are the following:
```
api/events.go:19:25: exported func NewEventsHandler returns unexported type *api.eventsHandler, which can be annoying to use
cluster/swarm/node.go:26:52: exported func NewNode returns unexported type *swarm.node, which can be annoying to use
discovery/discovery.go:35:6: type name will be used as discovery.DiscoveryService by other packages, and that stutters; consider calling this Service
discovery/generator.go:28:2: can probably use "var result []string" instead
discovery/consul/consul.go:15:6: type name will be used as consul.ConsulDiscoveryService by other packages, and that stutters; consider calling this DiscoveryService
discovery/etcd/etcd.go:14:6: type name will be used as etcd.EtcdDiscoveryService by other packages, and that stutters; consider calling this DiscoveryService
discovery/file/file.go:12:6: type name will be used as file.FileDiscoveryService by other packages, and that stutters; consider calling this DiscoveryService
discovery/file/file.go:29:2: can probably use "var result []string" instead
discovery/nodes/nodes.go:10:6: type name will be used as nodes.NodesDiscoveryService by other packages, and that stutters; consider calling this DiscoveryService
discovery/token/token.go:19:6: type name will be used as token.TokenDiscoveryService by other packages, and that stutters; consider calling this DiscoveryService
scheduler/filter/port_test.go:246:5: struct field IpAddress should be IPAddress
scheduler/filter/port_test.go:247:5: struct field IpPrefixLen should be IPPrefixLen
```

In particular, the last two errors cannot be blocking as they test something externally that uses those variable names. The rest of the errors were above my capabilities this time, so perhaps a second increment can fix them? Just some background on what I was thinking and why I set that setting.

**Comment by aluzzardi** [comment]
```
api/events.go:19:25: exported func NewEventsHandler returns unexported type *api.eventsHandler, which can be annoying to use
```

@vieux: Should this be api.EventsHandler or newEventsHandler?

```
cluster/swarm/node.go:26:52: exported func NewNode returns unexported type *swarm.node, which can be annoying to use
```

@vieux: Same

```
discovery/discovery.go:35:6: type name will be used as discovery.DiscoveryService by other packages, and that stutters; consider calling this Service
discovery/consul/consul.go:15:6: type name will be used as consul.ConsulDiscoveryService by other packages, and that stutters; consider calling this DiscoveryService
discovery/etcd/etcd.go:14:6: type name will be used as etcd.EtcdDiscoveryService by other packages, and that stutters; consider calling this DiscoveryService
discovery/file/file.go:12:6: type name will be used as file.FileDiscoveryService by other packages, and that stutters; consider calling this DiscoveryService
discovery/nodes/nodes.go:10:6: type name will be used as nodes.NodesDiscoveryService by other 
packages, and that stutters; consider calling this DiscoveryService
discovery/token/token.go:19:6: type name will be used as token.TokenDiscoveryService by other packages, and that stutters; consider calling this DiscoveryService
```

@vieux: Not sure about this? Maybe it makes sense

```
discovery/generator.go:28:2: can probably use "var result []string" instead
discovery/file/file.go:29:2: can probably use "var result []string" instead
```

@chanwit: Could have have a look at the generator one?

```
scheduler/filter/port_test.go:246:5: struct field IpAddress should be IPAddress
scheduler/filter/port_test.go:247:5: struct field IpPrefixLen should be IPPrefixLen
```
Yeah, I don't see how we could fix those since the error is in Docker.

@vieux: Thoughts?

**Comment by aluzzardi** [comment]
@technolo-g: Thanks, this is fantastic!

I would probably make this PR all about fixing golint issues rather than enabling golint in one step (as in, I'd probably revert .travis.yml in this PR and make another one with just that).

As a second step, I'll look with @vieux @abronan and @chanwit on how to fix the remaining golint issues, then we can merge the travis PR.

WDYT?

**Comment by technolo-g** [comment]
@aluzzardi SGTM. I will:
- Pull out the travis changes
- Create a new branch with the travis changes
- Create a PR for that change that depends on this one.

**Comment by vieux** [comment]
@aluzzardi I agree, @technolo-g you should merge this one without the travis, then we will take care of fixing the remaining issues.

Thanks again @technolo-g

**Comment by technolo-g** [comment]
@vieux @aluzzardi, this should be gtg.

**Comment by aluzzardi** [comment]
LGTM

**Comment by vieux** [comment]
LGTM

**Pull request merged**
