### PR TITLE
remove coverage from the README since we don't use it anymore

### PR DESCRIPTION
**Pull request by vieux**
Signed-off-by: Victor Vieux <vieux@docker.com>

### CODE REVIEW

**Comment by vieux** [comment]
ping @nishanttotla @dongluochen

**Comment by nishanttotla** [comment]
LGTM.

Btw, why aren't we using it?

**Comment by dongluochen** [comment]
LGTM.

**Comment by vieux** [comment]
@nishanttotla because coveralls is crap, the way it counts is not great and often their website is down (it even make our travis fail)

**Pull request merged**
