### PR TITLE
convert docs Dockerfiles to use docs/base:oss

### PR DESCRIPTION
**Pull request by SvenDowideit**
speeds up `make docs`, and reduces the svn checkout timeout issue.

### CODE REVIEW

**Comment by nishanttotla** [comment]
LGTM

Ping @moxiegirl

**Comment by vieux** [comment]
LGTM

**Comment by SvenDowideit** [comment]
@thaJeztah @jamtur01

**Comment by MHBauer** [comment]
LGTM

**Comment by jamtur01** [comment]
LGTM

**Comment by thaJeztah** [comment]
LGTM

think that's enough LGTMS :joy:

**Pull request merged**
