### PR TITLE
switch to golang 1.5

### PR DESCRIPTION
**Pull request by vieux**
Signed-off-by: Victor Vieux <vieux@docker.com>

### CODE REVIEW

**Comment by chanwit** [comment]
You did it!!
LGTM

**Comment by vieux** [comment]
ping @docker/swarm-maintainers

**Comment by aluzzardi** [comment]
I think there are other places.

travis?

**Comment by aluzzardi** [comment]
And `test/integration/Dockerfile`

**Comment by abronan** [comment]
LGTM we should be careful about the first failure on leadership tests though.. might happen again. Might be worth re-running the tests.

**Comment by vieux** [comment]
ping @aluzzardi good catch, I added them.

**Comment by jimmyxian** [comment]
@vieux Do we need update README.md? :)
> Beginning with Swarm 0.4 golang 1.4.x or later is required for building Swarm. Refer to the Go installation page to download and install the golang 1.4.x or later package.

**Comment by vieux** [comment]
@jimmyxian good point

**Comment by MHBauer** [comment]
Is go1.5 required? Should travis have a 1.5 build in addition to a 1.4.2 build? 

I am still unfamiliar with the go ecosystem, so I am not sure of the pros and cons. I come from a Java background where point releases are huge and happen with years between them.

This more of a question of curiosity rather than a suggestion.

**Comment by vieux** [comment]
@MHBauer go 1.x will always be backward compatible, no breaking changes.
We decided not to test 1.4.2 because, at some point we might drop the 1.4.2 support if we use features that are only in 1.5

Performances and cross compilation are much better in 1.5

Generally, we update to the latest version of go as soon as it's stable.

**Comment by vieux** [comment]
@jimmyxian I don't think we need to update the Readme yet, as 1.5 is not required, so 1.4.x or later is still valid.

**Comment by abronan** [comment]
Ok merging then ;) we'll change the doc in another PR if required

**Comment by jimmyxian** [comment]
@vieux OK

**Pull request merged**
