### PR TITLE
Moving to official consul image

### PR DESCRIPTION
**Pull request by nishanttotla**
There's now an official consul image: https://hub.docker.com/_/consul/

Let's see if our integration tests work with that.

Signed-off-by: Nishant Totla nishanttotla@gmail.com

### CODE REVIEW

**Comment by nishanttotla** [comment]
Nope, doesn't really seem to work, not yet sure why.

**Comment by abronan** [comment]
@nishanttotla thought about doing the migration, yet I'm not sure this is quite "the same" image, might require some tweaks to make it work.

Logs are throwing: `cannot set or renew session for ttl, unable to operate on sessions`

My guess is that the config passed to the image (which shrinks the minimum ttl value to `1s`) is not interpreted and thus operations on session gets rejected because the minimum ttl must be `10s`. Will look into it and commit on top.

**Comment by thaJeztah** [comment]
Yeah, looks like it has a really different entrypoint script, so guess it expects different arguments being passed

**Comment by nishanttotla** [comment]
@abronan makes sense. Hopefully it's not too hard to do (the older image is fine too for now)

**Comment by vieux** [comment]
Nice~

**Pull request closed without merging**
