### PR TITLE
Call SyncCluster at etcd client initialization

### PR DESCRIPTION
**Pull request by abronan**
Signed-off-by: Alexandre Beslic <abronan@docker.com>

### CODE REVIEW

**Comment by abronan** [comment]
ping @aluzzardi

**Comment by aluzzardi** [comment]
We'll have to create integration tests that set up a replicated environment :/

I'm pretty sure if you kill the etcd leader our discovery becomes fubar.

Please add a FIXME on top of it

LGTM

**Comment by abronan** [comment]
@aluzzardi Yes either we refresh on each operation (overkill but we are pretty much sure we have an up to date state) or we sync periodically in a goroutine. Not sure what is the good practice with etcd.

Added the FIXME.

**Comment by aluzzardi** [comment]
LGTM

**Pull request merged**
