### PR TITLE
[EXPERIMENTAL] Add Kubernetes support to swarm

### PR DESCRIPTION
**Pull request by preillyme**
This PR adds all the code for supporting Kubernetes.
The main code base is barely touched, most of the added code is on cluster/kubernetes/
ping @aluzzardi @abronan @kelseyhightower @samalba @vieux

### CODE REVIEW

**Comment by preillyme** [comment]
FYI: This is still a WIP.

**Comment by preillyme** [comment]
Hey @dpetersen and @alexwelch can you two take a look at this as well?

**Comment by abronan** [comment]
@kelseyhightower Needs a `golint` check for travis to pass :)

The failure on Jenkins is unrelated so we are good.

**Comment by preillyme** [comment]
@abronan I've fixed the golint issues.

**Comment by kelseyhightower** [comment]
@abronan Look at the last commit. The 10 second sleep should be gone and we only sleep between api calls when we check for pod status.

**Comment by abronan** [comment]
@kelseyhightower Ok I was looking at each commit and saw that this was updated. Can you squash the two commits with the initial implementation and restoring the missing things, that would be easier to review. Thanks!

**Comment by abronan** [comment]
ping @aluzzardi for review

**Comment by preillyme** [comment]
@kelseyhightower would you like to rebase this PR or should I?

**Comment by sstarcher** [comment]
@preillyme can someone rebase the PR :+1:

**Comment by preillyme** [comment]
@sstarcher I'm currently working through https://gist.github.com/preillyme/ac875e6e8abe67b76a45de027f3980fa and I've asked @kelseyhightower to take a look as well.

**Comment by preillyme** [comment]
It's showing `unknown repository` now. But https://github.com/kismatic/swarm/tree/cluster-kubernetes is updated and the `merge conflicts` should be resolved @sstarcher.

**Comment by eparis** [comment]
you closed the issue?

**Comment by preillyme** [comment]
@eparis moved it to https://github.com/docker/swarm/pull/2084 to work around the `unknown repository` issue according to GitHub support.

**Pull request closed without merging**
