### PR TITLE
Tweak docs introduction

### PR DESCRIPTION
**Pull request by bfirsh**
I had a go at making it a bit punchier and making the formatting consistent with other docs / projects.

### CODE REVIEW

**Comment by vieux** [comment]
ping @SvenDowideit

**Comment by SvenDowideit** [comment]
LGTM - @fredlf

**Comment by fredlf** [comment]
LGTM. Nicely done.

**Comment by fredlf** [comment]
Ping @bfirsh You'll have to merge. I don't have privs.

**Comment by bfirsh** [comment]
I don't either. :)

**Pull request merged**
