### PR TITLE
Fix Consul Leader Election Failure on multi-server and leader soft-restart

### LINKED ISSUE #1782: Restarting Consul leader leaves redundant Swarm cluster without a primary manager
## What I have

- 5 nodes cluster
- each node runs Consul 0.6.3
- each node runs Swarm 1.1.0
- Swarm is setup to use `consul://localhost:8500` for discovery and redundancy

## What I do

- I'm rebooting random nodes, but between reboots, I let the cluster settle (i.e. I wait until all nodes are shown healthy, both by Consul and Swarm with `docker info`)

## What I expect to see

- everything is fine

## What I see instead

- when rebooting the Consul leader (which is NOT the Swarm primary at that time), the Swarm primary loses the cluster leadership, and never recovers

## Possibly related (but unsure)

#1088 #1025 #1491 #982 

## Details

Here are a bunch of logs from Consul + Swarm managers + output of `docker info`.

Towards the end of the logs:
- Swarm primary is node 3
- Consul leader is node 5
- after rebooting node 2, everything was OK
- after rebooting node 5, we're dead

Note: after collecting those logs, I restarted node 3, and eventually a leader election happened and my cluster works again.

[consul-1.log.txt](https://github.com/docker/swarm/files/123262/consul-1.log.txt)
[consul-2.log.txt](https://github.com/docker/swarm/files/123263/consul-2.log.txt)
[consul-3.log.txt](https://github.com/docker/swarm/files/123264/consul-3.log.txt)
[consul-4.log.txt](https://github.com/docker/swarm/files/123265/consul-4.log.txt)
[consul-5.log.txt](https://github.com/docker/swarm/files/123266/consul-5.log.txt)
[swarm-agent-master-1.log.txt](https://github.com/docker/swarm/files/123267/swarm-agent-master-1.log.txt)
[swarm-agent-master-2.log.txt](https://github.com/docker/swarm/files/123268/swarm-agent-master-2.log.txt)
[swarm-agent-master-3.log.txt](https://github.com/docker/swarm/files/123269/swarm-agent-master-3.log.txt)
[swarm-agent-master-4.log.txt](https://github.com/docker/swarm/files/123270/swarm-agent-master-4.log.txt)
[swarm-agent-master-5.log.txt](https://github.com/docker/swarm/files/123271/swarm-agent-master-5.log.txt)
[swarm-info-1.log.txt](https://github.com/docker/swarm/files/123273/swarm-info-1.log.txt)
[swarm-info-2.log.txt](https://github.com/docker/swarm/files/123272/swarm-info-2.log.txt)
[swarm-info-3.log.txt](https://github.com/docker/swarm/files/123275/swarm-info-3.log.txt)
[swarm-info-4.log.txt](https://github.com/docker/swarm/files/123274/swarm-info-4.log.txt)
[swarm-info-5.log.txt](https://github.com/docker/swarm/files/123276/swarm-info-5.log.txt)

### PR DESCRIPTION
**Pull request by abronan**
This fixes an error with Consul which fails to see a new
swarm leader after a consul leader soft restart because
of session renewal and missing status update on leadership

Fixes #1782 

Depends on docker/libkv#120 and docker/leadership#2

Needs more testing with other stores.

/cc @vieux @jpetazzo

Signed-off-by: Alexandre Beslic <alexandre.beslic@gmail.com>

### CODE REVIEW

**Comment by vieux** [comment]
LGTM

**Comment by vieux** [comment]
ping @nishanttotla @dongluochen

**Comment by abronan** [comment]
**Do not merge yet**, don't forget this depends on two other PRs :sweat_smile:

**Comment by vieux** [comment]
:sweat_smile:

**Comment by dongluochen** [comment]
LGTM

**Pull request merged**
