### PR TITLE
Fixing links after move of repo

### PR DESCRIPTION
**Pull request by moxiegirl**
- @bfirsh asked for rename of repo which broke a number of links in this doc. 
- User tweeted about TODO in doc; fixed that

Signed-off-by: Mary Anthony <mary@docker.com>

### CODE REVIEW

**Comment by mgoelzer** [comment]
LGTM

**Comment by moxiegirl** [comment]
author LGTM

**Comment by vieux** [comment]
LGTM

**Comment by abronan** [comment]
LGTM

**Pull request merged**
