### PR TITLE
add Chanwit to the MAINTAINERS file

### PR DESCRIPTION
**Pull request by vieux**

### CODE REVIEW

**Comment by vieux** [comment]
ping @docker/swarm-maintainers

**Comment by vieux** [comment]
ping @chanwit

**Comment by thaJeztah** [comment]
:+1: congrats @chanwit

**Comment by abronan** [comment]
:balloon: :tada:

**Comment by chanwit** [comment]
Thank you

**Comment by jimmyxian** [comment]
:sparkles: :clap:

**Comment by thaJeztah** [comment]
Please "LGTM", otherwise it'll never get merged :-)

**Comment by chanwit** [comment]
LGTM

Thank you @thaJeztah :)

**Comment by aluzzardi** [comment]
Welcome @chanwit ! Please merge this PR on your own :)

**Comment by chanwit** [comment]
Thank you @aluzzardi but it seems the merge button is still not shown here for me :)

**Comment by aluzzardi** [comment]
@chanwit You have to accept the invitation somewhere in GitHub :)

Also, please join #docker-swarm and #docker-maintainers on IRC!

**Comment by chanwit** [comment]
lol sorry @aluzzardi I was snowed under by the Github mails.
I'm good to go now. Thanks!

**Comment by thaJeztah** [comment]
\o/

**Pull request merged**
