### PR TITLE
stress test: First short at stress testing Swarm in an automated way.

### PR DESCRIPTION
**Pull request by aluzzardi**
Signed-off-by: Andrea Luzzardi <aluzzardi@gmail.com>

### CODE REVIEW

**Comment by chanwit** [comment]
How many node swarm should be able to handle properly before getting 1.0?
Do you have some numbers in mind?

**Comment by ehazlett** [comment]
:+1: nice!  i'll test this out :)

**Comment by aluzzardi** [comment]
@chanwit 100-ish

**Comment by abronan** [comment]
Current status: 300 containers on 30 nodes, slowly ramping up :smile:

**Comment by aluzzardi** [comment]
Yeah, I went up to 1000 containers on 100 nodes but started having hiccups :)

**Comment by abronan** [comment]
@aluzzardi My machine started having hiccups way before the 100 nodes milestone :sob: 

It's a great first shot and gives an idea of Swarm is capable of. Would be great if in the future, we could distribute the load between multiple machines/docker daemons for this stress tests.

**Comment by abronan** [comment]
Anyway, LGTM

**Comment by vieux** [comment]
LGTM

**Pull request merged**
