### PR TITLE
Refactoring code around image ref generation

### PR DESCRIPTION
**Pull request by nishanttotla**
Follow up to #2272.

Moving code for generating image refs from repo and tag to one place.

Signed-off-by: Nishant Totla <nishanttotla@gmail.com>

### CODE REVIEW

**Comment by nishanttotla** [comment]
Ping @abronan @vieux

**Comment by abronan** [comment]
LGTM

**Comment by nishanttotla** [comment]
Ping @dongluochen

**Comment by dongluochen** [comment]
LGTM

**Pull request merged**
