### PR TITLE
fix volume tests with the last docker engine

### PR DESCRIPTION
**Pull request by vieux**
Signed-off-by: Victor Vieux <vieux@docker.com>

### CODE REVIEW

**Comment by vieux** [comment]
ping @aluzzardi @abronan

**Comment by jimmyxian** [comment]
` @test "docker volume" `  --->  `@test "docker volume ls" `
Other than that. :)
LGTM

**Comment by vieux** [comment]
@jimmyxian good catch

**Comment by abronan** [comment]
LGTM when description is fixed :ghost:

**Pull request merged**
