### PR TITLE
make Operating System ouput compatible in docker info

### LINKED ISSUE #2096: `docker swarm info` and `docker info` show some different details
Hi, all, 
I found that `docker swarm info` and `docker info` showed some different details in docker 1.10.0 and swarm/master.

Here are some aspects related to this situation:
- Images
- OSType
- Operating System
- Architecture
- Plugins(nothings)

**How to reporduce:**
I have only one docker host(192.168.2.59:2376) with swarm manager on it. Here is how I start my swarm manager on 192.168.2.59:

```
$GOPATH/bin/swarm -l debug manage -H tcp://0.0.0.0:2375 nodes://192.168.2.59:2376
```

Here is `docker -H tcp://127.0.0.1:2375` output:

```
root@ubuntu:~# docker -H tcp://127.0.0.1:2375 info
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 41
Server Version: swarm/1.2.0
Role: primary
Strategy: spread
Filters: health, port, dependency, affinity, constraint
Nodes: 1
 ubuntu: 192.168.2.59:2376
  └ Status: Healthy
  └ Containers: 2
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 2.052 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=3.19.0-25-generic, operatingsystem=Ubuntu 14.04.3 LTS, storagedriver=aufs
  └ Error: (none)
  └ UpdatedAt: 2016-04-08T04:40:31Z
  └ ServerVersion: 1.10.0
Plugins:
 Volume:
 Network:
Kernel Version: 3.19.0-25-generic
Operating System: linux
Architecture: amd64
CPUs: 1
Total Memory: 2.052 GiB
Name: ubuntu
```

And here is `docker -H tcp://127.0.0.1:2376` output:

```
root@ubuntu:~# docker -H tcp://127.0.0.1:2376 info
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 55
Server Version: 1.10.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 365
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 3.19.0-25-generic
Operating System: Ubuntu 14.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.954 GiB
Name: ubuntu
ID: RDEJ:ZCV6:CJH5:UCNB:P5RR:66LB:JZSO:YACX:TBL3:PYMV:2F77:KBUA
WARNING: No swap limit support
```

### PR DESCRIPTION
**Pull request by allencloud**
In docker info and docker_swarm info, there are some incompatibilities.
This pr did:
1. make Operating System output same as Docker Daemon
2. Add new dependencies:
```
github.com/mattn/go-shellwords
github.com/docker/docker/pkg/parsers/operatingsystem
```

Fixes #2096 

Signed-off-by: Sun Hongliang <allen.sun@daocloud.io>

### CODE REVIEW

**Comment by allencloud** [comment]
I think I updated the Godeps in the wrong way  :(

**Comment by nishanttotla** [comment]
@allencloud how did you update Godeps?

**Comment by vieux** [comment]
@allencloud `pkg/platform` doesn't work on mac, that's why we aren't using it right now.

**Comment by allencloud** [comment]
@nishanttotla 
1. godep restore
2. add dependency in code
3. godep save
4. modify Godeps.json

**Comment by allencloud** [comment]
@vieux 
If then, I will leave platform package.

**Comment by nishanttotla** [comment]
@allencloud depending on the Godep version you use, you might have to do `godep save ./...`

**Comment by allencloud** [comment]
It seems that package `github.com/docker/docker/pkg/parsers/operatingsystem` can not work on MacOS, neither can packager  `github.com/docker/docker/pkg/platform`.

Is it because there is no *_darwin.go in the both packages? @vieux 

And no *_darwin.go in package `github.com/docker/docker/pkg/parsers/kernel` in Godeps for a long time, why there is no error reported in travis-ci?

**Comment by vieux** [comment]
yes that's why.

In `github.com/docker/docker/pkg/parsers/kernel` we aren't using any platform dependent code.

**Comment by allencloud** [comment]
If then, I think we had better close this pr?

**Comment by dongluochen** [comment]
Closing for the lack of darwin support in Go.

**Pull request closed without merging**
