### PR TITLE
Name changing slave to agent

### PR DESCRIPTION
**Pull request by jimenez**
Signed-off-by: Isabel Jimenez <contact@isabeljimenez.com>

### CODE REVIEW

**Comment by abronan** [comment]
LGTM++++

**Comment by dongluochen** [comment]
Thanks @jimenez. Please update slave_test.go.

**Comment by abronan** [comment]
`cluster/mesos/slave_test.go:13: undefined: newSlave` woot yes needs tests update :smile:

**Comment by vieux** [comment]
LGTM

**Pull request merged**
