### PR TITLE
Switch to install

### PR DESCRIPTION
**Pull request by moxiegirl**
The team believes that some confusion around installing Swarm could be alleviated by having an Install Swarm entry off the **Install** menu.

I'd propose moving the current "easy to use" trial swarm  page as our install.  

Signed-off-by: Mary Anthony <mary@docker.com>

### CODE REVIEW

**Comment by moxiegirl** [comment]
ping @aluzzardi @abronan @vieux Hi guys, you can see this working here:

http://docker-manthony.s3-website-us-east-1.amazonaws.com/swarm/install-w-machine/

**Comment by vieux** [comment]
@moxiegirl could the title be "Docker Swarm" to be consistent with the rest ?

**Comment by moxiegirl** [comment]
Sure. http://docker-manthony.s3-website-us-east-1.amazonaws.com/ Refresh your browser!

**Comment by moxiegirl** [comment]
@aluzzardi @vieux @abronan If y'all want to merge this, I'll cherry pick it into docs and send it live tonight.

**Comment by aluzzardi** [comment]
LGTM

**Comment by vieux** [comment]
LGTM

**Comment by moxiegirl** [comment]
Thanks guys.

**Pull request merged**
