### PR TITLE
add simple strategy test

### PR DESCRIPTION
**Pull request by vieux**
Fix https://github.com/docker/swarm/issues/888

### CODE REVIEW

**Comment by vieux** [comment]
ping @nishanttotla @dongluochen @abronan

**Comment by MHBauer** [comment]
Looks good. I'd rather it said `Reserved CPUs: 1` must match twice somehow, but I'm not sure how to pull that off.

**Comment by nishanttotla** [comment]
LGTM.

**Comment by dongluochen** [comment]
LGTM.

**Pull request merged**
