### PR TITLE
Dependency Filter: co-schedule dependent containers on the same node.

### LINKED ISSUE #251: How to deal with --link --volume_from network container etc.
In a word, most of the cases in real world requires relationship between Docker containers like --link --volume-from --net=container, that means, at least, swarm should be able to schedule those containers to one host.

But I did not see this kind of strategy in swarm currently, is it under developing or swarm has other approach?

### PR DESCRIPTION
**Pull request by aluzzardi**
Supported dependencies:
- Shared volumes: `--volumes-from=dependency`
- Links: `--link=dependency:alias`
- Shared network stack: `--net=container:dependency`

Fix #251

### CODE REVIEW

**Comment by vieux** [comment]
LGTM

**Comment by aanand** [comment]
Amazing. Will try this out tomorrow.

**Comment by vieux** [comment]
@aanand thanks!

**Comment by bacongobbler** [comment]
big :+1: from me! Definitely something required to add swarm as a supported scheduler for Deis :)

**Comment by aanand** [comment]
:+1: This works great.

**Comment by vieux** [comment]
@aanand thanks for the feedback!

**Comment by anentropic** [comment]
Do I understand correctly that the current recommended workaround is to use this pattern: https://docs.docker.com/engine/articles/ambassador_pattern_linking/

...to break the `link` dependency between containers in my docker-compose.yml so that they can be scheduled to different nodes?

**Comment by abronan** [comment]
@anentropic The current way to link containers between different nodes is to use the `overlay` networking feature of docker `1.9`/`1.10` and use the `docker network` command.

Please refer to the [documentation](https://docs.docker.com/engine/userguide/networking/get-started-overlay/) if you want more details on how to setup multi-host networking and get it working with Docker Compose.

After that you'll be able to use a single Compose file to describe your stack and all the containers are created on the same overlay across different hosts, thus could see and discover each other without using `--link` or the `ambassador pattern`.

**Comment by anentropic** [comment]
Thanks!

Shouldn't this be the default though?  How am I supposed to know I need a specialist feature "multi-host networking overlay" in order for things to work as expected?

It's confusing because there's a bunch of places like https://github.com/docker/compose/blob/master/SWARM.md which still say cross-node links are not possible.

**Comment by anentropic** [comment]
for anyone using docker-compose, you don't need to manually create an overlay network as described in the docs linked above

instead upgrade to compose 1.6 and see the new docs here, where network stuff is configured from the compose file (...this is starting to make sense!):
https://github.com/docker/compose/blob/1.6.0-rc1/docs/networking.md
(and here https://github.com/docker/compose/blob/1.6.0-rc1/docs/compose-file.md)

**Comment by bfirsh** [comment]
@anentropic Recommended solution is, as @abronan says, to use the new Compose file and not specify any links. All Compose containers will be scheduled onto the same overlay network which spans multiple Swarm nodes.

@abronan Docker 1.10 raises an interesting new issue now though – it is possible to use links in an overlay network, so containers probably shouldn't be co-scheduled if they're using links and on an overlay network. Shall I raise a new issue for this?

**Comment by aanand** [comment]
> if they're using links and on an overlay network

@mavenugo what's the precise logic for whether `--link` means an alias or an old-style link? Is it an old-style link if the container is connected *solely* to the `bridge` network?

**Comment by mavenugo** [comment]
@aanand 

> what's the precise logic for whether --link means an alias or an old-style link? Is it an old-style link if the container is connected solely to the bridge network?

That's correct. To be more specific. It is an old-style link only  if the container is connected to the *default* bridge network (`docker0`)

**Comment by aanand** [comment]
What if it's connected to both that network and a custom network?

**Comment by mavenugo** [comment]
Both `--link` and `--alias` are network scoped. (with `--link` further scoped for a container).
If a container is connected to both the default and custom network, then the `--link` will work on each of these networks just as intended. The only exception to the rule is that, if the user prefers the `ENV` variables, then the container must be started with default bridge network in `--net`.

**Pull request merged**
