### PR TITLE
travis: Lint test files (ensure they are not space indented)

### PR DESCRIPTION
**Pull request by aluzzardi**
Signed-off-by: Andrea Luzzardi <aluzzardi@gmail.com>

### CODE REVIEW

**Comment by aluzzardi** [comment]
/cc @ehazlett @nathanleclaire 

You might find this useful. I hated having a mix of tab/spaces indentation in bats files. This makes travis fail if the file is space-indented, you can adjust to your liking.

**Comment by aluzzardi** [comment]
@vieux Can you review?

**Comment by ehazlett** [comment]
Thanks!

**Comment by nathanleclaire** [comment]
Oh, neat.  We'll definitely have to look into this.

**Comment by vieux** [comment]
Awesome LGTM

**Pull request merged**
