### PR TITLE
Check unique container name on create and rename for Mesos cluster

### PR DESCRIPTION
**Pull request by ezrasilvera**
When running on top of Mesos there is currently no check for name uniqueness. 
The Mesos framework changes the actual container name by adding a random ID as prefix  This means that the docker Engine will not have any name conflicts as each container has a unique name.

However, from a user perspective the user can create as many containers with the exact same name without getting any warning or error. There are two major issues with this behaviour:
1) The user will not be able to address these containers by name because of the ambiguity
2) We get different user experience when using Mesos Vs using native Swarm cluster

### CODE REVIEW

**Comment by ezrasilvera** [comment]
ping @jimenez

**Comment by ezrasilvera** [comment]
@dongluochen how can we push this forward?  (BTW, there are additional PRs related to the Mesos framework that seems to be blocked ...)

**Comment by ezrasilvera** [comment]
@dongluochen can we merge ?

**Comment by dongluochen** [comment]
LGTM

ping @nishanttotla @allencloud.

**Comment by allencloud** [comment]
LGTM
Thanks @ezrasilvera

**Pull request merged**
