### PR TITLE
fix static compile with go 1.4

### PR DESCRIPTION
**Pull request by vieux**
See https://github.com/golang/go/issues/9344

### CODE REVIEW

**Comment by vieux** [comment]
@tianon is this the best to do or should we keep the tag and add `-installsuffix netgo` ?

**Comment by tianon** [comment]
Yeah that second option is what the go maintainers told us to do (keep the tag and add the installsuffix).

**Comment by vieux** [comment]
@tianon OK, LGTY ?

**Comment by tianon** [comment]
:+1: LGTM

**Pull request merged**
