### PR TITLE
Remove Volume

### PR DESCRIPTION
**Pull request by ehazlett**
This implements the remove volume functionality coming in 1.9.

### CODE REVIEW

**Comment by vieux** [comment]
@ehazlett duplicate of #1208 ?

**Comment by ehazlett** [comment]
doh!  sorry -- i thought i looked for this on friday :(  sorry!

**Comment by vieux** [comment]
@ehazlett feel free to LGTM #1208 :)

**Comment by ehazlett** [comment]
@vieux done :) -- thanks for adding create too :+1:

**Pull request closed without merging**
