### PR TITLE
Change the scheduler lock in Mesos cluster

### PR DESCRIPTION
**Pull request by ezrasilvera**
Addressing the issue in  #1495 . Need to change the scheduler lock , otherwise it blocks all incoming tasks and doesn't allow concurrent usage

Signed-off-by: Ezra Silvera <ezra@il.ibm.com>

### CODE REVIEW

**Comment by MHBauer** [comment]
I am not familiar with the code.

Looking at it, this is quite an aggressive advancement of the lock. Looking at the code I would think we could unlock right after `SelectNodesForContainer` on L#449. I don't see any other uses of the scheduler or the cluster after that look like they could be effected.

Alternatively, and I'd have to do more research, we could pull the lock inside `SelectNodesForContainer`.

**Comment by ezrasilvera** [comment]
@MHBauer See the issue I opened for clarifications. The original lock was using defer to unlock blocking till the function completes. The problem is that the in that fuction there is a call to monitor() which was blocking till the container was in RUNNING state. this means that you must wait for the previous request to change to RUNNING before new request can be handled which as you can see in the graph I attached make 0 concurrency. 
I wanted to avoid side effects, as there are other functions that use the scheduler as well, so I pushed the unlock as far as I could which is just before the blocking call to monitor()

**Comment by abronan** [comment]
ping @vieux @jimenez

**Comment by tnachen** [comment]
This mostly looks good to me. We are refactoring this path (cc @jimenez ) as it currently only able to launch one task per offer but we want to be able to pack as much tasks per offer.

**Comment by jimenez** [comment]
LGTM Thanks @ezrasilvera

**Pull request merged**
