### PR TITLE
bug fix: check status code in exec

### PR DESCRIPTION
**Pull request by jimmyxian**
Fix this issue: https://github.com/docker/swarm/issues/689
Signed-off-by: Xian Chaobo <xianchaobo@huawei.com>

### CODE REVIEW

**Comment by vieux** [comment]
LGTM

**Comment by aluzzardi** [comment]
Could this be part of the `exec` integration test? :)

It should be pretty trivial to test `$output == "Container * is not running"`

**Comment by jimmyxian** [comment]
ping @aluzzardi 
Added test when container is not running.Check again. TKS

**Comment by vieux** [comment]
LGTM ping @abronan

**Comment by abronan** [comment]
LGTM

**Pull request merged**
