### PR TITLE
update dockerclient

### PR DESCRIPTION
**Pull request by vieux**
Signed-off-by: Victor Vieux <vieux@docker.com>

### CODE REVIEW

**Comment by vieux** [comment]
ping @dongluochen

**Comment by vieux** [comment]
ping @abronan

**Comment by vieux** [comment]
@dongluochen today `docker inspect <container>` on swarm is using a proxy so you already see `Networks` in docker inspect but I think we should still merge this PR so we have the networks in memory.

**Comment by abronan** [comment]
LGTM

**Comment by dongluochen** [comment]
LGTM.

**Pull request merged**
