### PR TITLE
Explicitly updating client version for Engine 1.13

### LINKED ISSUE #2557: Update API version function
Currently, this is how the API Client version is set, in `engine.go`:

```
// Update API Version in apiClient
func (e *Engine) updateClientVersionFromServer(serverVersion string) {
	// v will be >= 1.8, since this is checked earlier
	v := version.Version(serverVersion)
	switch {
	case v.LessThan(version.Version("1.9")):
		e.apiClient.UpdateClientVersion("1.20")
	case v.LessThan(version.Version("1.10")):
		e.apiClient.UpdateClientVersion("1.21")
	case v.LessThan(version.Version("1.11")):
		e.apiClient.UpdateClientVersion("1.22")
	case v.LessThan(version.Version("1.12")):
		e.apiClient.UpdateClientVersion("1.23")
	default:
		e.apiClient.UpdateClientVersion("1.24")
	}
}
```
We should update this to the latest API version, and probably outdate older versions too at this point.

### PR DESCRIPTION
**Pull request by nishanttotla**
Fix #2557

cc @dongluochen @allencloud  

Signed-off-by: Nishant Totla <nishanttotla@gmail.com>

### CODE REVIEW

**Comment by dongluochen** [comment]
LGTM

**Comment by nishanttotla** [comment]
@dongluochen `network inspect` tests failing on 1.12 here as well, so it's not flaky.

The `leak tcp connections` and `port filter` tests on master do seem flaky though.

**Comment by dongluochen** [comment]
I'll fix the `network inspect` test.

**Comment by nishanttotla** [comment]
@dongluochen rebased on top of `network inspect` test fix.

**Pull request merged**
