### PR TITLE
Add load unit test

### PR DESCRIPTION
**Pull request by jimmyxian**
Add unit test for load (https://github.com/docker/swarm/pull/609)

### CODE REVIEW

**Comment by aluzzardi** [comment]
>  Coverage increased (+2.29%) to 61.76%

:fireworks: :fireworks: :fireworks:

We are finally in the `60+%` range. Will do a review tomorrow.

Thanks @jimmyxian !

**Comment by jimmyxian** [comment]
@aluzzardi OK...   :)

**Comment by vieux** [comment]
LGTM

**Comment by aluzzardi** [comment]
LGTM

**Pull request merged**
