### PR TITLE
add docker run --net-alias, docker network connect --ip and docker network connect --alias tests

### LINKED ISSUE #1713: net-alias not working with swarm
Swarm is ignoring --net-alias flag introduced with engine 1.10. This isn't an inspect cosmetic issue as the functionality of dns lookup for that net alias is not working.  This functionality works fine with single engine.

Swarm Version : 1.1.0-rc-2
Steps to Reproduce ( assuming multihost networking is configured):

- Create an overlay network called 'bar'

```
$docker -H 0.0.0.0:3375 network create -d overlay bar
7f979ec613f89e02d1626531d6dfadca5cd6ffa3e8e1c7114714a41361d5e767
```
- Create a container part of that network with a --net-alias of `test` : 

```
$ docker -H 0.0.0.0:3375 run -itd --name=foo --net=bar --net-alias=test ubuntu
5382d537e93f177dd18ef32165366964c78d96b52a0f242318906f2d6378d21f
```

- Check that "Aliases" show a `null` value. 

```
$docker inspect -f '{{ json .NetworkSettings }}' foo | python -mjson.tool
{
    "Bridge": "",
    "EndpointID": "",
    "Gateway": "",
    "GlobalIPv6Address": "",
    "GlobalIPv6PrefixLen": 0,
    "HairpinMode": false,
    "IPAddress": "",
    "IPPrefixLen": 0,
    "IPv6Gateway": "",
    "LinkLocalIPv6Address": "",
    "LinkLocalIPv6PrefixLen": 0,
    "MacAddress": "",
    "Networks": {
        "bar": {
            "Aliases": null, <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
            "EndpointID": "876b5632c6db11e0c830217978baa4725b79ca02ffa6b22ea3b41c249ccd046c",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAMConfig": null,
            "IPAddress": "10.0.0.2",
            "IPPrefixLen": 24,
            "IPv6Gateway": "",
            "Links": null,
            "MacAddress": "02:42:0a:00:00:02",
            "NetworkID": "7f979ec613f89e02d1626531d6dfadca5cd6ffa3e8e1c7114714a41361d5e767"
        }
    },
    "Ports": {},
    "SandboxID": "abdfcd9d04f370a179c6f795a349e91553979916cce302c30c11c209f0ca43fc",
    "SandboxKey": "/var/run/docker/netns/abdfcd9d04f3",
    "SecondaryIPAddresses": null,
    "SecondaryIPv6Addresses": null
}
```

### PR DESCRIPTION
**Pull request by vieux**
Fix #1713 
ping @nicolaka

### CODE REVIEW

**Comment by dongluochen** [comment]
Can we re-run test? It doesn't look related. 
```
not ok 88 docker network disconnect connect
# (in test file api/network.bats, line 80)
#   `[[ "${output}" != *"\"Containers\": {}"* ]]' failed
```

**Comment by vieux** [comment]
@dongluochen restarted another fails, it's unrelated

**Comment by dongluochen** [comment]
LGTM.

**Comment by abronan** [comment]
LGTM

**Pull request merged**
